const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),test=require('node:test');
const source=fs.readFileSync('application.js','utf8');
function setup(){const nodes={};function node(){return {hidden:false,textContent:'',value:'',disabled:false,children:[],replaceChildren(){this.children=[]},append(n){this.children.push(n)},get firstChild(){return this.children[0]}}}const docEvents={},events={},requests=[];let authCallback;const client={from:()=>({select(){return this},eq(){return this},maybeSingle(){return new Promise(resolve=>requests.push(resolve))}}),auth:{getSession:async()=>({data:{session:null}}),onAuthStateChange(cb){authCallback=cb},signOut:async()=>({}),signInWithPassword:async()=>({error:Error('invalid')})}};const c={confirm:()=>false,document:{getElementById:id=>nodes[id]??=node(),querySelectorAll:()=>[],createElement:()=>({...node(),contentWindow:{}}),addEventListener:(k,f)=>docEvents[k]=f},window:{addEventListener:(k,f)=>events[k]=f},history:{replaceState(_a,_b,h){c.location.hash=h}},location:{hash:'',origin:'https://example.test'},supabase:{createClient:()=>client},setTimeout:f=>f()};for(const id of ["module","workspace","login","logout","identity","sectionNotice","home"])c.document.getElementById(id);vm.createContext(c);vm.runInContext(source,c);return {nodes,events,requests,client,auth:s=>authCallback('TEST',s),click:s=>docEvents.click({target:{closest:()=>({dataset:{section:s}})}})};}
const session=id=>({user:{id,email:id+'@example.test'}}),tick=()=>new Promise(r=>setImmediate(r));
test('No module without membership; membership failure stays closed',async()=>{const a=setup();await tick();a.click('scan');assert.equal(a.nodes.module.firstChild,undefined);a.auth(session('outsider'));a.requests.shift()({data:null});await tick();assert.equal(a.nodes.workspace.hidden,true);assert.match(a.nodes.status.textContent,/ne dispose pas/);});
test('Authorized navigation replaces frames and logout clears immediately',async()=>{const a=setup();await tick();a.auth(session('member'));a.requests.shift()({data:{role:'operator'}});await tick();assert.equal(a.nodes.workspace.hidden,false);a.click('scan');const old=a.nodes.module.firstChild;assert.equal(old.src,'index.html?embedded=1');a.click('catalogue');assert.notEqual(a.nodes.module.firstChild,old);assert.equal(a.nodes.module.children.length,1);await a.nodes.logout.onclick();assert.equal(a.nodes.workspace.hidden,true);assert.equal(a.nodes.module.firstChild,undefined);});
test('Late membership reply cannot reopen a signed-out account',async()=>{const a=setup();await tick();a.auth(session('member'));const finish=a.requests.shift();a.auth(null);finish({data:{role:'admin'}});await tick();assert.equal(a.nodes.workspace.hidden,true);assert.equal(a.nodes.module.firstChild,undefined);});
test('Frame messages require matching origin and active sender; unknown routes fail closed',async()=>{const a=setup();await tick();a.auth(session('member'));a.requests.shift()({data:{role:'reader'}});await tick();a.click('scan');const frame=a.nodes.module.firstChild;const message={origin:'https://evil.test',source:frame.contentWindow,data:{type:'alcorb-section',section:'demo'}};a.events.message(message);assert.equal(a.nodes.module.firstChild,frame);a.events.message({...message,origin:'https://example.test',source:{}});assert.equal(a.nodes.module.firstChild,frame);a.events.message({...message,origin:'https://example.test',data:{type:'alcorb-section',section:'constructor'}});assert.equal(a.nodes.module.firstChild,undefined);});
test('Revoked or failed membership recheck removes loaded content',async()=>{const a=setup();await tick();a.auth(session('member'));a.requests.shift()({data:{role:'operator'}});await tick();a.click('scan');a.auth(session('member'));a.requests.shift()({error:{message:'offline'}});await tick();assert.equal(a.nodes.workspace.hidden,true);assert.equal(a.nodes.module.firstChild,undefined);});


test('Unsaved module changes keep the current section until confirmed',async()=>{const a=setup();await tick();a.auth(session('member'));a.requests.shift()({data:{role:'operator'}});await tick();a.click('settings');const frame=a.nodes.module.firstChild;a.events.message({origin:'https://example.test',source:frame.contentWindow,data:{type:'alcorb-dirty',dirty:true}});a.click('scan');assert.equal(a.nodes.module.firstChild,frame);a.events.message({origin:'https://example.test',source:frame.contentWindow,data:{type:'alcorb-dirty',dirty:false}});a.click('scan');assert.notEqual(a.nodes.module.firstChild,frame);});
