const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),test=require('node:test');
const source=fs.readFileSync('application.js','utf8');
/* Shared logistics access (8 October 2026): one shop password checked by the server, no account,
   no PIN. The shell asks SharedAccess for a session and never sees the password itself. */
const tick=()=>new Promise(resolve=>setImmediate(resolve));
function setup({hash='',refuse=null}={}){const nodes={},gate={entered:0,left:0};function node(){return {dataset:{},hidden:false,textContent:'',value:'',disabled:false,children:[],replaceChildren(){this.children=[]},append(n){this.children.push(n);n.parentNode=this},remove(){this.parentNode.children=this.parentNode.children.filter(n=>n!==this)},get firstChild(){return this.children[0]}}}const docEvents={},events={};let confirmAnswer=false;const c={URLSearchParams,confirm:()=>confirmAnswer,document:{getElementById:id=>nodes[id]??=node(),querySelectorAll:()=>[],createElement:()=>({...node(),contentWindow:{postMessage(){}}}),addEventListener:(k,f)=>docEvents[k]=f},window:{addEventListener:(k,f)=>events[k]=f},history:{replaceState(_a,_b,h){c.location.hash=h}},location:{hash,search:'',origin:'https://example.test'},SharedAccess:{enter:async()=>{gate.entered++;if(refuse)throw refuse;},leave(){gate.left++;}},supabase:{createClient(){throw Error('the shell must not create a database client')}},clearTimeout(){},setTimeout:f=>f()};for(const id of ["module","workspace","leave","identity","sectionNotice","home","entry"])c.document.getElementById(id);nodes.workspace.hidden=true;nodes.leave.hidden=true;vm.createContext(c);vm.runInContext(source,c);return {nodes,events,c,gate,confirm:v=>confirmAnswer=v,open:async()=>{nodes.openLogistics.onclick();await tick();},click:s=>docEvents.click({target:{closest:()=>({dataset:{section:s}})}})};}
test('Shell has no login, password, PIN or session code',()=>{
 const html=fs.readFileSync('application.html','utf8');
 for(const gone of ['id="login"','id="email"','password-visibility','pin-ui','Paramétrage','data-section="team"','data-section="settings"'])assert.equal(html.includes(gone),false,gone);
 for(const gone of ['signInWithPassword','getSession','onAuthStateChange','signOut','scanette_members','AlcorbAuth','pin-ui','createClient',"team:","settings:"])assert.equal(source.includes(gone),false,gone);
 assert.match(html,/toute personne qui le connaît agit pour le magasin/);
 // The password field is built by shared-access.js; the page itself holds no password, hash or value.
 assert.equal(/type="password"|value="/.test(html),false);assert.ok(html.indexOf('shared-access.js')<html.indexOf('application.js'));
});
test('No module before the logistics access is chosen',()=>{const a=setup();a.click('scan');assert.equal(a.nodes.module.firstChild,undefined);assert.equal(a.nodes.workspace.hidden,true);assert.equal(a.nodes.entry.hidden,false);});
test('Logistics access opens the workspace once the server has accepted the password',async()=>{const a=setup();await a.open();assert.equal(a.nodes.entry.hidden,true);assert.equal(a.nodes.workspace.hidden,false);assert.equal(a.nodes.leave.hidden,false);assert.match(a.nodes.identity.textContent,/partagé/);a.click('scan');assert.equal(a.nodes.module.firstChild.src,'index.html?embedded=1');});
test('A section link opens the workspace on that section after the password',async()=>{const a=setup({hash:'#receipts'});await tick();assert.equal(a.nodes.workspace.hidden,false);assert.equal(a.nodes.module.firstChild.src,'logistics-sessions.html?embedded=1&kind=receipt');});
test('Team, settings and unknown routes never open: they fall back to home',async()=>{for(const name of ['team','settings','constructor','tracking']){const a=setup();await a.open();a.click('scan');a.click(name);assert.equal(a.nodes.module.children.length,0,name);assert.equal(a.nodes.home.hidden,false);}const h=setup({hash:'#settings'});assert.equal(h.nodes.workspace.hidden,true,'an administration hash does not open anything');});
test('Navigation replaces frames; leaving clears immediately',async()=>{const a=setup();await a.open();a.click('scan');const old=a.nodes.module.firstChild;a.click('catalogue');assert.notEqual(a.nodes.module.firstChild,old);assert.equal(a.nodes.module.children.length,1);a.nodes.leave.onclick();assert.equal(a.nodes.workspace.hidden,true);assert.equal(a.nodes.module.firstChild,undefined);assert.equal(a.nodes.entry.hidden,false);});
test('Frame messages require matching origin and active sender; unknown routes fail closed',async()=>{const a=setup();await a.open();a.click('scan');const frame=a.nodes.module.firstChild;const message={origin:'https://evil.test',source:frame.contentWindow,data:{type:'alcorb-section',section:'demo'}};a.events.message(message);assert.equal(a.nodes.module.firstChild,frame);a.events.message({...message,origin:'https://example.test',source:{}});assert.equal(a.nodes.module.firstChild,frame);a.events.message({...message,origin:'https://example.test',data:{type:'alcorb-section',section:'constructor'}});assert.equal(a.nodes.module.firstChild,undefined);});
test('Unsaved module changes keep the current section until confirmed, also when leaving',async()=>{const a=setup();await a.open();a.click('receipts');const frame=a.nodes.module.firstChild;a.events.message({origin:'https://example.test',source:frame.contentWindow,data:{type:'alcorb-dirty',dirty:true}});a.click('scan');assert.equal(a.nodes.module.firstChild,frame);a.nodes.leave.onclick();assert.equal(a.nodes.workspace.hidden,false);a.events.message({origin:'https://example.test',source:frame.contentWindow,data:{type:'alcorb-dirty',dirty:false}});a.click('scan');assert.notEqual(a.nodes.module.firstChild,frame);});
test('Scan focus mode is scoped to the scanner and removed when leaving',async()=>{const a=setup();await a.open();a.click('scan');assert.equal(a.nodes.workspace.dataset.focus,'scan');a.click('catalogue');assert.equal(a.nodes.workspace.dataset.focus,'');a.click('scan');a.nodes.leave.onclick();assert.equal(a.nodes.workspace.dataset.focus,'');});
test('Inventory uses its local count screen with full-height camera space',async()=>{const a=setup();await a.open();a.click('inventory');assert.equal(a.nodes.module.firstChild.src,'inventory/index.html');assert.equal(a.nodes.workspace.dataset.focus,'inventory');a.click('receipts');assert.equal(a.nodes.workspace.dataset.focus,'');});
test('Receipt footer opens scanner with that dossier as association target',async()=>{const a=setup();await a.open();a.click('receipts');const frame=a.nodes.module.firstChild,id='11111111-1111-4111-8111-111111111111';a.events.message({origin:'https://example.test',source:frame.contentWindow,data:{type:'alcorb-section',section:'scan',receiptId:id}});assert.equal(a.nodes.module.firstChild.src,'index.html?embedded=1&receipt='+id);});
test('All operational sections are reachable: reception, scanner, inventory, preparation, departures, catalogue, returns',async()=>{const a=setup();await a.open();for(const [name,src] of Object.entries({receipts:'logistics-sessions.html?embedded=1&kind=receipt',scan:'index.html?embedded=1',inventory:'inventory/index.html',preparation:'preparation.html',departures:'store-partners.html?embedded=1',catalogue:'bellecave.html?embedded=1',returns:'returns.html?embedded=1'})){a.click(name);assert.equal(a.nodes.module.firstChild.src,src);}});
test('Retired GPS route returns home and never requests geolocation',async()=>{const a=setup();await a.open();a.click('tracking');assert.equal(a.nodes.module.children.length,0);assert.equal(a.nodes.home.hidden,false);a.click('scan');assert.equal(a.nodes.module.firstChild.allow,'camera');assert.equal(source.includes('geolocation'),false);});
test('Garage access is a plain link to the public portal, kept apart from the logistics access',()=>{const html=fs.readFileSync('application.html','utf8');assert.match(html,/<a id="openGarage" class="access-card garage-access" href="returns-portal.html">/);assert.doesNotMatch(html,/lien privé/);const a=setup();assert.equal(a.nodes.entry.hidden,false);assert.equal(a.nodes.workspace.hidden,true);assert.equal(a.nodes.openGarage?.onclick,undefined,'the shell does not intercept the garage link');const portal=fs.readFileSync('returns-portal.js','utf8');for(const fn of portal.match(/rpc\('([a-z_]+)'/g)||[])assert.match(fn,/returns_public_(garages|submit)/);assert.equal(/shared_/.test(portal),false,'the garage page never calls the logistics facade');});
test('Without a session nothing opens: refused or cancelled password keeps the entry screen',async()=>{
 const wrong=setup({refuse:Object.assign(Error('Mot de passe incorrect.'),{code:'WRONG'})});await wrong.open();
 assert.equal(wrong.gate.entered,1);assert.equal(wrong.nodes.workspace.hidden,true);assert.equal(wrong.nodes.entry.hidden,false);assert.equal(wrong.nodes.module.firstChild,undefined);assert.equal(wrong.nodes.status.textContent,'Mot de passe incorrect.');
 wrong.click('scan');assert.equal(wrong.nodes.module.firstChild,undefined);
 const cancelled=setup({hash:'#receipts',refuse:Object.assign(Error('x'),{code:'CANCELLED'})});await tick();
 assert.equal(cancelled.nodes.workspace.hidden,true);assert.equal(cancelled.nodes.module.firstChild,undefined);assert.equal(cancelled.nodes.status.textContent,'');
});
test('« Changer d’accès » ends the server session',async()=>{const a=setup();await a.open();a.nodes.leave.onclick();assert.equal(a.gate.left,1);assert.equal(a.nodes.workspace.hidden,true);});
