(()=>{'use strict';
const $=id=>document.getElementById(id),map=window.deliveryMap,shop='8770297c-cadb-4cc6-8b93-55a0f9bd154e';
let directory=[],partners=[],markers=[],epoch=0,privateStatus='Connexion requise pour les garages du magasin.',publicError=false;
const norm=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
function coordinates(c){return c&&typeof c.lat==='number'&&typeof c.lon==='number'&&Number.isFinite(c.lat)&&Number.isFinite(c.lon)&&Math.abs(c.lat)<=90&&Math.abs(c.lon)<=180?[c.lat,c.lon]:null;}
function places(){const sources=new Set(partners.map(p=>p.source_key).filter(Boolean)),out=[];for(const p of partners){const matches=directory.filter(d=>d.id===p.source_key||d.siret&&d.siret===p.source_key),source=matches.length===1?matches[0]:null,point=coordinates(p.details?.coordinates)||coordinates(source?.coordinates);if(point)out.push({name:p.name,city:p.details?.city||source?.city||'',point,store:true});}if($('publicGarages').checked)for(const p of directory){if(sources.has(p.id)||p.siret&&sources.has(p.siret))continue;const point=coordinates(p.coordinates);if(point)out.push({name:p.name,city:p.city||'',point,store:false});}return out;}
function paint(){markers.forEach(m=>m.remove());markers=[];$('garageResults').replaceChildren();const q=norm($('garageSearch').value).trim(),all=places(),filtered=all.filter(p=>norm(p.name+' '+p.city).includes(q)),located=all.filter(p=>p.store).length;
 $('garageStatus').textContent=privateStatus+' '+located+' garage(s) du magasin localisé(s), '+Math.max(0,partners.length-located)+' sans coordonnées. '+(publicError?'Annuaire public indisponible.':'Les repères orange proviennent d’OpenStreetMap ; ils ne désignent pas nécessairement vos clients. Les noms apparaissent en zoomant ou en cliquant.');
 for(const p of filtered){if(map&&map.getBounds().contains(p.point)){const title=document.createElement('strong'),popup=document.createElement('div');title.textContent=p.name;popup.textContent=p.name+' · '+p.city+' · '+(p.store?'Garage du magasin':'Annuaire public OpenStreetMap — emplacement à vérifier');const m=L.circleMarker(p.point,{radius:6,color:'#fff',weight:2,fillColor:p.store?'#8c40b0':'#c56b0a',fillOpacity:1}).addTo(map).bindTooltip(title,{permanent:map.getZoom()>=14,direction:'top',className:'garage-label'+(p.store?' store':'')}).bindPopup(popup);markers.push(m);}
 }
 if(q){for(const p of filtered.slice(0,20)){const b=document.createElement('button');b.textContent=p.name+' · '+p.city+' · '+(p.store?'Magasin':'Annuaire');b.disabled=!map;b.onclick=()=>map.setView(p.point,17);$('garageResults').append(b);}if(!filtered.length)$('garageResults').textContent='Aucun garage localisé correspondant.';}
}
$('garageSearch').oninput=paint;$('publicGarages').onchange=paint;if(map)map.on('moveend',paint);
async function enter(db,session){const ticket=++epoch;partners=[];privateStatus=session?'Chargement des fiches du magasin…':'Connexion requise pour les garages du magasin.';paint();if(!session)return;try{const loaded=[];for(let from=0;;from+=500){const r=await db.from('gestion_partners').select('id,name,source_key,details').eq('workspace_id',shop).eq('kind','client').order('id').range(from,from+499);if(ticket!==epoch)return;if(r.error)throw r.error;loaded.push(...r.data);if(r.data.length<500)break;}partners=loaded.filter(p=>!p.details?.merged_into);privateStatus='Fiches du magasin chargées.';}catch{if(ticket!==epoch)return;partners=[];privateStatus='Fiches du magasin indisponibles.';}paint();}
fetch('partners-osm-data.json').then(r=>{if(!r.ok)throw Error();return r.json();}).then(data=>{directory=(data.entries||[]).filter(p=>p.kind==='garage'&&['64','40'].includes(p.department));paint();}).catch(()=>{publicError=true;paint();});
try{const db=window.parent!==window&&window.parent.AlcorbAuth||supabase.createClient('https://pryocchvwmnuoidtitow.supabase.co','sb_publishable_AQ9cr2Z7Kr6EAravVOgB9Q_Z5Mx2yOZ');db.auth.onAuthStateChange((_e,s)=>setTimeout(()=>enter(db,s),0));db.auth.getSession().then(r=>enter(db,r.data.session)).catch(()=>{privateStatus='Connexion au magasin indisponible.';paint();});}catch{paint();}
})();
