const fs=require('node:fs'),vm=require('node:vm'),test=require('node:test'),assert=require('node:assert/strict');
const tick=()=>new Promise(r=>setImmediate(r));
function setup(readError=null,positions=[],options={}){const rendered=[];const centers=[];const map={setView(...args){centers.push(args)},invalidateSize(){}};const L={circle:()=>({addTo(){return this},remove(){}}),circleMarker:()=>{const marker={addTo(){return this},remove(){},bindPopup(){return this},bindTooltip(label,options){rendered.push({label:label.textContent,options});return this},bringToFront(){},openPopup(){}};return marker;}};const nodes={},events={},calls=[],pending=[];let success,error,cleared=0;const node=()=>({value:'Alexis',hidden:false,disabled:false,textContent:'',children:[],append(...items){this.children.push(...items)},replaceChildren(){this.children=[]},focus(){}});const document={hidden:false,getElementById:id=>nodes[id]??=node(),createElement:node,addEventListener:(e,f)=>events[e]=f};const db={rpc:async(name,args)=>{calls.push({name,args});if(name==='delivery_positions_current')return readError?{error:readError}:{data:positions};return await new Promise(resolve=>pending.push(resolve));},from:()=>({select:()=>({eq:()=>({eq:()=>({maybeSingle:async()=>({data:{role:'operator'}})})})})}),auth:{onAuthStateChange(){},getSession:async()=>({data:{session:{user:{id:'member'}}}})}};const window={deliveryMap:map,isSecureContext:true,addEventListener:(e,f)=>events[e]=f};const parentMessages=[];window.parent=options.embedded?{postMessage:m=>parentMessages.push(m)}:window;const stored=new Map(Object.entries(options.stored||{'alcorb-driver-name:8770297c-cadb-4cc6-8b93-55a0f9bd154e:member':'Alexis'}));const context={window,document,location:{origin:'https://example.test'},localStorage:{getItem:k=>stored.get(k),setItem:(k,v)=>stored.set(k,v)},L,deliveryMap:map,navigator:{geolocation:{watchPosition:(s,e)=>{success=s;error=e;return 1;},clearWatch:()=>cleared++}},supabase:{createClient:()=>db},crypto:{randomUUID:()=> 'lease-1'},Date,Promise,setTimeout,setInterval(){},console};vm.runInNewContext(fs.readFileSync('delivery-position.js','utf8'),context);return {rendered,nodes,events,centers,stored,parentMessages,window,calls,pending,document,fix:()=>success({timestamp:Date.now(),coords:{latitude:0,longitude:0,accuracy:5}}),deny:()=>error({code:1}),cleared:()=>cleared};}
test('Location never requested before explicit activation; stop during start cannot install a late GPS watch',async()=>{const a=setup();await tick();assert.equal(a.calls.filter(c=>c.name==='delivery_position_write').length,0);const start=a.nodes.startSharing.onclick();await tick();const stop=a.nodes.stopSharing.onclick();await tick();a.pending.shift()({});await tick();assert.equal(a.calls.at(-1).args.operation,'stop');a.pending.shift()({});await start;await stop;assert.match(a.nodes.sharingStatus.textContent,/arrêté/);assert.equal(a.cleared(),0);});
test('An in-flight position finishes before stop; later callbacks cannot send again',async()=>{const a=setup();await tick();const start=a.nodes.startSharing.onclick();await tick();a.pending.shift()({});await start;a.fix();await tick();const stop=a.nodes.stopSharing.onclick();a.fix();assert.equal(a.cleared(),1);a.pending.shift()({});await tick();assert.deepEqual(a.calls.filter(c=>c.name==='delivery_position_write').map(c=>c.args.operation),['begin','position','stop']);a.pending.shift()({});await stop;});
test('Hiding the page stops sharing and a refused permission also stops the lease',async()=>{for(const mode of ['hidden','deny']){const a=setup();await tick();const start=a.nodes.startSharing.onclick();await tick();a.pending.shift()({});await start;if(mode==='hidden'){a.document.hidden=true;a.events.visibilitychange();}else a.deny();await tick();assert.equal(a.calls.at(-1).args.operation,'stop');a.pending.shift()({});await tick();assert.equal(a.nodes.stopSharing.hidden,true);}});

test('Missing GPS service is explicit and never enables location sharing',async()=>{const a=setup({code:'PGRST202'});await tick();assert.equal(a.nodes.startSharing.disabled,true);assert.equal(a.nodes.startSharing.textContent,'GPS non activé');assert.match(a.nodes.sharingStatus.textContent,/service GPS n’est pas encore activé/);assert.equal(a.calls.filter(c=>c.name==='delivery_position_write').length,0);});
test('A network error is not described as an unactivated service or a missing membership',async()=>{const a=setup({message:'Network failed'});await tick();assert.equal(a.nodes.startSharing.disabled,true);assert.equal(a.nodes.startSharing.textContent,'Suivi indisponible');assert.match(a.nodes.sharingStatus.textContent,/connexion/);});

test('Two colocated drivers retain distinct permanent numbered names',async()=>{const a=setup(null,[{user_id:'one',label:'Cédric',latitude:43.5,longitude:-1.5,accuracy:5,age_seconds:0,updated_at:new Date().toISOString()},{user_id:'two',label:'Damien',latitude:43.5,longitude:-1.5,accuracy:5,age_seconds:0,updated_at:new Date().toISOString()}]);await tick();assert.deepEqual(a.rendered.map(r=>r.label),['#1 · Cédric','#2 · Damien']);assert.ok(a.rendered.every(r=>r.options.permanent));assert.notEqual(a.rendered[0].options.direction,a.rendered[1].options.direction);});

test('Driver dropdown uses stable identity, centers chosen driver and rejects expired positions',async()=>{
 const positions=[{user_id:'one',label:'Cédric',latitude:43.5,longitude:-1.5,accuracy:5,age_seconds:0,updated_at:new Date().toISOString()},{user_id:'two',label:'Damien',latitude:43.6,longitude:-1.4,accuracy:5,age_seconds:0,updated_at:new Date().toISOString()}];const a=setup(null,positions);await tick();assert.deepEqual(a.nodes.driverSelect.children.map(o=>o.value),['','one','two']);a.nodes.driverSelect.value='two';a.nodes.driverSelect.onchange();assert.deepEqual(Array.from(a.centers[0][0]),[43.6,-1.4]);assert.match(a.nodes.driverSelectionStatus.textContent,/Damien/);
 positions[1].age_seconds=100;a.events.online();await tick();assert.equal(a.nodes.driverSelect.value,'two');assert.equal(a.nodes.driverSelect.children.at(-1).disabled,true);assert.match(a.nodes.driverSelectionStatus.textContent,/plus disponible/);assert.equal(a.nodes.vehicleCount.textContent,'1 véhicule(s) · positions récentes');
});
test('Names are remembered by account without automatically starting GPS',async()=>{const a=setup();await tick();assert.equal(a.nodes.driverName.value,'Alexis');a.nodes.driverName.value='Cédric';a.nodes.driverName.onchange();assert.equal(a.stored.get('alcorb-driver-name:8770297c-cadb-4cc6-8b93-55a0f9bd154e:member'),'Cédric');assert.equal(a.calls.filter(c=>c.name==='delivery_position_write').length,0);const b=setup(null,[],{stored:{other:'Damien'}});await tick();assert.equal(b.nodes.driverName.value,'');});
test('Internal navigation pauses viewer polling while preserving the active GPS watch',async()=>{const a=setup(null,[],{embedded:true});await tick();const start=a.nodes.startSharing.onclick();await tick();a.pending.shift()({});await start;const reads=a.calls.filter(c=>c.name==='delivery_positions_current').length;
 a.events.message({origin:'https://example.test',source:a.window.parent,data:{type:'alcorb-tracking-view',visible:false}});a.events.online();await tick();assert.equal(a.calls.filter(c=>c.name==='delivery_positions_current').length,reads);assert.equal(a.cleared(),0);a.fix();await tick();assert.equal(a.calls.at(-1).args.operation,'position');a.pending.shift()({});await tick();assert.equal(a.calls.filter(c=>c.name==='delivery_positions_current').length,reads);assert.ok(a.parentMessages.some(m=>m.active===true));
 const stop=a.window.stopDeliverySharing();await tick();a.pending.shift()({});await stop;assert.equal(a.cleared(),1);assert.equal(a.parentMessages.at(-1).active,false);
});
test('Permanent lease conflicts stop GPS without retrying position writes',async()=>{const a=setup();await tick();const start=a.nodes.startSharing.onclick();await tick();a.pending.shift()({});await start;a.fix();await tick();a.pending.shift()({error:{code:'PT409'}});await tick();assert.equal(a.calls.at(-1).args.operation,'stop');a.pending.shift()({});await tick();a.fix();assert.equal(a.calls.filter(c=>c.args?.operation==='position').length,1);assert.equal(a.cleared(),1);assert.match(a.nodes.sharingStatus.textContent,/session remplacée/);});
