const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),G=require('./garage-records.js'),P=require('./partner-planning-core.js');
const tick=()=>new Promise(r=>setImmediate(r));
async function app({role='operator',rows=[],failure=null,session=true}={}){
 const nodes={},drawn=[],events={},pointers={},calls=[];let auth,hold;
 const node=()=>({value:'',checked:false,children:[],textContent:'',open:false,append(...n){this.children.push(...n)},replaceChildren(){this.children=[]},reset(){},focus(){},showModal(){this.open=true},close(){this.open=false},addEventListener(){},closest(){return null}}),$=id=>nodes[id]??=node();$('publicGarages').checked=true;
 const directory=[{id:'osm1',siret:'12345678901234',name:'Public',city:'Bayonne',kind:'garage',department:'64',coordinates:{lat:43.5,lon:-1.5}},{id:'osm2',name:'Namesake',city:'Tyrosse',kind:'garage',department:'40',coordinates:{lat:43.8,lon:-1}},{id:'osm3',name:'Bordeaux',kind:'garage',department:'33',coordinates:{lat:44.8,lon:-.6}}];
 const map={on(e,fn){events[e]=fn},getContainer:()=>({addEventListener(e,fn){pointers[e]=fn}}),mouseEventToLatLng:()=>({lat:43.5,lng:-1.5}),getCenter:()=>({lat:43.5,lng:-1.5}),getBounds:()=>({contains:()=>true}),getZoom:()=>15,setView(){}};
 const db={auth:{onAuthStateChange(fn){auth=fn},getSession:async()=>({data:{session:session?{user:{id:'u'}}:null}})},from(table){const q={select(){return q},eq(){return q},order(){return q},maybeSingle:async()=>({data:{role}}),range:async()=>({data:rows})};return q;},async rpc(name,args){calls.push(args);return failure?{error:{code:failure}}:{data:{id:args.partner_id,name:args.partner_name,kind:args.partner_kind,details:args.partner_details,source_key:args.partner_source,departures:args.partner_departures,version:args.expected_version+1}};}};
 const L={DomEvent:{stopPropagation(){}},circleMarker(point,style){const item={point,style,removed:false};drawn.push(item);return {addTo(){return this},bindTooltip(label){item.name=label.textContent;return this},bindPopup(popup){item.popup=popup;return this},on(){return this},getElement:()=>item,openPopup(){item.open=true},remove(){item.removed=true}};}};
 const w={deliveryMap:map};w.parent=w;
 vm.runInNewContext(fs.readFileSync('delivery-garages.js','utf8'),{GarageRecords:G,crypto:require('crypto').webcrypto,structuredClone,confirm:()=>true,window:w,document:{getElementById:$,createElement:node,addEventListener(){}},L,supabase:{createClient:()=>db},fetch:async()=>({ok:true,json:async()=>({entries:directory})}),setTimeout:(fn,ms)=>{if(ms===700){hold=fn;return 1;}return setTimeout(fn,ms)},clearTimeout:()=>{hold=null}});
 await tick();return {$,calls,events,pointers,hold:()=>hold?.(),live:()=>drawn.filter(x=>!x.removed),logout:async()=>{auth('SIGNED_OUT',null);await new Promise(r=>setTimeout(r,5))}};
}
const record={id:'private',name:'Private',kind:'client',version:4,source_key:'12345678901234',details:{city:'Bayonne',code:'C42'},departures:[{time:'09:30',days:[1],carrier:'Serge'}]};
test('Identity joins only by ID, includes unlocated private records in search',async()=>{const a=await app({rows:[record,{id:'x',name:'Namesake',details:{}}]});assert.deepEqual(a.live().map(x=>x.name),['Private','Namesake']);a.$('garageSearch').value='Namesake';a.$('garageSearch').oninput();assert.equal(a.$('garageResults').children.length,2);});
test('Archive is shared RPC with optimistic version and keeps original schedules/details',async()=>{const a=await app({rows:[record]});await a.live()[0].popup.children[1].children[1].onclick();assert.equal(a.calls[0].expected_version,4);assert.deepEqual(a.calls[0].partner_departures,record.departures);assert.equal(a.calls[0].partner_details.code,'C42');assert.equal(a.calls[0].partner_details.archived,true);assert.deepEqual(a.live().map(x=>x.name),['Namesake']);a.$('archivedGarages').checked=true;a.$('archivedGarages').onchange();await a.$('garageResults').children[0].children[1].children[0].onclick();assert.equal(a.calls[1].expected_version,5);assert.equal(a.calls[1].partner_details.archived,false);});
test('Public exclusion persisted by stable source and reapplied on reload',async()=>{const a=await app();await a.live()[0].popup.children[1].children[1].onclick();const r=a.calls[0];assert.equal(r.partner_source,'12345678901234');assert.equal(a.live().some(p=>p.name==='Public'),false);const b=await app({rows:[{...record,details:r.partner_details}]});assert.deepEqual(b.live().map(x=>x.name),['Namesake']);});
test('Failed archive leaves garage visible and reports concurrency conflict',async()=>{const a=await app({rows:[record],failure:'40001'});await a.live()[0].popup.children[1].children[1].onclick();assert.ok(a.live().some(p=>p.name==='Private'));assert.match(a.$('garageActionStatus').textContent,/modifiée ailleurs/);});
test('Add at chosen coordinates; empty names blocked; save closes only after success',async()=>{const a=await app();a.events.contextmenu({latlng:{lat:43.4,lng:-1.6}});assert.equal(a.$('garageDialog').open,true);await a.$('garageForm').onsubmit({preventDefault(){}});assert.equal(a.calls.length,0);a.$('garage-name').value='New garage';await a.$('garageForm').onsubmit({preventDefault(){}});assert.equal(a.calls[0].partner_details.coordinates.lat,43.4);assert.equal(a.calls[0].partner_details.coordinates.lon,-1.6);assert.equal(a.$('garageDialog').open,false);});
test('Viewer and logged-out users cannot save, logout clears private data',async()=>{for(const settings of [{role:'viewer'},{session:false}]){const a=await app(settings);assert.equal(a.$('addGarage').disabled,true);await a.live()[0].popup.children[1].children[1].onclick();assert.equal(a.calls.length,0);}const a=await app({rows:[record]});await a.logout();assert.ok(!a.live().some(p=>p.name==='Private'));});
test('Long press opens form; moving map cancels; no empty form from marker propagation',async()=>{const a=await app();const e={pointerType:'touch',clientX:10,clientY:10,target:{closest:()=>null}};a.pointers.pointerdown(e);a.pointers.pointermove({...e,clientX:40});a.hold();assert.equal(a.$('garageDialog').open,false);a.pointers.pointerdown(e);a.hold();assert.equal(a.$('garageDialog').open,true);a.$('garageCancel').onclick();a.events.contextmenu({propagatedFrom:{},latlng:{lat:1,lng:2}});assert.equal(a.$('garageDialog').open,false);});
test('Archived garage excluded from active departures, restored schedules unchanged',()=>{const archived={...record,details:G.archive(record,true)};assert.equal(P.active([archived]).length,0);assert.equal(P.slots([archived],1).length,0);assert.equal(P.slots([{...archived,details:G.archive(archived,false)}],1).length,1);});
