const test=require('node:test'),assert=require('node:assert/strict'),core=require('./delivery-tours-core.js');
const make=()=>core.create('tour','Livreur test',[{name:'ATB test',address:'Adresse test',documents:['BL1']},{name:'EMD test',address:'Autre adresse',documents:['BL2','BL3']}],'2026-09-20T10:00:00Z');
test('Livraison séquentielle, incidents explicites, reprise et fin sans double validation',()=>{const t=make();assert.throws(()=>core.transition(t,'delivered','0','','now'));core.transition(t,'start',null,'','10:00');assert.throws(()=>core.transition(t,'delivered','1','','now'));core.transition(t,'pause',null,'','10:01');assert.throws(()=>core.transition(t,'delivered','0','','now'));core.transition(t,'resume',null,'','10:02');core.transition(t,'delivered','0','','10:03');assert.equal(core.next(t).id,'1');assert.throws(()=>core.transition(t,'delivered','0','','now'));assert.throws(()=>core.transition(t,'partial','1','','now'));core.transition(t,'partial','1','BL3 : 1 pièce manquante','10:04');assert.equal(t.status,'completed');assert.equal(t.stops[0].status,'delivered');assert.equal(t.stops[1].status,'partial');assert.equal(t.events.length,5);assert.throws(()=>core.transition(t,'start',null,'','now'));});
test('Aperçu garage minimal, aucun autre nom, adresse ni BL exposé',()=>{const t=make();core.transition(t,'start',null,'','10:00');const c=core.customer(t,'1');assert.equal(c.stopsBefore,1);assert.equal(c.simulatedMinutes,10);assert.ok(!JSON.stringify(c).includes('ATB'));assert.ok(!JSON.stringify(c).includes('BL1'));assert.ok(!JSON.stringify(c).includes('Adresse'));core.transition(t,'delivered','0','','10:04');assert.equal(core.customer(t,'1').simulatedMinutes,5);core.transition(t,'pause',null,'','10:05');assert.equal(core.customer(t,'1').simulatedMinutes,null);});
test('Ordre avant départ uniquement et refus des BL en doublon',()=>{const t=make();core.move(t,'1',-1);assert.equal(t.stops[0].name,'EMD test');core.transition(t,'start',null,'','10:00');assert.throws(()=>core.move(t,'1',1));assert.throws(()=>core.create('t','D',[{documents:['BL1']},{documents:['BL1']}],'now'));assert.throws(()=>core.create('t','',[],'now'));});
test('Position GPS périmée, future ou invalide ne peut être présentée comme fraîche',()=>{const now=100000,p={latitude:43,longitude:-1,accuracy:12,at:now};assert.equal(core.freshPosition(p,now),true);assert.equal(core.freshPosition(p,now+60001),false);assert.equal(core.freshPosition({...p,at:now+1},now),false);assert.equal(core.freshPosition({...p,latitude:100},now),false);assert.equal(core.freshPosition({...p,accuracy:-1},now),false);});
const fs=require('node:fs'),vm=require('node:vm');
test('GPS stop rejects late callbacks and keeps coordinates out of saved state',()=>{let callback,cleared=0;const nodes={'#tour-gps-status':{replaceChildren(){},append(){}},'#tour-message':{}},el={innerHTML:'',querySelector:s=>nodes[s]},t=make();core.transition(t,'start',null,'','now');const state={deliveryTours:[t],deliveryTourId:t.id},docEvents={},winEvents={},c={DeliveryTours:core,navigator:{geolocation:{watchPosition(ok){callback=ok;return 7},clearWatch(id){assert.equal(id,7);cleared++}}},document:{createTextNode:x=>x,createElement:()=>({}),addEventListener:(k,f)=>docEvents[k]=f},window:{addEventListener:(k,f)=>winEvents[k]=f},setInterval:()=>1,clearInterval(){},Date};vm.createContext(c);vm.runInContext(fs.readFileSync('delivery-tours-ui.js','utf8'),c);c.DeliveryToursUI.mount(el,{store:'one',state,documents:[],clients:[],quantity:()=>[],save(){}});const act=a=>el.onclick({stopPropagation(){},target:{closest:()=>({dataset:{tour:a}})}});act('gps');callback({coords:{latitude:43,longitude:-1,accuracy:12},timestamp:Date.now()});assert.ok(!JSON.stringify(state).includes('latitude'));act('gps-stop');assert.equal(cleared,1);callback({coords:{latitude:43,longitude:-1,accuracy:12},timestamp:Date.now()});c.document.hidden=true;docEvents.visibilitychange();assert.equal(cleared,1);act('gps');winEvents.pagehide();assert.equal(cleared,2);});
test('Annulation avant départ uniquement et conservation des preuves',()=>{const t=make();core.transition(t,'cancel',null,'','now');assert.equal(t.status,'cancelled');assert.equal(t.stops.length,2);assert.throws(()=>core.transition(t,'start',null,'','now'));const active=make();core.transition(active,'start',null,'','now');assert.throws(()=>core.transition(active,'cancel',null,'','now'));});
