/* Explicit transfer of local pointage deltas. Does not change camera or scan logic. */
(function(){'use strict';const shop='8770297c-cadb-4cc6-8b93-55a0f9bd154e';let working=false;
const box=document.createElement('section');box.className='warehouse-controls';box.innerHTML='<div class="eyebrow">APRÈS LE SCAN · PRÉPARER UNE RÉCEPTION</div><p>Ta liste est prête ? Donne un nom à la livraison, puis prépare la réception. Tu pourras vérifier les quantités sur ce téléphone ou sur le PC avant de les ajouter au stock.</p><label>Fournisseur ou numéro du bon de livraison<input id="gestionLabel" maxlength="160" placeholder="Ex. APO · BL fournisseur 123"></label><div class="row"><button id="gestionTransfer">Préparer la réception</button><button id="gestionNewCycle">Commencer une autre livraison</button><a href="gestion.html">Mes réceptions →</a></div><p id="gestionTransferStatus" role="status" aria-live="polite"></p>';
document.getElementById('scanBtn').insertAdjacentElement('afterend',box);
const message=t=>document.getElementById('gestionTransferStatus').textContent=t;
const key=user=>'gestion_transfer_v1:'+user;
function state(user){const data=localStorage.getItem(key(user));return data?JSON.parse(data):{baseline:[],pending:null};}
function save(user,data){localStorage.setItem(key(user),JSON.stringify(data));}
document.getElementById('gestionTransfer').onclick=async()=>{if(working)return;if(!currentUserId||!storageReady){message('Connectez-vous avant de transmettre.');return;}working=true;const actor=currentUserId,epoch=sessionEpoch;try{const data=state(actor);if(!data.pending){const current=GestionCore.lines(snapshot());const request=GestionCore.request(current,data.baseline,document.getElementById('gestionLabel').value,crypto.randomUUID());if(!confirm(request.items.length+' référence(s), '+request.items.reduce((n,x)=>n+x.quantity,0)+' pièce(s) : créer la réception « '+request.label+' » dans Gestion ? Le stock ne sera pas modifié.'))return;data.pending=request;save(actor,data);}const p=data.pending;message('Transmission… En cas de coupure, réessayez : le même dossier sera utilisé.');await authenticatedFetch('/rest/v1/rpc/gestion_submit_receipt',{method:'POST',body:JSON.stringify({receipt_id:p.id,shop_id:shop,receipt_label:p.label,items:p.items})},epoch);if(actor!==currentUserId||epoch!==sessionEpoch)return;data.baseline=p.current;data.lastReceipt=p.id;data.pending=null;save(actor,data);message('Réception '+p.label+' préparée. Ouvre « Mes réceptions » pour vérifier et enregistrer les pièces reçues. Les prochains scans prépareront une liste supplémentaire.');}catch(error){if(actor===currentUserId&&epoch===sessionEpoch)message('Transmission non confirmée : '+error.message+' Si une tentative a été enregistrée, le prochain essai réutilisera son identifiant.');}finally{working=false;}};
document.getElementById('gestionNewCycle').onclick=()=>{if(working||!currentUserId)return;try{const data=state(currentUserId);if(data.pending)throw Error('Terminez la transmission en attente avant de changer de cycle.');if(GestionCore.lines(snapshot()).length)throw Error('Le pointage doit être vide. Exportez-le si nécessaire puis videz-le avec les commandes de Pointage avant de démarrer un nouveau cycle.');save(currentUserId,{baseline:[],pending:null});message('Nouveau cycle prêt. Les prochains scans prépareront une nouvelle réception.');}catch(error){message(error.message);}};
let observedUser=currentUserId;supaClient.auth.onAuthStateChange((_event,session)=>{const next=session?.user.id||null;if(next!==observedUser){observedUser=next;document.getElementById('gestionLabel').value='';message('');}});
})();
