-- Internal delivery rounds: DRY RUN of internal-tours.sql — writes nothing.
-- Generated by scripts/build-internal-tours-sql.cjs from internal-tours-data.json — do not edit by hand.
-- Source: Liste de référence saisie par Alexis le 09/10/2026. No coordinate, hour or record comes from the Internet.
-- Run by hand as postgres in the Supabase SQL Editor. Not applied by the application.
-- ONE statement, with named dollar-quote tags and no transaction keyword of its own: it runs as a
-- whole or not at all, and survives tools that alter doubled dollar signs.
--
-- Does everything internal-tours.sql does, then stops with an error whose message is the report:
-- the database rolls the whole statement back, so nothing is written. Use it to try the script in
-- the editor before the real run. An error « DRY RUN OK » is the expected, successful outcome.
--
-- What it does, for the Bellecave shop only:
--   * a garage that already has a record keeps its name, hours and carriers: the round is ADDED to
--     details.tours, the listed spelling variants are added to its aliases, and for Charlie his two
--     fixed departures (10:00 and 15:00, Monday to Friday) are added beside the existing ones;
--   * a garage without record gets a new one, with what Alexis wrote and nothing else;
--   * Damian, Maxime and Cédric get no hour at all; Ludovic gets no garage (reinforcement).
--   * garages whose match with an existing record is not certain are PENDING: neither created nor
--     attached, listed by internal-tours.check.sql for a decision (none at present).
-- Strict: stops without changing anything when an expected record is missing or not unique, or when
-- a record with the same name already exists for a garage that should be new.
-- Atomic: a single statement; any error undoes everything it did.
-- Idempotent: running it again changes nothing. Reversible: internal-tours.rollback.sql.
do $repclick_run$
declare shop constant uuid:='8770297c-cadb-4cc6-8b93-55a0f9bd154e'; dry_run constant boolean:=true;
 ref constant jsonb:=$repclick_data$[
 {
  "tour": "damian",
  "name": "JM Hirigoyen",
  "aliases": [],
  "details": {
   "city": "Arcangues",
   "address": "chemin du Mondarrain",
   "notes": "Garage à domicile.",
   "source": "Liste de référence saisie par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": []
 },
 {
  "tour": "damian",
  "name": "Carrosserie Biarrotte",
  "aliases": [],
  "details": {
   "city": "Biarritz",
   "notes": "Quartier de l’Allégresse.",
   "source": "Liste de référence saisie par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": []
 },
 {
  "tour": "damian",
  "name": "Garage de l’Allégresse",
  "aliases": [
   "Garage de la Négresse"
  ],
  "details": {
   "city": "Biarritz",
   "notes": "Anciennement Garage de la Négresse.",
   "source": "Liste de référence saisie par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": []
 },
 {
  "tour": "damian",
  "name": "Garage Modena",
  "aliases": [],
  "details": {
   "city": "Biarritz",
   "notes": "",
   "source": "Liste de référence saisie par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": []
 },
 {
  "tour": "damian",
  "name": "Ville de Biarritz",
  "aliases": [],
  "details": {
   "notes": "",
   "source": "Liste de référence saisie par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": []
 },
 {
  "tour": "damian",
  "name": "Garage l’Avenue",
  "aliases": [],
  "details": {
   "city": "Biarritz",
   "notes": "",
   "source": "Liste de référence saisie par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": []
 },
 {
  "tour": "damian",
  "name": "Crosa (Biarritz)",
  "aliases": [],
  "details": {
   "city": "Biarritz",
   "notes": "",
   "source": "Liste de référence saisie par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": []
 },
 {
  "tour": "damian",
  "existing": "First Stop Biarritz Pneus",
  "aliases": [],
  "fill": {},
  "slots": []
 },
 {
  "tour": "damian",
  "name": "Erviti Porsche",
  "aliases": [],
  "details": {
   "city": "Anglet",
   "notes": "",
   "source": "Liste de référence saisie par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": []
 },
 {
  "tour": "damian",
  "name": "Carro Vans",
  "aliases": [
   "Car Vans"
  ],
  "details": {
   "city": "Bidart",
   "notes": "",
   "source": "Liste de référence saisie par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": []
 },
 {
  "tour": "damian",
  "name": "Classic Vans",
  "aliases": [],
  "details": {
   "city": "Arbonne",
   "notes": "",
   "source": "Liste de référence saisie par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": []
 },
 {
  "tour": "damian",
  "name": "Dea",
  "aliases": [],
  "details": {
   "city": "Anglet",
   "notes": "",
   "source": "Liste de référence saisie par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": []
 },
 {
  "tour": "damian",
  "name": "Ville d’Anglet",
  "aliases": [],
  "details": {
   "notes": "",
   "source": "Liste de référence saisie par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": []
 },
 {
  "tour": "damian",
  "name": "MC Garage",
  "aliases": [],
  "details": {
   "notes": "",
   "source": "Liste de référence saisie par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": []
 },
 {
  "tour": "damian",
  "name": "Carrosserie Poau",
  "aliases": [],
  "details": {
   "notes": "Maignon.",
   "source": "Liste de référence saisie par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": []
 },
 {
  "tour": "damian",
  "name": "Jo Iribarren",
  "source_key": "tour-jo-iribarren-20261009",
  "distinct_from": "IRIBARREN PATRICK",
  "aliases": [
   "Irribarren",
   "Garage Jo Iribarren"
  ],
  "details": {
   "city": "Anglet",
   "address": "48 avenue de Cambo, Quartier Sutar, 64600 Anglet",
   "phones": [
    "05 59 42 37 67",
    "05 59 42 30 56"
   ],
   "hours": "Lundi à jeudi : 08h00–12h00 / 14h00–18h00 ; vendredi : 08h00–12h00 / 14h00–17h00.",
   "activities": "Réparation toutes marques, self-garage, contrôle anti-pollution, carrosserie, peinture, dépannage et remorquage, agrément assurances.",
   "source": "Informations fournies et confirmées par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": []
 },
 {
  "tour": "damian",
  "name": "Makila",
  "aliases": [],
  "details": {
   "network": "Toyota",
   "notes": "",
   "source": "Liste de référence saisie par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": []
 },
 {
  "tour": "damian",
  "name": "Land Rover / Auto Real",
  "aliases": [
   "Auto Real",
   "Land Rover"
  ],
  "details": {
   "notes": "",
   "source": "Liste de référence saisie par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": []
 },
 {
  "tour": "damian",
  "name": "Grimso",
  "aliases": [],
  "details": {
   "network": "Ford",
   "notes": "",
   "source": "Liste de référence saisie par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": []
 },
 {
  "tour": "damian",
  "name": "SB Auto",
  "aliases": [],
  "details": {
   "city": "Bassussary",
   "notes": "",
   "source": "Liste de référence saisie par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": []
 },
 {
  "tour": "damian",
  "name": "Peugeot",
  "aliases": [],
  "details": {
   "notes": "",
   "source": "Liste de référence saisie par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": []
 },
 {
  "tour": "damian",
  "name": "Honda",
  "aliases": [],
  "details": {
   "notes": "",
   "source": "Liste de référence saisie par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": []
 },
 {
  "tour": "damian",
  "name": "Car Bayonne",
  "aliases": [],
  "details": {
   "notes": "",
   "source": "Liste de référence saisie par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": []
 },
 {
  "tour": "damian",
  "name": "Belle Marion (Bayonne)",
  "aliases": [],
  "details": {
   "city": "Bayonne",
   "notes": "",
   "source": "Liste de référence saisie par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": []
 },
 {
  "tour": "damian",
  "name": "Maeva Car",
  "aliases": [],
  "details": {
   "notes": "",
   "source": "Liste de référence saisie par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": []
 },
 {
  "tour": "damian",
  "existing": "FEU VERT BIDART",
  "aliases": [],
  "fill": {},
  "slots": []
 },
 {
  "tour": "damian",
  "name": "Carrosserie de la Gare",
  "aliases": [],
  "details": {
   "notes": "",
   "source": "Liste de référence saisie par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": []
 },
 {
  "tour": "damian",
  "name": "SOS D Bosses",
  "aliases": [],
  "details": {
   "notes": "",
   "source": "Liste de référence saisie par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": []
 },
 {
  "tour": "damian",
  "name": "Etcheparre",
  "aliases": [],
  "details": {
   "notes": "",
   "source": "Liste de référence saisie par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": []
 },
 {
  "tour": "damian",
  "name": "Ocean Dépannage",
  "aliases": [],
  "details": {
   "notes": "",
   "source": "Liste de référence saisie par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": []
 },
 {
  "tour": "damian",
  "name": "Slavi",
  "aliases": [],
  "details": {
   "notes": "",
   "source": "Liste de référence saisie par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": []
 },
 {
  "tour": "maxime",
  "name": "Labachot (Anglet)",
  "aliases": [],
  "details": {
   "city": "Anglet",
   "notes": "",
   "source": "Liste de référence saisie par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": []
 },
 {
  "tour": "maxime",
  "name": "Norauto Pontot",
  "aliases": [
   "Nauroto Pontot"
  ],
  "details": {
   "notes": "",
   "source": "Liste de référence saisie par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": []
 },
 {
  "tour": "maxime",
  "name": "Garage du Centre",
  "aliases": [],
  "details": {
   "notes": "",
   "source": "Liste de référence saisie par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": []
 },
 {
  "tour": "maxime",
  "name": "Carrosserie Barcelona",
  "aliases": [],
  "details": {
   "notes": "",
   "source": "Liste de référence saisie par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": []
 },
 {
  "tour": "maxime",
  "name": "Carrosserie Moderne",
  "aliases": [],
  "details": {
   "notes": "",
   "source": "Liste de référence saisie par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": []
 },
 {
  "tour": "maxime",
  "name": "Feu Vert (Anglet)",
  "aliases": [],
  "details": {
   "city": "Anglet",
   "notes": "",
   "source": "Liste de référence saisie par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": []
 },
 {
  "tour": "maxime",
  "name": "Norauto France",
  "aliases": [
   "Nauroto France"
  ],
  "details": {
   "notes": "",
   "source": "Liste de référence saisie par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": []
 },
 {
  "tour": "maxime",
  "name": "Point S",
  "aliases": [],
  "details": {
   "address": "allée Paulmy",
   "notes": "",
   "source": "Liste de référence saisie par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": []
 },
 {
  "tour": "maxime",
  "name": "Pneu Service Auto",
  "aliases": [],
  "details": {
   "notes": "",
   "source": "Liste de référence saisie par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": []
 },
 {
  "tour": "maxime",
  "name": "Ondres Auto",
  "aliases": [],
  "details": {
   "notes": "",
   "source": "Liste de référence saisie par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": []
 },
 {
  "tour": "maxime",
  "name": "Pneu du BAB",
  "aliases": [],
  "details": {
   "notes": "",
   "source": "Liste de référence saisie par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": []
 },
 {
  "tour": "maxime",
  "name": "Concept Car",
  "aliases": [],
  "details": {
   "notes": "",
   "source": "Liste de référence saisie par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": []
 },
 {
  "tour": "maxime",
  "name": "Atelier Carrosserie Shark",
  "aliases": [],
  "details": {
   "notes": "",
   "source": "Liste de référence saisie par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": []
 },
 {
  "tour": "maxime",
  "name": "Euromaster (allées Marines)",
  "aliases": [],
  "details": {
   "address": "allées Marines",
   "notes": "",
   "source": "Liste de référence saisie par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": []
 },
 {
  "tour": "maxime",
  "name": "Hirigoyen",
  "aliases": [],
  "details": {
   "notes": "",
   "source": "Liste de référence saisie par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": []
 },
 {
  "tour": "maxime",
  "name": "JC Auto",
  "aliases": [],
  "details": {
   "notes": "",
   "source": "Liste de référence saisie par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": []
 },
 {
  "tour": "maxime",
  "name": "Auto Sélection",
  "aliases": [],
  "details": {
   "notes": "",
   "source": "Liste de référence saisie par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": []
 },
 {
  "tour": "maxime",
  "name": "Castagnet",
  "aliases": [],
  "details": {
   "notes": "Total, allées Marines.",
   "source": "Liste de référence saisie par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": []
 },
 {
  "tour": "maxime",
  "name": "Fidalgo",
  "aliases": [],
  "details": {
   "notes": "",
   "source": "Liste de référence saisie par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": []
 },
 {
  "tour": "maxime",
  "name": "Belle Marion (Anglet)",
  "aliases": [],
  "details": {
   "city": "Anglet",
   "notes": "",
   "source": "Liste de référence saisie par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": []
 },
 {
  "tour": "maxime",
  "name": "Anglet Auto Service",
  "aliases": [],
  "details": {
   "notes": "",
   "source": "Liste de référence saisie par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": []
 },
 {
  "tour": "maxime",
  "name": "Ferdinand Aviation",
  "aliases": [],
  "details": {
   "notes": "Particulier.",
   "source": "Liste de référence saisie par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": []
 },
 {
  "tour": "maxime",
  "name": "Cossec",
  "aliases": [],
  "details": {
   "notes": "",
   "source": "Liste de référence saisie par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": []
 },
 {
  "tour": "maxime",
  "name": "Service Auto 64",
  "aliases": [],
  "details": {
   "notes": "",
   "source": "Liste de référence saisie par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": []
 },
 {
  "tour": "maxime",
  "name": "Communauté de Bayonne",
  "aliases": [],
  "details": {
   "notes": "",
   "source": "Liste de référence saisie par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": []
 },
 {
  "tour": "maxime",
  "name": "Urrusty",
  "aliases": [],
  "details": {
   "notes": "",
   "source": "Liste de référence saisie par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": []
 },
 {
  "tour": "maxime",
  "name": "Dayde",
  "aliases": [],
  "details": {
   "notes": "",
   "source": "Liste de référence saisie par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": []
 },
 {
  "tour": "maxime",
  "name": "Mendi",
  "aliases": [],
  "details": {
   "notes": "",
   "source": "Liste de référence saisie par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": []
 },
 {
  "tour": "charlie",
  "name": "Lamerain Renault",
  "aliases": [],
  "details": {
   "notes": "",
   "source": "Liste de référence saisie par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": [
   {
    "mode": "internal",
    "carrier": "Charlie",
    "time": "10:00",
    "cutoff": "",
    "sector": "Saint-Jean-de-Luz / Urrugne / Ciboure / Ascain / Saint-Pée-sur-Nivelle",
    "place": "",
    "notes": "",
    "days": [
     1,
     2,
     3,
     4,
     5
    ]
   },
   {
    "mode": "internal",
    "carrier": "Charlie",
    "time": "15:00",
    "cutoff": "",
    "sector": "Saint-Jean-de-Luz / Urrugne / Ciboure / Ascain / Saint-Pée-sur-Nivelle",
    "place": "",
    "notes": "",
    "days": [
     1,
     2,
     3,
     4,
     5
    ]
   }
  ]
 },
 {
  "tour": "charlie",
  "name": "Cigarroa",
  "aliases": [],
  "details": {
   "notes": "",
   "source": "Liste de référence saisie par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": [
   {
    "mode": "internal",
    "carrier": "Charlie",
    "time": "10:00",
    "cutoff": "",
    "sector": "Saint-Jean-de-Luz / Urrugne / Ciboure / Ascain / Saint-Pée-sur-Nivelle",
    "place": "",
    "notes": "",
    "days": [
     1,
     2,
     3,
     4,
     5
    ]
   },
   {
    "mode": "internal",
    "carrier": "Charlie",
    "time": "15:00",
    "cutoff": "",
    "sector": "Saint-Jean-de-Luz / Urrugne / Ciboure / Ascain / Saint-Pée-sur-Nivelle",
    "place": "",
    "notes": "",
    "days": [
     1,
     2,
     3,
     4,
     5
    ]
   }
  ]
 },
 {
  "tour": "charlie",
  "existing": "CN AUTO",
  "aliases": [],
  "fill": {},
  "slots": [
   {
    "mode": "internal",
    "carrier": "Charlie",
    "time": "10:00",
    "cutoff": "",
    "sector": "Saint-Jean-de-Luz / Urrugne / Ciboure / Ascain / Saint-Pée-sur-Nivelle",
    "place": "",
    "notes": "",
    "days": [
     1,
     2,
     3,
     4,
     5
    ]
   },
   {
    "mode": "internal",
    "carrier": "Charlie",
    "time": "15:00",
    "cutoff": "",
    "sector": "Saint-Jean-de-Luz / Urrugne / Ciboure / Ascain / Saint-Pée-sur-Nivelle",
    "place": "",
    "notes": "",
    "days": [
     1,
     2,
     3,
     4,
     5
    ]
   }
  ]
 },
 {
  "tour": "charlie",
  "existing": "First Stop Laboudigue Saint-Jean-de-Luz",
  "aliases": [],
  "fill": {},
  "slots": [
   {
    "mode": "internal",
    "carrier": "Charlie",
    "time": "10:00",
    "cutoff": "",
    "sector": "Saint-Jean-de-Luz / Urrugne / Ciboure / Ascain / Saint-Pée-sur-Nivelle",
    "place": "",
    "notes": "",
    "days": [
     1,
     2,
     3,
     4,
     5
    ]
   },
   {
    "mode": "internal",
    "carrier": "Charlie",
    "time": "15:00",
    "cutoff": "",
    "sector": "Saint-Jean-de-Luz / Urrugne / Ciboure / Ascain / Saint-Pée-sur-Nivelle",
    "place": "",
    "notes": "",
    "days": [
     1,
     2,
     3,
     4,
     5
    ]
   }
  ]
 },
 {
  "tour": "charlie",
  "existing": "LECLERC ST JEAN DE LUZ",
  "aliases": [
   "Leclerc Auto"
  ],
  "fill": {},
  "slots": [
   {
    "mode": "internal",
    "carrier": "Charlie",
    "time": "10:00",
    "cutoff": "",
    "sector": "Saint-Jean-de-Luz / Urrugne / Ciboure / Ascain / Saint-Pée-sur-Nivelle",
    "place": "",
    "notes": "",
    "days": [
     1,
     2,
     3,
     4,
     5
    ]
   },
   {
    "mode": "internal",
    "carrier": "Charlie",
    "time": "15:00",
    "cutoff": "",
    "sector": "Saint-Jean-de-Luz / Urrugne / Ciboure / Ascain / Saint-Pée-sur-Nivelle",
    "place": "",
    "notes": "",
    "days": [
     1,
     2,
     3,
     4,
     5
    ]
   }
  ]
 },
 {
  "tour": "charlie",
  "existing": "AUTO SPORT",
  "aliases": [
   "Autosport"
  ],
  "fill": {},
  "slots": [
   {
    "mode": "internal",
    "carrier": "Charlie",
    "time": "10:00",
    "cutoff": "",
    "sector": "Saint-Jean-de-Luz / Urrugne / Ciboure / Ascain / Saint-Pée-sur-Nivelle",
    "place": "",
    "notes": "",
    "days": [
     1,
     2,
     3,
     4,
     5
    ]
   },
   {
    "mode": "internal",
    "carrier": "Charlie",
    "time": "15:00",
    "cutoff": "",
    "sector": "Saint-Jean-de-Luz / Urrugne / Ciboure / Ascain / Saint-Pée-sur-Nivelle",
    "place": "",
    "notes": "",
    "days": [
     1,
     2,
     3,
     4,
     5
    ]
   }
  ]
 },
 {
  "tour": "charlie",
  "name": "Auto 64",
  "aliases": [],
  "details": {
   "notes": "",
   "source": "Liste de référence saisie par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": [
   {
    "mode": "internal",
    "carrier": "Charlie",
    "time": "10:00",
    "cutoff": "",
    "sector": "Saint-Jean-de-Luz / Urrugne / Ciboure / Ascain / Saint-Pée-sur-Nivelle",
    "place": "",
    "notes": "",
    "days": [
     1,
     2,
     3,
     4,
     5
    ]
   },
   {
    "mode": "internal",
    "carrier": "Charlie",
    "time": "15:00",
    "cutoff": "",
    "sector": "Saint-Jean-de-Luz / Urrugne / Ciboure / Ascain / Saint-Pée-sur-Nivelle",
    "place": "",
    "notes": "",
    "days": [
     1,
     2,
     3,
     4,
     5
    ]
   }
  ]
 },
 {
  "tour": "charlie",
  "existing": "MARINELA",
  "aliases": [],
  "fill": {},
  "slots": [
   {
    "mode": "internal",
    "carrier": "Charlie",
    "time": "10:00",
    "cutoff": "",
    "sector": "Saint-Jean-de-Luz / Urrugne / Ciboure / Ascain / Saint-Pée-sur-Nivelle",
    "place": "",
    "notes": "",
    "days": [
     1,
     2,
     3,
     4,
     5
    ]
   },
   {
    "mode": "internal",
    "carrier": "Charlie",
    "time": "15:00",
    "cutoff": "",
    "sector": "Saint-Jean-de-Luz / Urrugne / Ciboure / Ascain / Saint-Pée-sur-Nivelle",
    "place": "",
    "notes": "",
    "days": [
     1,
     2,
     3,
     4,
     5
    ]
   }
  ]
 },
 {
  "tour": "charlie",
  "existing": "DALLARD ST JEAN DE LUZ",
  "aliases": [],
  "fill": {},
  "slots": [
   {
    "mode": "internal",
    "carrier": "Charlie",
    "time": "10:00",
    "cutoff": "",
    "sector": "Saint-Jean-de-Luz / Urrugne / Ciboure / Ascain / Saint-Pée-sur-Nivelle",
    "place": "",
    "notes": "",
    "days": [
     1,
     2,
     3,
     4,
     5
    ]
   },
   {
    "mode": "internal",
    "carrier": "Charlie",
    "time": "15:00",
    "cutoff": "",
    "sector": "Saint-Jean-de-Luz / Urrugne / Ciboure / Ascain / Saint-Pée-sur-Nivelle",
    "place": "",
    "notes": "",
    "days": [
     1,
     2,
     3,
     4,
     5
    ]
   }
  ]
 },
 {
  "tour": "charlie",
  "name": "Huchet",
  "aliases": [],
  "details": {
   "notes": "",
   "source": "Liste de référence saisie par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": [
   {
    "mode": "internal",
    "carrier": "Charlie",
    "time": "10:00",
    "cutoff": "",
    "sector": "Saint-Jean-de-Luz / Urrugne / Ciboure / Ascain / Saint-Pée-sur-Nivelle",
    "place": "",
    "notes": "",
    "days": [
     1,
     2,
     3,
     4,
     5
    ]
   },
   {
    "mode": "internal",
    "carrier": "Charlie",
    "time": "15:00",
    "cutoff": "",
    "sector": "Saint-Jean-de-Luz / Urrugne / Ciboure / Ascain / Saint-Pée-sur-Nivelle",
    "place": "",
    "notes": "",
    "days": [
     1,
     2,
     3,
     4,
     5
    ]
   }
  ]
 },
 {
  "tour": "charlie",
  "existing": "JS AUTO",
  "aliases": [],
  "fill": {},
  "slots": [
   {
    "mode": "internal",
    "carrier": "Charlie",
    "time": "10:00",
    "cutoff": "",
    "sector": "Saint-Jean-de-Luz / Urrugne / Ciboure / Ascain / Saint-Pée-sur-Nivelle",
    "place": "",
    "notes": "",
    "days": [
     1,
     2,
     3,
     4,
     5
    ]
   },
   {
    "mode": "internal",
    "carrier": "Charlie",
    "time": "15:00",
    "cutoff": "",
    "sector": "Saint-Jean-de-Luz / Urrugne / Ciboure / Ascain / Saint-Pée-sur-Nivelle",
    "place": "",
    "notes": "",
    "days": [
     1,
     2,
     3,
     4,
     5
    ]
   }
  ]
 },
 {
  "tour": "charlie",
  "name": "Top Auto",
  "aliases": [],
  "details": {
   "notes": "",
   "source": "Liste de référence saisie par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": [
   {
    "mode": "internal",
    "carrier": "Charlie",
    "time": "10:00",
    "cutoff": "",
    "sector": "Saint-Jean-de-Luz / Urrugne / Ciboure / Ascain / Saint-Pée-sur-Nivelle",
    "place": "",
    "notes": "",
    "days": [
     1,
     2,
     3,
     4,
     5
    ]
   },
   {
    "mode": "internal",
    "carrier": "Charlie",
    "time": "15:00",
    "cutoff": "",
    "sector": "Saint-Jean-de-Luz / Urrugne / Ciboure / Ascain / Saint-Pée-sur-Nivelle",
    "place": "",
    "notes": "",
    "days": [
     1,
     2,
     3,
     4,
     5
    ]
   }
  ]
 },
 {
  "tour": "charlie",
  "name": "PBA",
  "aliases": [],
  "details": {
   "notes": "",
   "source": "Liste de référence saisie par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": [
   {
    "mode": "internal",
    "carrier": "Charlie",
    "time": "10:00",
    "cutoff": "",
    "sector": "Saint-Jean-de-Luz / Urrugne / Ciboure / Ascain / Saint-Pée-sur-Nivelle",
    "place": "",
    "notes": "",
    "days": [
     1,
     2,
     3,
     4,
     5
    ]
   },
   {
    "mode": "internal",
    "carrier": "Charlie",
    "time": "15:00",
    "cutoff": "",
    "sector": "Saint-Jean-de-Luz / Urrugne / Ciboure / Ascain / Saint-Pée-sur-Nivelle",
    "place": "",
    "notes": "",
    "days": [
     1,
     2,
     3,
     4,
     5
    ]
   }
  ]
 },
 {
  "tour": "charlie",
  "name": "Antao",
  "aliases": [],
  "details": {
   "notes": "",
   "source": "Liste de référence saisie par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": [
   {
    "mode": "internal",
    "carrier": "Charlie",
    "time": "10:00",
    "cutoff": "",
    "sector": "Saint-Jean-de-Luz / Urrugne / Ciboure / Ascain / Saint-Pée-sur-Nivelle",
    "place": "",
    "notes": "",
    "days": [
     1,
     2,
     3,
     4,
     5
    ]
   },
   {
    "mode": "internal",
    "carrier": "Charlie",
    "time": "15:00",
    "cutoff": "",
    "sector": "Saint-Jean-de-Luz / Urrugne / Ciboure / Ascain / Saint-Pée-sur-Nivelle",
    "place": "",
    "notes": "",
    "days": [
     1,
     2,
     3,
     4,
     5
    ]
   }
  ]
 },
 {
  "tour": "charlie",
  "name": "Darboure Pampi",
  "aliases": [],
  "details": {
   "notes": "",
   "source": "Liste de référence saisie par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": [
   {
    "mode": "internal",
    "carrier": "Charlie",
    "time": "10:00",
    "cutoff": "",
    "sector": "Saint-Jean-de-Luz / Urrugne / Ciboure / Ascain / Saint-Pée-sur-Nivelle",
    "place": "",
    "notes": "",
    "days": [
     1,
     2,
     3,
     4,
     5
    ]
   },
   {
    "mode": "internal",
    "carrier": "Charlie",
    "time": "15:00",
    "cutoff": "",
    "sector": "Saint-Jean-de-Luz / Urrugne / Ciboure / Ascain / Saint-Pée-sur-Nivelle",
    "place": "",
    "notes": "",
    "days": [
     1,
     2,
     3,
     4,
     5
    ]
   }
  ]
 },
 {
  "tour": "charlie",
  "existing": "HERRIKOA",
  "aliases": [],
  "fill": {},
  "slots": [
   {
    "mode": "internal",
    "carrier": "Charlie",
    "time": "10:00",
    "cutoff": "",
    "sector": "Saint-Jean-de-Luz / Urrugne / Ciboure / Ascain / Saint-Pée-sur-Nivelle",
    "place": "",
    "notes": "",
    "days": [
     1,
     2,
     3,
     4,
     5
    ]
   },
   {
    "mode": "internal",
    "carrier": "Charlie",
    "time": "15:00",
    "cutoff": "",
    "sector": "Saint-Jean-de-Luz / Urrugne / Ciboure / Ascain / Saint-Pée-sur-Nivelle",
    "place": "",
    "notes": "",
    "days": [
     1,
     2,
     3,
     4,
     5
    ]
   }
  ]
 },
 {
  "tour": "charlie",
  "name": "Darboure Famille",
  "aliases": [],
  "details": {
   "notes": "Particulier.",
   "source": "Liste de référence saisie par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": [
   {
    "mode": "internal",
    "carrier": "Charlie",
    "time": "10:00",
    "cutoff": "",
    "sector": "Saint-Jean-de-Luz / Urrugne / Ciboure / Ascain / Saint-Pée-sur-Nivelle",
    "place": "",
    "notes": "",
    "days": [
     1,
     2,
     3,
     4,
     5
    ]
   },
   {
    "mode": "internal",
    "carrier": "Charlie",
    "time": "15:00",
    "cutoff": "",
    "sector": "Saint-Jean-de-Luz / Urrugne / Ciboure / Ascain / Saint-Pée-sur-Nivelle",
    "place": "",
    "notes": "",
    "days": [
     1,
     2,
     3,
     4,
     5
    ]
   }
  ]
 },
 {
  "tour": "charlie",
  "name": "Endarra",
  "aliases": [],
  "details": {
   "notes": "",
   "source": "Liste de référence saisie par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": [
   {
    "mode": "internal",
    "carrier": "Charlie",
    "time": "10:00",
    "cutoff": "",
    "sector": "Saint-Jean-de-Luz / Urrugne / Ciboure / Ascain / Saint-Pée-sur-Nivelle",
    "place": "",
    "notes": "",
    "days": [
     1,
     2,
     3,
     4,
     5
    ]
   },
   {
    "mode": "internal",
    "carrier": "Charlie",
    "time": "15:00",
    "cutoff": "",
    "sector": "Saint-Jean-de-Luz / Urrugne / Ciboure / Ascain / Saint-Pée-sur-Nivelle",
    "place": "",
    "notes": "",
    "days": [
     1,
     2,
     3,
     4,
     5
    ]
   }
  ]
 },
 {
  "tour": "charlie",
  "name": "Pare-Brise 64",
  "aliases": [],
  "details": {
   "notes": "",
   "source": "Liste de référence saisie par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": [
   {
    "mode": "internal",
    "carrier": "Charlie",
    "time": "10:00",
    "cutoff": "",
    "sector": "Saint-Jean-de-Luz / Urrugne / Ciboure / Ascain / Saint-Pée-sur-Nivelle",
    "place": "",
    "notes": "",
    "days": [
     1,
     2,
     3,
     4,
     5
    ]
   },
   {
    "mode": "internal",
    "carrier": "Charlie",
    "time": "15:00",
    "cutoff": "",
    "sector": "Saint-Jean-de-Luz / Urrugne / Ciboure / Ascain / Saint-Pée-sur-Nivelle",
    "place": "",
    "notes": "",
    "days": [
     1,
     2,
     3,
     4,
     5
    ]
   }
  ]
 },
 {
  "tour": "cedric",
  "name": "Adrien",
  "aliases": [],
  "details": {
   "notes": "",
   "source": "Liste de référence saisie par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": []
 },
 {
  "tour": "cedric",
  "name": "Charli’Auto",
  "aliases": [],
  "details": {
   "notes": "",
   "source": "Liste de référence saisie par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": []
 },
 {
  "tour": "cedric",
  "name": "Hôpital de Bayonne",
  "aliases": [],
  "details": {
   "notes": "",
   "source": "Liste de référence saisie par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": []
 },
 {
  "tour": "cedric",
  "name": "Bay Utilitaire",
  "aliases": [],
  "details": {
   "notes": "",
   "source": "Liste de référence saisie par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": []
 },
 {
  "tour": "cedric",
  "name": "Carrosserie Grand Basque",
  "aliases": [],
  "details": {
   "notes": "",
   "source": "Liste de référence saisie par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": []
 },
 {
  "tour": "cedric",
  "name": "Garage des 3 Vallées",
  "aliases": [],
  "details": {
   "notes": "",
   "source": "Liste de référence saisie par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": []
 },
 {
  "tour": "cedric",
  "existing": "AUGARAY (ROADY)",
  "unique_like": "roady",
  "aliases": [
   "Roady Bayonne",
   "Centre auto Roady Bayonne"
  ],
  "fill": {
   "city": "Bayonne",
   "address": "12 allée de Biarnes, 64100 Bayonne",
   "phone": "05 18 23 07 86",
   "hours": "Lundi à vendredi : 09h00–12h00 / 14h00–19h00 ; samedi : 09h00–12h00 / 14h00–18h00 ; dimanche : fermé."
  },
  "slots": []
 },
 {
  "tour": "cedric",
  "name": "Iveco",
  "aliases": [
   "Yveco"
  ],
  "details": {
   "notes": "",
   "source": "Liste de référence saisie par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": []
 },
 {
  "tour": "cedric",
  "name": "Barthes",
  "aliases": [],
  "details": {
   "notes": "",
   "source": "Liste de référence saisie par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": []
 },
 {
  "tour": "cedric",
  "name": "Dulamon",
  "aliases": [],
  "details": {
   "notes": "",
   "source": "Liste de référence saisie par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": []
 },
 {
  "tour": "cedric",
  "name": "Feu Vert (Tarnos)",
  "aliases": [],
  "details": {
   "city": "Tarnos",
   "notes": "",
   "source": "Liste de référence saisie par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": []
 },
 {
  "tour": "cedric",
  "name": "Mega Auto",
  "aliases": [],
  "details": {
   "notes": "",
   "source": "Liste de référence saisie par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": []
 },
 {
  "tour": "cedric",
  "name": "AT Auto",
  "aliases": [],
  "details": {
   "notes": "",
   "source": "Liste de référence saisie par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": []
 },
 {
  "tour": "cedric",
  "name": "EMD",
  "aliases": [],
  "details": {
   "notes": "",
   "source": "Liste de référence saisie par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": []
 },
 {
  "tour": "cedric",
  "name": "Carrosserie Sanchez",
  "aliases": [],
  "details": {
   "notes": "",
   "source": "Liste de référence saisie par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": []
 },
 {
  "tour": "cedric",
  "name": "Hureaux",
  "aliases": [],
  "details": {
   "notes": "",
   "source": "Liste de référence saisie par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": []
 },
 {
  "tour": "cedric",
  "name": "Yliass",
  "aliases": [],
  "details": {
   "notes": "",
   "source": "Liste de référence saisie par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": []
 },
 {
  "tour": "cedric",
  "name": "Lopez Qonian",
  "aliases": [],
  "details": {
   "notes": "",
   "source": "Liste de référence saisie par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": []
 },
 {
  "tour": "cedric",
  "name": "TPM",
  "aliases": [],
  "details": {
   "notes": "",
   "source": "Liste de référence saisie par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": []
 },
 {
  "tour": "cedric",
  "name": "Relais de l’Océan",
  "aliases": [],
  "details": {
   "notes": "",
   "source": "Liste de référence saisie par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": []
 },
 {
  "tour": "cedric",
  "name": "Bazé",
  "aliases": [],
  "details": {
   "notes": "",
   "source": "Liste de référence saisie par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": []
 },
 {
  "tour": "cedric",
  "name": "Sophydro",
  "aliases": [],
  "details": {
   "notes": "",
   "source": "Liste de référence saisie par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": []
 },
 {
  "tour": "cedric",
  "name": "Duchet",
  "aliases": [],
  "details": {
   "notes": "",
   "source": "Liste de référence saisie par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": []
 },
 {
  "tour": "cedric",
  "name": "Atelier Shark",
  "aliases": [],
  "details": {
   "notes": "",
   "source": "Liste de référence saisie par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": []
 },
 {
  "tour": "cedric",
  "name": "Pascassio",
  "aliases": [],
  "details": {
   "notes": "",
   "source": "Liste de référence saisie par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": []
 },
 {
  "tour": "cedric",
  "name": "Vulco",
  "aliases": [],
  "details": {
   "notes": "",
   "source": "Liste de référence saisie par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": []
 },
 {
  "tour": "cedric",
  "name": "Bayonne PL",
  "aliases": [],
  "details": {
   "notes": "",
   "source": "Liste de référence saisie par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": []
 },
 {
  "tour": "cedric",
  "name": "BMW",
  "aliases": [],
  "details": {
   "notes": "",
   "source": "Liste de référence saisie par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": []
 },
 {
  "tour": "cedric",
  "name": "Scania",
  "aliases": [
   "Scannia"
  ],
  "details": {
   "notes": "",
   "source": "Liste de référence saisie par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": []
 }
]$repclick_data$;
 waiting constant jsonb:=$repclick_data$[]$repclick_data$;
 e jsonb; target public.gestion_partners%rowtype; found_count integer; new_id uuid; is_new boolean;
 next_details jsonb; next_departures jsonb; rounds jsonb; known text; alias text; slot jsonb; fill_key text;
 created integer:=0; changed integer:=0; untouched integer:=0;
begin
 if not exists(select 1 from public.scanette_workspaces w where w.id=shop) then raise exception 'Shop % not found',shop; end if;
 lock table public.gestion_partners in share row exclusive mode;
 for e in select value from jsonb_array_elements(ref) loop
  is_new:=false;
  if e ? 'unique_like' then
   select count(*) into found_count from public.gestion_partners p where p.workspace_id=shop and p.kind='client' and not (p.details ? 'merged_into') and p.name ilike '%'||(e->>'unique_like')||'%';
   if found_count<>1 then raise exception 'Expected exactly one record whose name contains "%", found %: nothing is attached or created',e->>'unique_like',found_count; end if;
  end if;
  if e ? 'existing' then
   select count(*) into found_count from public.gestion_partners p where p.workspace_id=shop and p.kind='client' and p.name=e->>'existing' and not (p.details ? 'merged_into');
   if found_count<>1 then raise exception 'Expected exactly one record named "%", found %',e->>'existing',found_count; end if;
   select * into target from public.gestion_partners p where p.workspace_id=shop and p.kind='client' and p.name=e->>'existing' and not (p.details ? 'merged_into') for update;
  else
   new_id:=md5('repclick:internal-tours:2026-10-09:'||(e->>'tour')||':'||(e->>'name'))::uuid;
   -- A record created by hand is found again by its key; otherwise by the identifier this script gives.
   if e ? 'source_key' then
    select * into target from public.gestion_partners p where p.workspace_id=shop and p.kind='client' and p.source_key=e->>'source_key' for update;
   else
    select * into target from public.gestion_partners p where p.id=new_id for update;
   end if;
   if not found then
    if exists(select 1 from public.gestion_partners p where p.workspace_id=shop and p.kind='client' and not (p.details ? 'merged_into') and lower(btrim(p.name))=lower(btrim(e->>'name'))) then
     raise exception 'A record named "%" already exists: decide whether it is the same garage before adding it',e->>'name'; end if;
    is_new:=true; target.id:=new_id; target.name:=e->>'name'; target.details:=e->'details'; target.departures:='[]'::jsonb;
   elsif target.workspace_id<>shop or target.kind<>'client' then raise exception 'Record % belongs to another shop or kind',new_id;
   end if;
  end if;
  if e ? 'distinct_from' and (target.name=e->>'distinct_from' or lower(btrim(target.name))=lower(btrim(e->>'distinct_from'))) then
   raise exception '"%" must stay a record distinct from "%": refusing to merge them',e->>'name',e->>'distinct_from'; end if;
  -- Round: added to the list, never replacing another round.
  rounds:=case when jsonb_typeof(target.details->'tours')='array' then target.details->'tours' else '[]'::jsonb end;
  if not rounds ? (e->>'tour') then rounds:=rounds||to_jsonb(e->>'tour'); end if;
  next_details:=jsonb_set(target.details,'{tours}',rounds);
  -- Aliases: kept as the « a ; b » text the records already use; a variant is added once.
  known:=coalesce(next_details->>'aliases','');
  for alias in select value from jsonb_array_elements_text(e->'aliases') loop
   if lower(btrim(alias))<>lower(btrim(target.name)) and not exists(select 1 from regexp_split_to_table(known,'\s*[;,]\s*') a where lower(btrim(a))=lower(btrim(alias))) then
    known:=case when btrim(known)='' then alias else known||' ; '||alias end;
   end if;
  end loop;
  if known is distinct from coalesce(next_details->>'aliases','') then next_details:=jsonb_set(next_details,'{aliases}',to_jsonb(known)); end if;
  -- Confirmed details of an existing record: a key is added when the record has none; nothing is overwritten.
  for fill_key in select jsonb_object_keys(coalesce(e->'fill','{}'::jsonb)) loop
   if not (next_details ? fill_key) or coalesce(next_details->>fill_key,'')='' then next_details:=jsonb_set(next_details,array[fill_key],e->'fill'->fill_key); end if;
  end loop;
  -- Fixed departures (Charlie): added beside the existing ones, once.
  next_departures:=target.departures;
  for slot in select value from jsonb_array_elements(e->'slots') loop
   if not exists(select 1 from jsonb_array_elements(next_departures) s where lower(s.value->>'carrier')=lower(slot->>'carrier') and s.value->>'time'=slot->>'time') then
    next_departures:=next_departures||slot;
   end if;
  end loop;
  if jsonb_array_length(next_departures)>30 then raise exception 'Too many departures on "%"',target.name; end if;
  if is_new then
   insert into public.gestion_partners(id,workspace_id,kind,name,details,departures,source_key,version,updated_by)
   values(target.id,shop,'client',target.name,next_details,next_departures,coalesce(e->>'source_key',''),1,null);
   created:=created+1;
  elsif next_details is distinct from target.details or next_departures is distinct from target.departures then
   update public.gestion_partners p set details=next_details,departures=next_departures,version=p.version+1,updated_at=now() where p.id=target.id;
   changed:=changed+1;
  else untouched:=untouched+1;
  end if;
 end loop;
 if dry_run then
  raise exception 'DRY RUN OK — nothing written. Would create % record(s), complete % existing record(s), leave % unchanged. Pending, neither created nor attached: %',created,changed,untouched,
   coalesce((select string_agg((w.value->>'name')||' ['||(w.value->>'tour')||']',', ') from jsonb_array_elements(waiting) w),'none') using errcode='P0001';
 end if;
 raise notice 'Internal rounds: % record(s) created, % existing record(s) completed, % already up to date, % pending',created,changed,untouched,jsonb_array_length(waiting);
end $repclick_run$;
