-- Internal delivery rounds: undo internal-tours.sql.
-- Generated by scripts/build-internal-tours-sql.cjs from internal-tours-data.json — do not edit by hand.
-- Source: Liste de référence saisie par Alexis le 09/10/2026. No coordinate, hour or record comes from the Internet.
-- Run by hand as postgres in the Supabase SQL Editor. Not applied by the application.
-- ONE statement, with named dollar-quote tags and no transaction keyword of its own: it runs as a
-- whole or not at all, and survives tools that alter doubled dollar signs.
--
-- Removes exactly what internal-tours.sql added:
--   * records it created are deleted only if nobody changed them since (still version 1);
--     a record edited since is kept and only loses the round, and is listed in a notice;
--   * on the other records: the round, the added spelling variants and Charlie's two fixed
--     departures are removed; names, other hours and carriers are left as they are.
-- Atomic: a single statement. Idempotent: running it again changes nothing.
do $repclick_run$
declare shop constant uuid:='8770297c-cadb-4cc6-8b93-55a0f9bd154e';
 ref constant jsonb:=$repclick_data$[
 {
  "tour": "damian",
  "name": "JM Hirigoyen",
  "aliases": [],
  "details": {
   "city": "Arcangues",
   "address": "chemin du Mondarrain",
   "notes": "Garage à domicile.",
   "source": "Liste de référence saisie par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": []
 },
 {
  "tour": "damian",
  "name": "Carrosserie Biarrotte",
  "aliases": [],
  "details": {
   "city": "Biarritz",
   "notes": "Quartier de l’Allégresse.",
   "source": "Liste de référence saisie par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": []
 },
 {
  "tour": "damian",
  "name": "Garage de l’Allégresse",
  "aliases": [
   "Garage de la Négresse"
  ],
  "details": {
   "city": "Biarritz",
   "notes": "Anciennement Garage de la Négresse.",
   "source": "Liste de référence saisie par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": []
 },
 {
  "tour": "damian",
  "name": "Garage Modena",
  "aliases": [],
  "details": {
   "city": "Biarritz",
   "notes": "",
   "source": "Liste de référence saisie par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": []
 },
 {
  "tour": "damian",
  "name": "Ville de Biarritz",
  "aliases": [],
  "details": {
   "notes": "",
   "source": "Liste de référence saisie par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": []
 },
 {
  "tour": "damian",
  "name": "Garage l’Avenue",
  "aliases": [],
  "details": {
   "city": "Biarritz",
   "notes": "",
   "source": "Liste de référence saisie par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": []
 },
 {
  "tour": "damian",
  "name": "Crosa (Biarritz)",
  "aliases": [],
  "details": {
   "city": "Biarritz",
   "notes": "",
   "source": "Liste de référence saisie par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": []
 },
 {
  "tour": "damian",
  "existing": "First Stop Biarritz Pneus",
  "aliases": [],
  "fill": {},
  "slots": []
 },
 {
  "tour": "damian",
  "name": "Erviti Porsche",
  "aliases": [],
  "details": {
   "city": "Anglet",
   "notes": "",
   "source": "Liste de référence saisie par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": []
 },
 {
  "tour": "damian",
  "name": "Carro Vans",
  "aliases": [
   "Car Vans"
  ],
  "details": {
   "city": "Bidart",
   "notes": "",
   "source": "Liste de référence saisie par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": []
 },
 {
  "tour": "damian",
  "name": "Classic Vans",
  "aliases": [],
  "details": {
   "city": "Arbonne",
   "notes": "",
   "source": "Liste de référence saisie par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": []
 },
 {
  "tour": "damian",
  "name": "Dea",
  "aliases": [],
  "details": {
   "city": "Anglet",
   "notes": "",
   "source": "Liste de référence saisie par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": []
 },
 {
  "tour": "damian",
  "name": "Ville d’Anglet",
  "aliases": [],
  "details": {
   "notes": "",
   "source": "Liste de référence saisie par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": []
 },
 {
  "tour": "damian",
  "name": "MC Garage",
  "aliases": [],
  "details": {
   "notes": "",
   "source": "Liste de référence saisie par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": []
 },
 {
  "tour": "damian",
  "name": "Carrosserie Poau",
  "aliases": [],
  "details": {
   "notes": "Maignon.",
   "source": "Liste de référence saisie par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": []
 },
 {
  "tour": "damian",
  "name": "Jo Iribarren",
  "source_key": "tour-jo-iribarren-20261009",
  "distinct_from": "IRIBARREN PATRICK",
  "aliases": [
   "Irribarren",
   "Garage Jo Iribarren"
  ],
  "details": {
   "city": "Anglet",
   "address": "48 avenue de Cambo, Quartier Sutar, 64600 Anglet",
   "phones": [
    "05 59 42 37 67",
    "05 59 42 30 56"
   ],
   "hours": "Lundi à jeudi : 08h00–12h00 / 14h00–18h00 ; vendredi : 08h00–12h00 / 14h00–17h00.",
   "activities": "Réparation toutes marques, self-garage, contrôle anti-pollution, carrosserie, peinture, dépannage et remorquage, agrément assurances.",
   "source": "Informations fournies et confirmées par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": []
 },
 {
  "tour": "damian",
  "name": "Makila",
  "aliases": [],
  "details": {
   "network": "Toyota",
   "notes": "",
   "source": "Liste de référence saisie par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": []
 },
 {
  "tour": "damian",
  "name": "Land Rover / Auto Real",
  "aliases": [
   "Auto Real",
   "Land Rover"
  ],
  "details": {
   "notes": "",
   "source": "Liste de référence saisie par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": []
 },
 {
  "tour": "damian",
  "name": "Grimso",
  "aliases": [],
  "details": {
   "network": "Ford",
   "notes": "",
   "source": "Liste de référence saisie par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": []
 },
 {
  "tour": "damian",
  "name": "SB Auto",
  "aliases": [],
  "details": {
   "city": "Bassussary",
   "notes": "",
   "source": "Liste de référence saisie par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": []
 },
 {
  "tour": "damian",
  "name": "Peugeot",
  "aliases": [],
  "details": {
   "notes": "",
   "source": "Liste de référence saisie par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": []
 },
 {
  "tour": "damian",
  "name": "Honda",
  "aliases": [],
  "details": {
   "notes": "",
   "source": "Liste de référence saisie par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": []
 },
 {
  "tour": "damian",
  "name": "Car Bayonne",
  "aliases": [],
  "details": {
   "notes": "",
   "source": "Liste de référence saisie par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": []
 },
 {
  "tour": "damian",
  "name": "Belle Marion (Bayonne)",
  "aliases": [],
  "details": {
   "city": "Bayonne",
   "notes": "",
   "source": "Liste de référence saisie par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": []
 },
 {
  "tour": "damian",
  "name": "Maeva Car",
  "aliases": [],
  "details": {
   "notes": "",
   "source": "Liste de référence saisie par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": []
 },
 {
  "tour": "damian",
  "existing": "FEU VERT BIDART",
  "aliases": [],
  "fill": {},
  "slots": []
 },
 {
  "tour": "damian",
  "name": "Carrosserie de la Gare",
  "aliases": [],
  "details": {
   "notes": "",
   "source": "Liste de référence saisie par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": []
 },
 {
  "tour": "damian",
  "name": "SOS D Bosses",
  "aliases": [],
  "details": {
   "notes": "",
   "source": "Liste de référence saisie par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": []
 },
 {
  "tour": "damian",
  "name": "Etcheparre",
  "aliases": [],
  "details": {
   "notes": "",
   "source": "Liste de référence saisie par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": []
 },
 {
  "tour": "damian",
  "name": "Ocean Dépannage",
  "aliases": [],
  "details": {
   "notes": "",
   "source": "Liste de référence saisie par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": []
 },
 {
  "tour": "damian",
  "name": "Slavi",
  "aliases": [],
  "details": {
   "notes": "",
   "source": "Liste de référence saisie par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": []
 },
 {
  "tour": "maxime",
  "name": "Labachot (Anglet)",
  "aliases": [],
  "details": {
   "city": "Anglet",
   "notes": "",
   "source": "Liste de référence saisie par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": []
 },
 {
  "tour": "maxime",
  "name": "Norauto Pontot",
  "aliases": [
   "Nauroto Pontot"
  ],
  "details": {
   "notes": "",
   "source": "Liste de référence saisie par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": []
 },
 {
  "tour": "maxime",
  "name": "Garage du Centre",
  "aliases": [],
  "details": {
   "notes": "",
   "source": "Liste de référence saisie par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": []
 },
 {
  "tour": "maxime",
  "name": "Carrosserie Barcelona",
  "aliases": [],
  "details": {
   "notes": "",
   "source": "Liste de référence saisie par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": []
 },
 {
  "tour": "maxime",
  "name": "Carrosserie Moderne",
  "aliases": [],
  "details": {
   "notes": "",
   "source": "Liste de référence saisie par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": []
 },
 {
  "tour": "maxime",
  "name": "Feu Vert (Anglet)",
  "aliases": [],
  "details": {
   "city": "Anglet",
   "notes": "",
   "source": "Liste de référence saisie par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": []
 },
 {
  "tour": "maxime",
  "name": "Norauto France",
  "aliases": [
   "Nauroto France"
  ],
  "details": {
   "notes": "",
   "source": "Liste de référence saisie par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": []
 },
 {
  "tour": "maxime",
  "name": "Point S",
  "aliases": [],
  "details": {
   "address": "allée Paulmy",
   "notes": "",
   "source": "Liste de référence saisie par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": []
 },
 {
  "tour": "maxime",
  "name": "Pneu Service Auto",
  "aliases": [],
  "details": {
   "notes": "",
   "source": "Liste de référence saisie par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": []
 },
 {
  "tour": "maxime",
  "name": "Ondres Auto",
  "aliases": [],
  "details": {
   "notes": "",
   "source": "Liste de référence saisie par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": []
 },
 {
  "tour": "maxime",
  "name": "Pneu du BAB",
  "aliases": [],
  "details": {
   "notes": "",
   "source": "Liste de référence saisie par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": []
 },
 {
  "tour": "maxime",
  "name": "Concept Car",
  "aliases": [],
  "details": {
   "notes": "",
   "source": "Liste de référence saisie par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": []
 },
 {
  "tour": "maxime",
  "name": "Atelier Carrosserie Shark",
  "aliases": [],
  "details": {
   "notes": "",
   "source": "Liste de référence saisie par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": []
 },
 {
  "tour": "maxime",
  "name": "Euromaster (allées Marines)",
  "aliases": [],
  "details": {
   "address": "allées Marines",
   "notes": "",
   "source": "Liste de référence saisie par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": []
 },
 {
  "tour": "maxime",
  "name": "Hirigoyen",
  "aliases": [],
  "details": {
   "notes": "",
   "source": "Liste de référence saisie par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": []
 },
 {
  "tour": "maxime",
  "name": "JC Auto",
  "aliases": [],
  "details": {
   "notes": "",
   "source": "Liste de référence saisie par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": []
 },
 {
  "tour": "maxime",
  "name": "Auto Sélection",
  "aliases": [],
  "details": {
   "notes": "",
   "source": "Liste de référence saisie par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": []
 },
 {
  "tour": "maxime",
  "name": "Castagnet",
  "aliases": [],
  "details": {
   "notes": "Total, allées Marines.",
   "source": "Liste de référence saisie par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": []
 },
 {
  "tour": "maxime",
  "name": "Fidalgo",
  "aliases": [],
  "details": {
   "notes": "",
   "source": "Liste de référence saisie par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": []
 },
 {
  "tour": "maxime",
  "name": "Belle Marion (Anglet)",
  "aliases": [],
  "details": {
   "city": "Anglet",
   "notes": "",
   "source": "Liste de référence saisie par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": []
 },
 {
  "tour": "maxime",
  "name": "Anglet Auto Service",
  "aliases": [],
  "details": {
   "notes": "",
   "source": "Liste de référence saisie par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": []
 },
 {
  "tour": "maxime",
  "name": "Ferdinand Aviation",
  "aliases": [],
  "details": {
   "notes": "Particulier.",
   "source": "Liste de référence saisie par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": []
 },
 {
  "tour": "maxime",
  "name": "Cossec",
  "aliases": [],
  "details": {
   "notes": "",
   "source": "Liste de référence saisie par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": []
 },
 {
  "tour": "maxime",
  "name": "Service Auto 64",
  "aliases": [],
  "details": {
   "notes": "",
   "source": "Liste de référence saisie par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": []
 },
 {
  "tour": "maxime",
  "name": "Communauté de Bayonne",
  "aliases": [],
  "details": {
   "notes": "",
   "source": "Liste de référence saisie par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": []
 },
 {
  "tour": "maxime",
  "name": "Urrusty",
  "aliases": [],
  "details": {
   "notes": "",
   "source": "Liste de référence saisie par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": []
 },
 {
  "tour": "maxime",
  "name": "Dayde",
  "aliases": [],
  "details": {
   "notes": "",
   "source": "Liste de référence saisie par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": []
 },
 {
  "tour": "maxime",
  "name": "Mendi",
  "aliases": [],
  "details": {
   "notes": "",
   "source": "Liste de référence saisie par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": []
 },
 {
  "tour": "charlie",
  "name": "Lamerain Renault",
  "aliases": [],
  "details": {
   "notes": "",
   "source": "Liste de référence saisie par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": [
   {
    "mode": "internal",
    "carrier": "Charlie",
    "time": "10:00",
    "cutoff": "",
    "sector": "Saint-Jean-de-Luz / Urrugne / Ciboure / Ascain / Saint-Pée-sur-Nivelle",
    "place": "",
    "notes": "",
    "days": [
     1,
     2,
     3,
     4,
     5
    ]
   },
   {
    "mode": "internal",
    "carrier": "Charlie",
    "time": "15:00",
    "cutoff": "",
    "sector": "Saint-Jean-de-Luz / Urrugne / Ciboure / Ascain / Saint-Pée-sur-Nivelle",
    "place": "",
    "notes": "",
    "days": [
     1,
     2,
     3,
     4,
     5
    ]
   }
  ]
 },
 {
  "tour": "charlie",
  "name": "Cigarroa",
  "aliases": [],
  "details": {
   "notes": "",
   "source": "Liste de référence saisie par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": [
   {
    "mode": "internal",
    "carrier": "Charlie",
    "time": "10:00",
    "cutoff": "",
    "sector": "Saint-Jean-de-Luz / Urrugne / Ciboure / Ascain / Saint-Pée-sur-Nivelle",
    "place": "",
    "notes": "",
    "days": [
     1,
     2,
     3,
     4,
     5
    ]
   },
   {
    "mode": "internal",
    "carrier": "Charlie",
    "time": "15:00",
    "cutoff": "",
    "sector": "Saint-Jean-de-Luz / Urrugne / Ciboure / Ascain / Saint-Pée-sur-Nivelle",
    "place": "",
    "notes": "",
    "days": [
     1,
     2,
     3,
     4,
     5
    ]
   }
  ]
 },
 {
  "tour": "charlie",
  "existing": "CN AUTO",
  "aliases": [],
  "fill": {},
  "slots": [
   {
    "mode": "internal",
    "carrier": "Charlie",
    "time": "10:00",
    "cutoff": "",
    "sector": "Saint-Jean-de-Luz / Urrugne / Ciboure / Ascain / Saint-Pée-sur-Nivelle",
    "place": "",
    "notes": "",
    "days": [
     1,
     2,
     3,
     4,
     5
    ]
   },
   {
    "mode": "internal",
    "carrier": "Charlie",
    "time": "15:00",
    "cutoff": "",
    "sector": "Saint-Jean-de-Luz / Urrugne / Ciboure / Ascain / Saint-Pée-sur-Nivelle",
    "place": "",
    "notes": "",
    "days": [
     1,
     2,
     3,
     4,
     5
    ]
   }
  ]
 },
 {
  "tour": "charlie",
  "existing": "First Stop Laboudigue Saint-Jean-de-Luz",
  "aliases": [],
  "fill": {},
  "slots": [
   {
    "mode": "internal",
    "carrier": "Charlie",
    "time": "10:00",
    "cutoff": "",
    "sector": "Saint-Jean-de-Luz / Urrugne / Ciboure / Ascain / Saint-Pée-sur-Nivelle",
    "place": "",
    "notes": "",
    "days": [
     1,
     2,
     3,
     4,
     5
    ]
   },
   {
    "mode": "internal",
    "carrier": "Charlie",
    "time": "15:00",
    "cutoff": "",
    "sector": "Saint-Jean-de-Luz / Urrugne / Ciboure / Ascain / Saint-Pée-sur-Nivelle",
    "place": "",
    "notes": "",
    "days": [
     1,
     2,
     3,
     4,
     5
    ]
   }
  ]
 },
 {
  "tour": "charlie",
  "existing": "LECLERC ST JEAN DE LUZ",
  "aliases": [
   "Leclerc Auto"
  ],
  "fill": {},
  "slots": [
   {
    "mode": "internal",
    "carrier": "Charlie",
    "time": "10:00",
    "cutoff": "",
    "sector": "Saint-Jean-de-Luz / Urrugne / Ciboure / Ascain / Saint-Pée-sur-Nivelle",
    "place": "",
    "notes": "",
    "days": [
     1,
     2,
     3,
     4,
     5
    ]
   },
   {
    "mode": "internal",
    "carrier": "Charlie",
    "time": "15:00",
    "cutoff": "",
    "sector": "Saint-Jean-de-Luz / Urrugne / Ciboure / Ascain / Saint-Pée-sur-Nivelle",
    "place": "",
    "notes": "",
    "days": [
     1,
     2,
     3,
     4,
     5
    ]
   }
  ]
 },
 {
  "tour": "charlie",
  "existing": "AUTO SPORT",
  "aliases": [
   "Autosport"
  ],
  "fill": {},
  "slots": [
   {
    "mode": "internal",
    "carrier": "Charlie",
    "time": "10:00",
    "cutoff": "",
    "sector": "Saint-Jean-de-Luz / Urrugne / Ciboure / Ascain / Saint-Pée-sur-Nivelle",
    "place": "",
    "notes": "",
    "days": [
     1,
     2,
     3,
     4,
     5
    ]
   },
   {
    "mode": "internal",
    "carrier": "Charlie",
    "time": "15:00",
    "cutoff": "",
    "sector": "Saint-Jean-de-Luz / Urrugne / Ciboure / Ascain / Saint-Pée-sur-Nivelle",
    "place": "",
    "notes": "",
    "days": [
     1,
     2,
     3,
     4,
     5
    ]
   }
  ]
 },
 {
  "tour": "charlie",
  "name": "Auto 64",
  "aliases": [],
  "details": {
   "notes": "",
   "source": "Liste de référence saisie par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": [
   {
    "mode": "internal",
    "carrier": "Charlie",
    "time": "10:00",
    "cutoff": "",
    "sector": "Saint-Jean-de-Luz / Urrugne / Ciboure / Ascain / Saint-Pée-sur-Nivelle",
    "place": "",
    "notes": "",
    "days": [
     1,
     2,
     3,
     4,
     5
    ]
   },
   {
    "mode": "internal",
    "carrier": "Charlie",
    "time": "15:00",
    "cutoff": "",
    "sector": "Saint-Jean-de-Luz / Urrugne / Ciboure / Ascain / Saint-Pée-sur-Nivelle",
    "place": "",
    "notes": "",
    "days": [
     1,
     2,
     3,
     4,
     5
    ]
   }
  ]
 },
 {
  "tour": "charlie",
  "existing": "MARINELA",
  "aliases": [],
  "fill": {},
  "slots": [
   {
    "mode": "internal",
    "carrier": "Charlie",
    "time": "10:00",
    "cutoff": "",
    "sector": "Saint-Jean-de-Luz / Urrugne / Ciboure / Ascain / Saint-Pée-sur-Nivelle",
    "place": "",
    "notes": "",
    "days": [
     1,
     2,
     3,
     4,
     5
    ]
   },
   {
    "mode": "internal",
    "carrier": "Charlie",
    "time": "15:00",
    "cutoff": "",
    "sector": "Saint-Jean-de-Luz / Urrugne / Ciboure / Ascain / Saint-Pée-sur-Nivelle",
    "place": "",
    "notes": "",
    "days": [
     1,
     2,
     3,
     4,
     5
    ]
   }
  ]
 },
 {
  "tour": "charlie",
  "existing": "DALLARD ST JEAN DE LUZ",
  "aliases": [],
  "fill": {},
  "slots": [
   {
    "mode": "internal",
    "carrier": "Charlie",
    "time": "10:00",
    "cutoff": "",
    "sector": "Saint-Jean-de-Luz / Urrugne / Ciboure / Ascain / Saint-Pée-sur-Nivelle",
    "place": "",
    "notes": "",
    "days": [
     1,
     2,
     3,
     4,
     5
    ]
   },
   {
    "mode": "internal",
    "carrier": "Charlie",
    "time": "15:00",
    "cutoff": "",
    "sector": "Saint-Jean-de-Luz / Urrugne / Ciboure / Ascain / Saint-Pée-sur-Nivelle",
    "place": "",
    "notes": "",
    "days": [
     1,
     2,
     3,
     4,
     5
    ]
   }
  ]
 },
 {
  "tour": "charlie",
  "name": "Huchet",
  "aliases": [],
  "details": {
   "notes": "",
   "source": "Liste de référence saisie par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": [
   {
    "mode": "internal",
    "carrier": "Charlie",
    "time": "10:00",
    "cutoff": "",
    "sector": "Saint-Jean-de-Luz / Urrugne / Ciboure / Ascain / Saint-Pée-sur-Nivelle",
    "place": "",
    "notes": "",
    "days": [
     1,
     2,
     3,
     4,
     5
    ]
   },
   {
    "mode": "internal",
    "carrier": "Charlie",
    "time": "15:00",
    "cutoff": "",
    "sector": "Saint-Jean-de-Luz / Urrugne / Ciboure / Ascain / Saint-Pée-sur-Nivelle",
    "place": "",
    "notes": "",
    "days": [
     1,
     2,
     3,
     4,
     5
    ]
   }
  ]
 },
 {
  "tour": "charlie",
  "existing": "JS AUTO",
  "aliases": [],
  "fill": {},
  "slots": [
   {
    "mode": "internal",
    "carrier": "Charlie",
    "time": "10:00",
    "cutoff": "",
    "sector": "Saint-Jean-de-Luz / Urrugne / Ciboure / Ascain / Saint-Pée-sur-Nivelle",
    "place": "",
    "notes": "",
    "days": [
     1,
     2,
     3,
     4,
     5
    ]
   },
   {
    "mode": "internal",
    "carrier": "Charlie",
    "time": "15:00",
    "cutoff": "",
    "sector": "Saint-Jean-de-Luz / Urrugne / Ciboure / Ascain / Saint-Pée-sur-Nivelle",
    "place": "",
    "notes": "",
    "days": [
     1,
     2,
     3,
     4,
     5
    ]
   }
  ]
 },
 {
  "tour": "charlie",
  "name": "Top Auto",
  "aliases": [],
  "details": {
   "notes": "",
   "source": "Liste de référence saisie par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": [
   {
    "mode": "internal",
    "carrier": "Charlie",
    "time": "10:00",
    "cutoff": "",
    "sector": "Saint-Jean-de-Luz / Urrugne / Ciboure / Ascain / Saint-Pée-sur-Nivelle",
    "place": "",
    "notes": "",
    "days": [
     1,
     2,
     3,
     4,
     5
    ]
   },
   {
    "mode": "internal",
    "carrier": "Charlie",
    "time": "15:00",
    "cutoff": "",
    "sector": "Saint-Jean-de-Luz / Urrugne / Ciboure / Ascain / Saint-Pée-sur-Nivelle",
    "place": "",
    "notes": "",
    "days": [
     1,
     2,
     3,
     4,
     5
    ]
   }
  ]
 },
 {
  "tour": "charlie",
  "name": "PBA",
  "aliases": [],
  "details": {
   "notes": "",
   "source": "Liste de référence saisie par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": [
   {
    "mode": "internal",
    "carrier": "Charlie",
    "time": "10:00",
    "cutoff": "",
    "sector": "Saint-Jean-de-Luz / Urrugne / Ciboure / Ascain / Saint-Pée-sur-Nivelle",
    "place": "",
    "notes": "",
    "days": [
     1,
     2,
     3,
     4,
     5
    ]
   },
   {
    "mode": "internal",
    "carrier": "Charlie",
    "time": "15:00",
    "cutoff": "",
    "sector": "Saint-Jean-de-Luz / Urrugne / Ciboure / Ascain / Saint-Pée-sur-Nivelle",
    "place": "",
    "notes": "",
    "days": [
     1,
     2,
     3,
     4,
     5
    ]
   }
  ]
 },
 {
  "tour": "charlie",
  "name": "Antao",
  "aliases": [],
  "details": {
   "notes": "",
   "source": "Liste de référence saisie par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": [
   {
    "mode": "internal",
    "carrier": "Charlie",
    "time": "10:00",
    "cutoff": "",
    "sector": "Saint-Jean-de-Luz / Urrugne / Ciboure / Ascain / Saint-Pée-sur-Nivelle",
    "place": "",
    "notes": "",
    "days": [
     1,
     2,
     3,
     4,
     5
    ]
   },
   {
    "mode": "internal",
    "carrier": "Charlie",
    "time": "15:00",
    "cutoff": "",
    "sector": "Saint-Jean-de-Luz / Urrugne / Ciboure / Ascain / Saint-Pée-sur-Nivelle",
    "place": "",
    "notes": "",
    "days": [
     1,
     2,
     3,
     4,
     5
    ]
   }
  ]
 },
 {
  "tour": "charlie",
  "name": "Darboure Pampi",
  "aliases": [],
  "details": {
   "notes": "",
   "source": "Liste de référence saisie par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": [
   {
    "mode": "internal",
    "carrier": "Charlie",
    "time": "10:00",
    "cutoff": "",
    "sector": "Saint-Jean-de-Luz / Urrugne / Ciboure / Ascain / Saint-Pée-sur-Nivelle",
    "place": "",
    "notes": "",
    "days": [
     1,
     2,
     3,
     4,
     5
    ]
   },
   {
    "mode": "internal",
    "carrier": "Charlie",
    "time": "15:00",
    "cutoff": "",
    "sector": "Saint-Jean-de-Luz / Urrugne / Ciboure / Ascain / Saint-Pée-sur-Nivelle",
    "place": "",
    "notes": "",
    "days": [
     1,
     2,
     3,
     4,
     5
    ]
   }
  ]
 },
 {
  "tour": "charlie",
  "existing": "HERRIKOA",
  "aliases": [],
  "fill": {},
  "slots": [
   {
    "mode": "internal",
    "carrier": "Charlie",
    "time": "10:00",
    "cutoff": "",
    "sector": "Saint-Jean-de-Luz / Urrugne / Ciboure / Ascain / Saint-Pée-sur-Nivelle",
    "place": "",
    "notes": "",
    "days": [
     1,
     2,
     3,
     4,
     5
    ]
   },
   {
    "mode": "internal",
    "carrier": "Charlie",
    "time": "15:00",
    "cutoff": "",
    "sector": "Saint-Jean-de-Luz / Urrugne / Ciboure / Ascain / Saint-Pée-sur-Nivelle",
    "place": "",
    "notes": "",
    "days": [
     1,
     2,
     3,
     4,
     5
    ]
   }
  ]
 },
 {
  "tour": "charlie",
  "name": "Darboure Famille",
  "aliases": [],
  "details": {
   "notes": "Particulier.",
   "source": "Liste de référence saisie par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": [
   {
    "mode": "internal",
    "carrier": "Charlie",
    "time": "10:00",
    "cutoff": "",
    "sector": "Saint-Jean-de-Luz / Urrugne / Ciboure / Ascain / Saint-Pée-sur-Nivelle",
    "place": "",
    "notes": "",
    "days": [
     1,
     2,
     3,
     4,
     5
    ]
   },
   {
    "mode": "internal",
    "carrier": "Charlie",
    "time": "15:00",
    "cutoff": "",
    "sector": "Saint-Jean-de-Luz / Urrugne / Ciboure / Ascain / Saint-Pée-sur-Nivelle",
    "place": "",
    "notes": "",
    "days": [
     1,
     2,
     3,
     4,
     5
    ]
   }
  ]
 },
 {
  "tour": "charlie",
  "name": "Endarra",
  "aliases": [],
  "details": {
   "notes": "",
   "source": "Liste de référence saisie par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": [
   {
    "mode": "internal",
    "carrier": "Charlie",
    "time": "10:00",
    "cutoff": "",
    "sector": "Saint-Jean-de-Luz / Urrugne / Ciboure / Ascain / Saint-Pée-sur-Nivelle",
    "place": "",
    "notes": "",
    "days": [
     1,
     2,
     3,
     4,
     5
    ]
   },
   {
    "mode": "internal",
    "carrier": "Charlie",
    "time": "15:00",
    "cutoff": "",
    "sector": "Saint-Jean-de-Luz / Urrugne / Ciboure / Ascain / Saint-Pée-sur-Nivelle",
    "place": "",
    "notes": "",
    "days": [
     1,
     2,
     3,
     4,
     5
    ]
   }
  ]
 },
 {
  "tour": "charlie",
  "name": "Pare-Brise 64",
  "aliases": [],
  "details": {
   "notes": "",
   "source": "Liste de référence saisie par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": [
   {
    "mode": "internal",
    "carrier": "Charlie",
    "time": "10:00",
    "cutoff": "",
    "sector": "Saint-Jean-de-Luz / Urrugne / Ciboure / Ascain / Saint-Pée-sur-Nivelle",
    "place": "",
    "notes": "",
    "days": [
     1,
     2,
     3,
     4,
     5
    ]
   },
   {
    "mode": "internal",
    "carrier": "Charlie",
    "time": "15:00",
    "cutoff": "",
    "sector": "Saint-Jean-de-Luz / Urrugne / Ciboure / Ascain / Saint-Pée-sur-Nivelle",
    "place": "",
    "notes": "",
    "days": [
     1,
     2,
     3,
     4,
     5
    ]
   }
  ]
 },
 {
  "tour": "cedric",
  "name": "Adrien",
  "aliases": [],
  "details": {
   "notes": "",
   "source": "Liste de référence saisie par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": []
 },
 {
  "tour": "cedric",
  "name": "Charli’Auto",
  "aliases": [],
  "details": {
   "notes": "",
   "source": "Liste de référence saisie par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": []
 },
 {
  "tour": "cedric",
  "name": "Hôpital de Bayonne",
  "aliases": [],
  "details": {
   "notes": "",
   "source": "Liste de référence saisie par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": []
 },
 {
  "tour": "cedric",
  "name": "Bay Utilitaire",
  "aliases": [],
  "details": {
   "notes": "",
   "source": "Liste de référence saisie par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": []
 },
 {
  "tour": "cedric",
  "name": "Carrosserie Grand Basque",
  "aliases": [],
  "details": {
   "notes": "",
   "source": "Liste de référence saisie par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": []
 },
 {
  "tour": "cedric",
  "name": "Garage des 3 Vallées",
  "aliases": [],
  "details": {
   "notes": "",
   "source": "Liste de référence saisie par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": []
 },
 {
  "tour": "cedric",
  "existing": "AUGARAY (ROADY)",
  "unique_like": "roady",
  "aliases": [
   "Roady Bayonne",
   "Centre auto Roady Bayonne"
  ],
  "fill": {
   "city": "Bayonne",
   "address": "12 allée de Biarnes, 64100 Bayonne",
   "phone": "05 18 23 07 86",
   "hours": "Lundi à vendredi : 09h00–12h00 / 14h00–19h00 ; samedi : 09h00–12h00 / 14h00–18h00 ; dimanche : fermé."
  },
  "slots": []
 },
 {
  "tour": "cedric",
  "name": "Iveco",
  "aliases": [
   "Yveco"
  ],
  "details": {
   "notes": "",
   "source": "Liste de référence saisie par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": []
 },
 {
  "tour": "cedric",
  "name": "Barthes",
  "aliases": [],
  "details": {
   "notes": "",
   "source": "Liste de référence saisie par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": []
 },
 {
  "tour": "cedric",
  "name": "Dulamon",
  "aliases": [],
  "details": {
   "notes": "",
   "source": "Liste de référence saisie par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": []
 },
 {
  "tour": "cedric",
  "name": "Feu Vert (Tarnos)",
  "aliases": [],
  "details": {
   "city": "Tarnos",
   "notes": "",
   "source": "Liste de référence saisie par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": []
 },
 {
  "tour": "cedric",
  "name": "Mega Auto",
  "aliases": [],
  "details": {
   "notes": "",
   "source": "Liste de référence saisie par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": []
 },
 {
  "tour": "cedric",
  "name": "AT Auto",
  "aliases": [],
  "details": {
   "notes": "",
   "source": "Liste de référence saisie par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": []
 },
 {
  "tour": "cedric",
  "name": "EMD",
  "aliases": [],
  "details": {
   "notes": "",
   "source": "Liste de référence saisie par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": []
 },
 {
  "tour": "cedric",
  "name": "Carrosserie Sanchez",
  "aliases": [],
  "details": {
   "notes": "",
   "source": "Liste de référence saisie par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": []
 },
 {
  "tour": "cedric",
  "name": "Hureaux",
  "aliases": [],
  "details": {
   "notes": "",
   "source": "Liste de référence saisie par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": []
 },
 {
  "tour": "cedric",
  "name": "Yliass",
  "aliases": [],
  "details": {
   "notes": "",
   "source": "Liste de référence saisie par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": []
 },
 {
  "tour": "cedric",
  "name": "Lopez Qonian",
  "aliases": [],
  "details": {
   "notes": "",
   "source": "Liste de référence saisie par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": []
 },
 {
  "tour": "cedric",
  "name": "TPM",
  "aliases": [],
  "details": {
   "notes": "",
   "source": "Liste de référence saisie par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": []
 },
 {
  "tour": "cedric",
  "name": "Relais de l’Océan",
  "aliases": [],
  "details": {
   "notes": "",
   "source": "Liste de référence saisie par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": []
 },
 {
  "tour": "cedric",
  "name": "Bazé",
  "aliases": [],
  "details": {
   "notes": "",
   "source": "Liste de référence saisie par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": []
 },
 {
  "tour": "cedric",
  "name": "Sophydro",
  "aliases": [],
  "details": {
   "notes": "",
   "source": "Liste de référence saisie par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": []
 },
 {
  "tour": "cedric",
  "name": "Duchet",
  "aliases": [],
  "details": {
   "notes": "",
   "source": "Liste de référence saisie par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": []
 },
 {
  "tour": "cedric",
  "name": "Atelier Shark",
  "aliases": [],
  "details": {
   "notes": "",
   "source": "Liste de référence saisie par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": []
 },
 {
  "tour": "cedric",
  "name": "Pascassio",
  "aliases": [],
  "details": {
   "notes": "",
   "source": "Liste de référence saisie par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": []
 },
 {
  "tour": "cedric",
  "name": "Vulco",
  "aliases": [],
  "details": {
   "notes": "",
   "source": "Liste de référence saisie par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": []
 },
 {
  "tour": "cedric",
  "name": "Bayonne PL",
  "aliases": [],
  "details": {
   "notes": "",
   "source": "Liste de référence saisie par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": []
 },
 {
  "tour": "cedric",
  "name": "BMW",
  "aliases": [],
  "details": {
   "notes": "",
   "source": "Liste de référence saisie par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": []
 },
 {
  "tour": "cedric",
  "name": "Scania",
  "aliases": [
   "Scannia"
  ],
  "details": {
   "notes": "",
   "source": "Liste de référence saisie par Alexis le 09/10/2026",
   "aliases": ""
  },
  "fill": {},
  "slots": []
 }
]$repclick_data$;
 e jsonb; target public.gestion_partners%rowtype; new_id uuid; next_details jsonb; next_departures jsonb; rounds jsonb; known text; alias text; fill_key text;
 deleted integer:=0; changed integer:=0; kept text:='';
begin
 lock table public.gestion_partners in share row exclusive mode;
 for e in select value from jsonb_array_elements(ref) loop
  if e ? 'existing' then
   select * into target from public.gestion_partners p where p.workspace_id=shop and p.kind='client' and p.name=e->>'existing' and not (p.details ? 'merged_into') for update;
  else
   new_id:=md5('repclick:internal-tours:2026-10-09:'||(e->>'tour')||':'||(e->>'name'))::uuid;
   if e ? 'source_key' then
    select * into target from public.gestion_partners p where p.workspace_id=shop and p.kind='client' and p.source_key=e->>'source_key' for update;
   else
    select * into target from public.gestion_partners p where p.id=new_id and p.workspace_id=shop for update;
   end if;
   if found and target.version=1 then delete from public.gestion_partners p where p.id=target.id; deleted:=deleted+1; continue; end if;
   if found then kept:=kept||case when kept='' then '' else ', ' end||target.name; end if;
  end if;
  if not found then continue; end if;
  rounds:=coalesce((select jsonb_agg(r.value) from jsonb_array_elements(case when jsonb_typeof(target.details->'tours')='array' then target.details->'tours' else '[]'::jsonb end) r where r.value<>to_jsonb(e->>'tour')),'[]'::jsonb);
  next_details:=case when jsonb_array_length(rounds)=0 then target.details-'tours' else jsonb_set(target.details,'{tours}',rounds) end;
  if e ? 'existing' and jsonb_array_length(e->'aliases')>0 and next_details ? 'aliases' then
   known:=coalesce((select string_agg(btrim(a),' ; ') from regexp_split_to_table(next_details->>'aliases','\s*[;,]\s*') a
    where btrim(a)<>'' and not exists(select 1 from jsonb_array_elements_text(e->'aliases') x where lower(btrim(x.value))=lower(btrim(a)))),'');
   next_details:=jsonb_set(next_details,'{aliases}',to_jsonb(known));
  end if;
  -- Details this script added to an existing record are removed only if they still hold the same value.
  for fill_key in select jsonb_object_keys(coalesce(e->'fill','{}'::jsonb)) loop
   if next_details->fill_key=e->'fill'->fill_key then next_details:=next_details-fill_key; end if;
  end loop;
  next_departures:=coalesce((select jsonb_agg(s.value) from jsonb_array_elements(target.departures) s where not exists(select 1 from jsonb_array_elements(e->'slots') x where x.value=s.value)),'[]'::jsonb);
  if next_details is distinct from target.details or next_departures is distinct from target.departures then
   update public.gestion_partners p set details=next_details,departures=next_departures,version=p.version+1,updated_at=now() where p.id=target.id;
   changed:=changed+1;
  end if;
 end loop;
 raise notice 'Internal rounds undone: % created record(s) deleted, % record(s) restored',deleted,changed;
 if kept<>'' then raise notice 'Created records edited since, kept without their round: %',kept; end if;
end $repclick_run$;
