-- Internal delivery rounds: read-only report, before or after internal-tours.sql.
-- Generated by scripts/build-internal-tours-sql.cjs from internal-tours-data.json — do not edit by hand.
-- Source: Liste de référence saisie par Alexis le 09/10/2026. No coordinate, hour or record comes from the Internet.
-- Run by hand as postgres in the Supabase SQL Editor. Not applied by the application.
select t.round as tournee,
 count(*) filter (where p.id is not null) as fiches_rattachees,
 count(*) filter (where p.id is not null and jsonb_array_length(p.departures)=0) as sans_horaire,
 count(*) filter (where p.id is not null and exists(select 1 from jsonb_array_elements(p.departures) s where lower(s.value->>'carrier')=lower(t.round))) as avec_departs_de_la_tournee
from (values ('damian'),('maxime'),('charlie'),('cedric')) t(round)
left join public.gestion_partners p on p.workspace_id='8770297c-cadb-4cc6-8b93-55a0f9bd154e' and p.kind='client' and not (p.details ? 'merged_into')
 and jsonb_typeof(p.details->'tours')='array' and p.details->'tours' ? t.round
group by t.round order by t.round;
-- Expected after the mutation: cedric 28, charlie 19, damian 30, maxime 28. Charlie: every record has his two departures.
select p.name as fiche_existante_completee,p.details->'tours' as tournees,p.details->>'aliases' as variantes,
 (select string_agg((s.value->>'carrier')||' '||(s.value->>'time'),', ' order by s.value->>'time') from jsonb_array_elements(p.departures) s) as departs
from public.gestion_partners p where p.workspace_id='8770297c-cadb-4cc6-8b93-55a0f9bd154e' and p.kind='client'
 and p.name in ('First Stop Biarritz Pneus','FEU VERT BIDART','CN AUTO','First Stop Laboudigue Saint-Jean-de-Luz','LECLERC ST JEAN DE LUZ','AUTO SPORT','MARINELA','DALLARD ST JEAN DE LUZ','JS AUTO','HERRIKOA') order by p.name;
