const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),C=require('./inventory/core.js');
function setup({data=null,error=null,closed=false}={}){
 const nodes={};function node(id=''){return {id,hidden:['work','camera','resume'].includes(id),disabled:['brand','range','zone','begin','beginScan'].includes(id),value:'',textContent:'',children:[],options:[],classList:{toggle(){}},replaceChildren(...x){this.children=[...x];this.options=[...x];},append(...x){this.children.push(...x);this.options.push(...x)},setAttribute(){},addEventListener(){},querySelector(){return null},querySelectorAll(){return []},focus(){},click(){return this.onclick?.()},scrollIntoView(){}};}
 const $=id=>nodes[id]??=node(id);let calls=0,saved=null;
 // Shared access facade as loaded by the page: the only call is shared_inventory_current, without any shop argument.
 const shared={call:async(name,args)=>{calls++;assert.equal(name,'shared_inventory_current');assert.equal(args,undefined);if(closed)throw Object.assign(Error('closed'),{code:'42501'});if(error)throw Object.assign(Error(error.message),{code:'XX000'});return data;},message:()=>'L’accès logistique partagé est fermé pour le moment.'};
 const context={InventoryCore:C,InventoryStorage:{all:async()=>[],save:async(d,r)=>(saved=structuredClone(d),{...d,revision:r+1,updatedAt:new Date().toISOString()})},structuredClone,Date,Map,Set,Promise,crypto:{randomUUID:()=> 'draft'},Option:function(t,v){this.text=t;this.value=v},document:{getElementById:$,createElement:()=>node(),addEventListener(){},head:node()},window:{supabase:{},SharedAccess:shared,parent:{postMessage(){}},addEventListener(){}},location:{hash:'',origin:'https://example.test'},navigator:{},setInterval(){},setTimeout(){}};
 vm.runInNewContext(fs.readFileSync('inventory/app.js','utf8'),context);return {nodes,$,get saved(){return saved},get calls(){return calls}};
}
const tick=()=>new Promise(r=>setImmediate(r));
const list={title:'Magasin',rows:[{id:'1',reference:'001',brand:'Bosch',range:'Disques',location:'A19a'},{id:'2',reference:'002',brand:'Purflux',range:'Filtres',location:'A2'}]};
test('Opening inventory from the shared logistics access loads usable brand/range/location filters',async()=>{const a=setup({data:list});await tick();assert.equal(a.calls,1);assert.equal(a.$('begin').disabled,false);assert.equal(a.$('beginScan').disabled,false);assert.equal(a.$('brand').options.length,3);a.$('brand').value='Bosch';a.$('brand').onchange();assert.equal(a.$('range').options.length,2);assert.match(a.$('selectionCount').textContent,/1 références/);assert.equal(a.$('zone').options[1].value,'A19a');});
test('Scan entry requires a name and opens scanner only after creating its local count',async()=>{const a=setup({data:list});await tick();let scans=0;a.$('scan').onclick=()=>scans++;await a.$('beginScan').onclick();assert.equal(scans,0);a.$('employee').value='Test';await a.$('beginScan').onclick();assert.equal(a.$('work').hidden,false);assert.equal(scans,1);});
test('Closed shared access or server errors leave controls disabled with explanation',async()=>{const a=setup({closed:true});await tick();assert.equal(a.calls,1);assert.equal(a.$('begin').disabled,true);assert.match(a.$('message').textContent,/fermé/);const b=setup({error:{message:'offline'}});await tick();assert.equal(b.$('beginScan').disabled,true);assert.match(b.$('message').textContent,/indisponible/);});


test('Second counter is displayed and persisted in the local inventory',async()=>{const a=setup({data:list});await tick();a.$('employee').value='Alexis';a.$('employee2').value='Axel';await a.$('begin').onclick();assert.equal(a.saved.employee2,'Axel');assert.equal(a.saved.employee,'Alexis');assert.match(a.$('title').textContent,/Alexis \/ Axel/);});
