const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs');
function setup({lost=false,records=[]}={}){
 const nodes={},partners=[{id:'known',name:'IDLP'}],calls=[];let serial=0,fail=lost;
 function node(id=''){return {id,value:'',checked:false,children:[],textContent:'',scrollIntoView(){this.scrolled=true},focus(){this.focused=true},reset(){for(const n of Object.values(nodes))n.value='';},replaceChildren(...items){this.children=items;},append(...items){this.children.push(...items)},checkValidity(){return true;}};}
 const $=id=>nodes[id]??=node(id);
 const db={auth:{onAuthStateChange(){},getSession:async()=>({data:{session:{user:{id:'actor'}}}})},from(table){const filters={};const q={select(){return q},eq(k,v){filters[k]=v;return q},order(){return q},limit(){return q},range(){return q},maybeSingle(){return q},single(){return q},then(resolve){return Promise.resolve({data:table==='scanette_members'?{role:'operator'}:table==='gestion_partners'?(filters.id?partners.find(p=>p.id===filters.id)||null:[...partners]):structuredClone(filters.id?records.find(r=>r.id===filters.id):records)}).then(resolve)}};return q},rpc:async(name,args)=>{calls.push({name,args});if(name==='gestion_save_partner'){const row={id:args.partner_id,name:args.partner_name};partners.push(row);if(fail){fail=false;return {error:{message:'network response lost'}};}return {data:row};}const saved={id:args.session_id,content:args.document,version:1,updated_at:new Date().toISOString()};records=[saved,...records.filter(r=>r.id!==saved.id)];return {data:saved};}};
 const w={addEventListener(){}};vm.runInNewContext(fs.readFileSync('logistics-sessions.js','utf8'),{supabase:{createClient:()=>db},URLSearchParams,location:{search:'',origin:'http://localhost'},document:{getElementById:$,createElement:()=>node()},Option:function(t,v){this.value=v;this.textContent=t},window:w,parent:w,crypto:{randomUUID:()=>`uuid-${++serial}`},structuredClone,Date,Map,setTimeout,localStorage:{},ScanetteCore:{read:()=>({sections:[]})},confirm:()=>true});
 return {$,calls,partners,submit:()=>$('form').onsubmit({preventDefault(){}})};
}
const tick=()=>new Promise(r=>setImmediate(r));
test('Registered supplier selection fills visible name without opening details',async()=>{const a=setup();await tick();a.$('supplier').value='known';a.$('supplier').onchange();assert.equal(a.$('supplierName').value,'IDLP');assert.equal(a.$('supplierDetails').open,false);a.$('orders').value='BL1';await a.submit();assert.equal(a.calls.length,1);assert.equal(a.calls[0].args.document.supplier_id,'known');});
test('Suggestion is saved with receipt in one submit, coordinates optional',async()=>{const a=setup();await tick();a.$('supplier').value='suggestion:Minerva';a.$('supplier').onchange();assert.equal(a.$('supplierName').value,'Minerva');assert.equal(a.$('supplierDetails').open,false);a.$('orders').value='BL2';await a.submit();assert.deepEqual(a.calls.map(c=>c.name),['gestion_save_partner','logistics_save_session']);assert.equal(a.calls[1].args.document.supplier_id,a.calls[0].args.partner_id);});
test('Manual name reuses existing supplier with whitespace and case differences',async()=>{const a=setup();await tick();a.$('supplierName').value=' idlp ';a.$('supplierName').oninput();a.$('orders').value='BL3';await a.submit();assert.equal(a.calls.length,1);assert.equal(a.calls[0].args.document.supplier_id,'known');});
test('Incomplete receipt does not create supplier; changed name cannot keep old selection',async()=>{const a=setup();await tick();a.$('supplier').value='known';a.$('supplier').onchange();a.$('supplierName').value='New supplier';a.$('supplierName').oninput();assert.equal(a.$('supplier').value,'');await a.submit();assert.equal(a.calls.length,0);a.$('orders').value='BL4';await a.submit();assert.equal(a.calls[0].args.partner_name,'New supplier');assert.equal(a.calls[1].args.document.supplier_name,'New supplier');});
test('Lost supplier response retries without duplicate creation and keeps receipt input',async()=>{const a=setup({lost:true});await tick();a.$('supplierName').value='New supplier';a.$('orders').value='BL5';await a.submit();assert.equal(a.$('orders').value,'BL5');assert.equal(a.$('fields').disabled,false);await a.submit();assert.deepEqual(a.calls.map(c=>c.name),['gestion_save_partner','logistics_save_session']);assert.equal(a.partners.filter(p=>p.name==='New supplier').length,1);});

test('Returning starts blank while saved dossiers remain grouped in footer',async()=>{const a=setup({records:[{id:'receipt',version:3,content:{supplier_id:'known',supplier_name:'IDLP',orders:'BL persisted',event_at:'2026-09-23T12:00:00Z',lines:[]}}]});await tick();assert.equal(a.$('orders').value,'');assert.match(a.$('records').children[0].children[1].children[0].textContent,/BL persisted/);});
test('Saving clears typed fields but keeps saved dossier in footer',async()=>{const a=setup();await tick();a.$('supplier').value='known';a.$('supplier').onchange();a.$('orders').value='BL-footer';a.$('label').value='Palette';await a.submit();const card=a.$('records').children[0].children[1];assert.equal(card.className,'receipt-card');assert.match(card.children[0].textContent,/IDLP.*BL-footer/);assert.equal(a.$('orders').value,'');assert.equal(a.$('supplierName').value,'');assert.equal(a.$('label').value,'');assert.ok(a.$('savedDossiers').scrolled);});
test('One date heading groups two dossiers and separate brands retain their quantities',async()=>{const content={supplier_id:'known',supplier_name:'IDLP',orders:'BL-two',event_at:'2026-09-23T12:00:00Z',lines:[{reference:'R',quantity:3}],pointages:[{name:'Bosch',lines:[{reference:'R',quantity:1}]},{name:'Purflux',lines:[{reference:'R',quantity:2}]}]};const a=setup({records:[{id:'r',version:2,content},{id:'r2',version:1,content:{...content,orders:'BL-other'}}]});await tick();assert.equal(a.$('records').children.length,1);const group=a.$('records').children[0];assert.equal(group.children.length,3);assert.match(group.children[0].textContent,/2026/);const card=group.children[1];assert.ok(!card.children[0].textContent.includes('2026'));const details=card.children.filter(n=>n.className==='receipt-pointage');assert.equal(details.length,2);assert.match(details[1].children[1].textContent,/Quantité : 2/);});
test('Delete is reversible and preserves pointage contents on server',async()=>{const content={supplier_id:'known',supplier_name:'IDLP',orders:'BL-trash',event_at:'2026-09-23T12:00:00Z',lines:[{reference:'R',quantity:3}]};const a=setup({records:[{id:'r',version:2,content}]});await tick();let card=a.$('records').children[0].children[1];await card.children.find(n=>n.textContent==='Supprimer le dossier').onclick();assert.ok(a.calls[0].args.document.deleted_at);assert.equal(a.calls[0].args.document.lines[0].quantity,3);assert.match(a.$('records').children[0].textContent,/Aucun dossier/);a.$('showDeleted').checked=true;a.$('showDeleted').onchange();card=a.$('records').children[0].children[1];await card.children.find(n=>n.textContent==='Restaurer le dossier').onclick();assert.equal(a.calls[1].args.document.deleted_at,undefined);assert.equal(a.calls[1].args.document.lines[0].quantity,3);});
test('Saved dossiers footer is below form and has direct navigation from page top',()=>{const html=fs.readFileSync('logistics-sessions.html','utf8');assert.ok(html.indexOf('<footer id="savedDossiers"')>html.indexOf('</form>'));assert.match(html,/href="#savedDossiers"/);});

test('Three consecutive saves create distinct dossiers and all remain visible after reload',async()=>{const a=setup();await tick();for(const order of ['BL-one','BL-two','BL-three']){a.$('supplier').value='known';a.$('supplier').onchange();a.$('orders').value=order;await a.submit();}const saves=a.calls.filter(c=>c.name==='logistics_save_session');assert.equal(new Set(saves.map(c=>c.args.session_id)).size,3);assert.deepEqual(saves.map(c=>c.args.expected_version),[0,0,0]);await a.$('reload').onclick();await tick();const cards=a.$('records').children.flatMap(g=>g.children.filter(n=>n.className==='receipt-card'));assert.equal(cards.length,3);for(const order of ['BL-one','BL-two','BL-three'])assert.ok(cards.some(c=>c.children[0].textContent.includes(order)));});
