(function(root){
'use strict';
const escape=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function cell(v){let s=String(v??'');if(/^[\s\u0000-\u001f]*[=+@-]/u.test(s))s="'"+s;return '"'+s.replace(/"/g,'""')+'"';}
function rows(session){const c=session.content;const meta=[session.id,session.kind,c.event_at,c.supplier_name||'',c.orders||'',(c.employees||[]).join(' / '),c.brand||'',c.range||'',c.zone||''];return (c.lines.length?c.lines:[{}]).map(l=>[...meta,l.reference||'',l.description||'',l.quantity??'',l.location||'']);}
function csv(session){return '\ufeff'+[['Dossier','Type','Date ISO','Fournisseur','Commandes / BL','Employés','Marque','Gamme','Zone','Référence','Désignation','Quantité comptée','Emplacement'],...rows(session)].map(r=>r.map(cell).join(';')).join('\r\n');}
function print(session){const c=session.content;return '<!doctype html><html lang="fr"><meta charset="utf-8"><title>Relevé logistique</title><style>body{font:14px Arial;margin:24px}table{width:100%;border-collapse:collapse}td,th{padding:7px;border:1px solid #aaa;text-align:left}thead{display:table-header-group}tr{break-inside:avoid}@media print{button{display:none}}</style><button onclick="window.print()">Choisir l’imprimante et imprimer</button><h1>'+escape(session.kind==='receipt'?'Réception':'Inventaire')+'</h1><p>'+escape(c.label||session.id)+'</p><p>'+escape(new Date(c.event_at).toLocaleString('fr-FR'))+'</p><p>'+escape(c.supplier_name||'')+' '+escape(c.orders||'')+'</p><p>'+escape((c.employees||[]).join(' / '))+'</p><p>'+escape([c.brand,c.range,c.zone].filter(Boolean).join(' · '))+'</p><table><thead><tr><th>Référence</th><th>Désignation</th><th>Quantité</th><th>Emplacement</th></tr></thead><tbody>'+c.lines.map(l=>'<tr><td>'+escape(l.reference)+'</td><td>'+escape(l.description)+'</td><td>'+escape(l.quantity)+'</td><td>'+escape(l.location)+'</td></tr>').join('')+'</tbody></table><p>Relevé de contrôle — aucun mouvement de stock magasin.</p></html>';}
function importSection(section){return Object.entries(section.items).map(([ref,item])=>({product_id:item.productId||null,reference:item.reference||ref,description:item.description||'',quantity:item.qty,location:''}));}
const api={cell,csv,print,importSection};root.LogisticsCore=api;if(typeof module!=='undefined')module.exports=api;
})(typeof globalThis!=='undefined'?globalThis:this);
