const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs');
function setup({lost=false}={}){
 const nodes={},partners=[{id:'known',name:'IDLP'}],calls=[];let serial=0,fail=lost;
 function node(id=''){return {id,value:'',children:[],textContent:'',reset(){for(const n of Object.values(nodes))n.value='';},replaceChildren(...items){this.children=items;},append(...items){this.children.push(...items)},checkValidity(){return true;}};}
 const $=id=>nodes[id]??=node(id);
 const db={auth:{onAuthStateChange(){},getSession:async()=>({data:{session:{user:{id:'actor'}}}})},from(table){const filters={};const q={select(){return q},eq(k,v){filters[k]=v;return q},order(){return q},limit(){return q},range(){return q},maybeSingle(){return q},then(resolve){return Promise.resolve({data:table==='scanette_members'?{role:'operator'}:table==='gestion_partners'?(filters.id?partners.find(p=>p.id===filters.id)||null:[...partners]):[]}).then(resolve)}};return q},rpc:async(name,args)=>{calls.push({name,args});if(name==='gestion_save_partner'){const row={id:args.partner_id,name:args.partner_name};partners.push(row);if(fail){fail=false;return {error:{message:'network response lost'}};}return {data:row};}return {data:{id:args.session_id,content:args.document,version:1,updated_at:new Date().toISOString()}};}};
 const w={addEventListener(){}};vm.runInNewContext(fs.readFileSync('logistics-sessions.js','utf8'),{supabase:{createClient:()=>db},URLSearchParams,location:{search:'',origin:'http://localhost'},document:{getElementById:$,createElement:()=>node()},Option:function(t,v){this.value=v;this.textContent=t},window:w,parent:w,crypto:{randomUUID:()=>`uuid-${++serial}`},structuredClone,Date,Map,setTimeout,localStorage:{},ScanetteCore:{read:()=>({sections:[]})},confirm:()=>true});
 return {$,calls,partners,submit:()=>$('form').onsubmit({preventDefault(){}})};
}
const tick=()=>new Promise(r=>setImmediate(r));
test('Registered supplier selection fills visible name without opening details',async()=>{const a=setup();await tick();a.$('supplier').value='known';a.$('supplier').onchange();assert.equal(a.$('supplierName').value,'IDLP');assert.equal(a.$('supplierDetails').open,false);a.$('orders').value='BL1';await a.submit();assert.equal(a.calls.length,1);assert.equal(a.calls[0].args.document.supplier_id,'known');});
test('Suggestion is saved with receipt in one submit, coordinates optional',async()=>{const a=setup();await tick();a.$('supplier').value='suggestion:Minerva';a.$('supplier').onchange();assert.equal(a.$('supplierName').value,'Minerva');assert.equal(a.$('supplierDetails').open,false);a.$('orders').value='BL2';await a.submit();assert.deepEqual(a.calls.map(c=>c.name),['gestion_save_partner','logistics_save_session']);assert.equal(a.calls[1].args.document.supplier_id,a.calls[0].args.partner_id);});
test('Manual name reuses existing supplier with whitespace and case differences',async()=>{const a=setup();await tick();a.$('supplierName').value=' idlp ';a.$('supplierName').oninput();a.$('orders').value='BL3';await a.submit();assert.equal(a.calls.length,1);assert.equal(a.calls[0].args.document.supplier_id,'known');});
test('Incomplete receipt does not create supplier; changed name cannot keep old selection',async()=>{const a=setup();await tick();a.$('supplier').value='known';a.$('supplier').onchange();a.$('supplierName').value='New supplier';a.$('supplierName').oninput();assert.equal(a.$('supplier').value,'');await a.submit();assert.equal(a.calls.length,0);a.$('orders').value='BL4';await a.submit();assert.equal(a.calls[0].args.partner_name,'New supplier');assert.equal(a.calls[1].args.document.supplier_name,'New supplier');});
test('Lost supplier response retries without duplicate creation and keeps receipt input',async()=>{const a=setup({lost:true});await tick();a.$('supplierName').value='New supplier';a.$('orders').value='BL5';await a.submit();assert.equal(a.$('orders').value,'BL5');assert.equal(a.$('fields').disabled,false);await a.submit();assert.deepEqual(a.calls.map(c=>c.name),['gestion_save_partner','logistics_save_session']);assert.equal(a.partners.filter(p=>p.name==='New supplier').length,1);});
