'use strict';
const $=id=>document.getElementById(id), key='alcorb-public-partners-v1';
let entries=[], chosen=new Set(), limit=24, available=true;
try {const saved=JSON.parse(localStorage.getItem(key)||'[]'); if(!Array.isArray(saved))throw Error();chosen=new Set(saved.filter(x=>typeof x==='string'&&/^\d{14}$/.test(x)));} catch {available=false;}
const normalize=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
function save(next){try{localStorage.setItem(key,JSON.stringify([...next]));chosen=next;available=true;return true;}catch{$('status').textContent='Enregistrement impossible sur cet appareil. La sélection précédente est conservée.';return false;}}
function render(){const query=normalize($('search').value).trim();const rows=entries.filter(e=>(!$('department').value||e.department===$('department').value)&&(!$('selected').checked||chosen.has(e.siret))&&normalize([e.name,e.city,e.postcode,e.siret].join(' ')).includes(query));$('results').replaceChildren();for(const e of rows.slice(0,limit)){const card=document.createElement('article');const tag=document.createElement('small');tag.textContent=e.city+' · '+e.department;const title=document.createElement('h2');title.textContent=e.name;const address=document.createElement('p');address.textContent=e.address;const id=document.createElement('p');id.textContent='SIRET '+e.siret;const link=document.createElement('a');link.href='https://annuaire-entreprises.data.gouv.fr/etablissement/'+e.siret;link.textContent='Consulter la fiche officielle';link.target='_blank';link.rel='noopener noreferrer';const button=document.createElement('button');button.textContent=chosen.has(e.siret)?'Retirer de ma sélection':'Ajouter à ma sélection';button.setAttribute('aria-pressed',String(chosen.has(e.siret)));button.onclick=()=>{const next=new Set(chosen);next.has(e.siret)?next.delete(e.siret):next.add(e.siret);if(save(next))render();};card.append(tag,title,address,id,link,button);$('results').append(card);}const count=entries.filter(e=>chosen.has(e.siret)).length;$('status').textContent=`${rows.length} établissement(s) trouvé(s) · ${count} sélectionné(s).`+(available?'':' Stockage local indisponible ou invalide ; vérifiez votre sélection.');if(!rows.length){const p=document.createElement('p');p.textContent='Aucun résultat dans cet échantillon. Essayez une autre ville ou retirez un filtre.';$('results').append(p);}$('export').disabled=!count;$('more').hidden=rows.length<=limit;}
for(const id of ['search','department','selected'])$(id).addEventListener('input',()=>{limit=24;render();});$('more').onclick=()=>{limit+=24;render();};
$('export').onclick=()=>{const payload={type:'selection-de-test',exportedAt:new Date().toISOString(),source:'Sirene via API Recherche des entreprises',entries:entries.filter(e=>chosen.has(e.siret))};const url=URL.createObjectURL(new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='partenaires-selection.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
fetch('partners-data.json').then(r=>{if(!r.ok)throw Error();return r.json();}).then(data=>{entries=data.entries;$('provenance').textContent=`${entries.length} établissements · collecte du ${new Date(data.retrievedAt).toLocaleDateString('fr-FR')} · ${data.source}.`;render();}).catch(()=>{$('status').textContent='Le référentiel n’a pas pu être chargé. Vérifiez votre connexion puis rechargez la page.';});
