const test=require('node:test'),a=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),C=require('./preparation-core.js'),P=require('./partner-planning-core.js');
function setup(photoResult,partners=[]){const nodes={},store=new Map();let fail=false;
 const node=()=>({value:'',hidden:false,children:[],dataset:{},checked:false,append(n){this.children.push(n)},replaceChildren(){this.children=[]},removeAttribute(){},reset(){},click(){},focus(){this.focused=(this.focused||0)+1},className:''});const camera={};
 const $=id=>nodes[id]??=(id==='reader'?node():node());
 const products=[{id:'p',reference:'TEST',description:'Article de test',location:'A1'}];
 const calls=[];
 // Shared access facade: no account, no shop argument. A barcode lookup answers with the catalogue fixture.
 const SharedAccess={ACTOR:'shared',adoptLocal(){return null;},call:async(name,args={})=>{calls.push({name,args});
  if(name==='shared_partners')return structuredClone(partners);
  if(name==='shared_products_by_references')return structuredClone(products);
  if(name==='shared_product_lookup')return products.map(p=>({...p,internal_barcode:args.code}));
  throw Error('unexpected '+name);}};
 const c={document:{getElementById:$,createElement:node,addEventListener(){}},window:{addEventListener(){}},parent:{postMessage(){}},location:{origin:'https://test.local'},PreparationPhoto:{cancel(){},read:async()=>photoResult},PreparationOCR:require('./preparation-ocr-core.js'),Preparation:C,PartnerPlanning:P,SharedAccess,localStorage:{getItem:k=>store.get(k)||null,setItem(k,v){if(fail)throw Error('Quota');store.set(k,v)}},setTimeout:f=>f(),setInterval(){},URL:{revokeObjectURL(){},createObjectURL(){return "blob:test"}},confirm:()=>true,crypto:{randomUUID:()=> 'doc'},structuredClone,Date,Intl,navigator:{},Html5Qrcode:class{async start(_device,_config,onCode){camera.onCode=onCode;camera.stopped=false;}async stop(){camera.stopped=true;}clear(){}}};
 vm.runInNewContext(fs.readFileSync('preparation.js','utf8'),c);return {nodes,$,store,products,camera,calls,fail:()=>fail=true};}
const tick=async()=>{for(let i=0;i<8;i++)await new Promise(r=>setImmediate(r));};
async function start(){const s=setup();await tick();s.$('new').onclick();s.$('number').value='TEST-1';s.$('date').value='2026-10-02';s.$('employee').value='Test';s.$('customer').value='Comptoir';s.$('mode').value='pickup';s.$('productQuery').value='TEST';await s.$('find').onclick();s.$('products').children[0].onclick();s.$('reviewed').checked=true;s.$('editor').onsubmit({preventDefault(){}});return s;}
test('pickup BL saves, scan checks a unit, finish persists and locks further scans',async()=>{const s=await start();a.match(s.$('departure').textContent,/Retrait au comptoir/);a.equal(s.$('finish').disabled,true);s.$('code').value='123';s.$('scanForm').onsubmit({preventDefault(){}});await tick();a.equal(s.$('finish').disabled,false);await s.$('finish').onclick();a.equal(s.$('cameraButton').disabled,true);const saved=JSON.parse([...s.store.values()][0]);a.equal(saved[0].lines[0].count,1);a.ok(saved[0].completedAt);});
test('storage failure leaves previous counted quantity intact',async()=>{const s=await start();s.fail();s.$('code').value='123';s.$('scanForm').onsubmit({preventDefault(){}});await tick();a.match(s.$('feedback').textContent,/Quota/);a.equal(JSON.parse([...s.store.values()][0])[0].lines[0].count,0);a.equal(s.$('finish').disabled,true);});
test('opens without account and calls only shared functions, never with a shop',async()=>{const s=await start();a.equal(s.$('workspace').hidden,false);a.ok(s.calls.length>=2);for(const c of s.calls){a.match(c.name,/^shared_/);a.equal(/workspace|shop/.test(JSON.stringify(c.args)),false);}a.ok([...s.store.keys()][0].endsWith(':shared'));});

test('photo builds recognized lines automatically and blocks missing catalogue matches',async()=>{const s=setup({header:{number:'PHOTO',date:'2026-10-02',pickup:true,pageVerified:true},lines:[{reference:'TEST',expected:4,uncertain:false},{reference:'UNKNOWN',expected:1,uncertain:true}]});await tick();s.$('new').onclick();s.$('photo').files=[{type:'image/jpeg',size:1000}];await s.$('photo').onchange();a.equal(s.$('number').value,'PHOTO');a.equal(s.$('draftLines').children.length,1);a.equal(s.$('photoRows').children.length,1);a.equal(s.$('begin').disabled,true);s.$('reviewed').checked=true;s.$('editor').onsubmit({preventDefault(){}});a.equal(s.store.size,0);});

test('BL header links unique client; the preparer is typed, never the seller',async()=>{const s=setup({header:{number:'AUTO',date:'2026-10-02',customerCode:'12',customer:'Client OCR',pickup:false},lines:[{reference:'TEST',expected:1}]},[{id:'garage',name:'Garage réel',details:{code:'12'}}]);await tick();s.$('new').onclick();a.equal(s.$('employee').value,'','no account, so no preparer name is guessed');s.$('photo').files=[{type:'image/jpeg',size:1000}];await s.$('photo').onchange();a.equal(s.$('garage').value,'garage');a.equal(s.$('customer').value,'Garage réel');a.equal(s.$('mode').value,'');});

const submit=async(s,code)=>{s.$('code').value=code;s.$('scanForm').onsubmit({preventDefault(){}});await tick();};
test('a refused code empties the reader field, keeps focus and never sticks to the next scan',async()=>{const s=await start(),known=s.products.splice(0);
 await submit(s,'9999');a.match(s.$('feedback').textContent,/Code inconnu/);a.equal(s.$('feedback').className,'error');a.equal(s.$('code').value,'');a.ok(s.$('code').focused>=1);a.equal(JSON.parse([...s.store.values()][0])[0].lines[0].count,0);
 s.products.push(...known);await submit(s,'123');a.match(s.$('feedback').textContent,/une pièce contrôlée/);a.equal(s.$('code').value,'');a.equal(JSON.parse([...s.store.values()][0])[0].lines[0].count,1);});
test('a refused code leaves the camera open; a failed save closes it',async()=>{const s=await start();await s.$('cameraButton').onclick();a.equal(s.$('camera').hidden,false);const known=s.products.splice(0);
 await submit(s,'9999');a.equal(s.$('camera').hidden,false);a.equal(s.camera.stopped,false);
 await s.camera.onCode('8888');await tick();a.match(s.$('feedback').textContent,/Code inconnu/);a.equal(s.$('camera').hidden,false);a.equal(s.camera.stopped,false);
 s.products.push(...known);s.fail();await submit(s,'123');a.match(s.$('feedback').textContent,/Quota/);a.equal(s.$('camera').hidden,true);a.equal(s.camera.stopped,true);});
test('two reader scans sent before the first answer are both controlled, in order',async()=>{const s=await start();s.$('code').value='123';s.$('scanForm').onsubmit({preventDefault(){}});a.equal(s.$('code').value,'');s.$('code').value='123';s.$('scanForm').onsubmit({preventDefault(){}});await tick();await tick();
 a.match(s.$('feedback').textContent,/Quantité déjà complète/);a.equal(JSON.parse([...s.store.values()][0])[0].lines[0].count,1);a.equal(s.$('code').value,'');});
