/* OCR on the device; the document image is never sent to an OCR service. */
(function(g){'use strict';let worker=null,generation=0;
async function cancel(){generation++;const old=worker;worker=null;if(old)try{await old.terminate();}catch{}}
async function read(file,progress){await cancel();const ticket=generation,live=()=>{if(ticket!==generation)throw Error('Lecture annulée.');};let canvas=null,crop=null;
try{progress('Préparation de la photo…');const image=await createImageBitmap(file);live();try{if(image.width<600||image.height<600)throw Error('Photo trop petite. Reprenez le BL de plus près, bien net.');canvas=document.createElement('canvas');const scale=Math.min(3,2160/image.width,4096/image.height);canvas.width=Math.round(image.width*scale);canvas.height=Math.round(image.height*scale);const ctx=canvas.getContext('2d',{willReadFrequently:true});ctx.drawImage(image,0,0,canvas.width,canvas.height);const pixels=ctx.getImageData(0,0,canvas.width,canvas.height),hist=new Uint32Array(256);for(let i=0;i<pixels.data.length;i+=4){const v=Math.round(.299*pixels.data[i]+.587*pixels.data[i+1]+.114*pixels.data[i+2]);pixels.data[i]=pixels.data[i+1]=pixels.data[i+2]=v;hist[v]++;}const count=canvas.width*canvas.height;let lo=0,hi=255,n=0;while(lo<254&&n<count*.01)n+=hist[lo++];n=0;while(hi>lo+1&&n<count*.01)n+=hist[hi--];for(let i=0;i<pixels.data.length;i+=4){const v=Math.max(0,Math.min(255,(pixels.data[i]-lo)*255/(hi-lo)));pixels.data[i]=pixels.data[i+1]=pixels.data[i+2]=v;}ctx.putImageData(pixels,0,0);}finally{image.close();}
live();let phase='Lecture du BL';const w=await Tesseract.createWorker('eng',1,{logger:m=>{if(ticket===generation&&m.status==='recognizing text')progress(phase+' · '+Math.round(m.progress*100)+' %');}});if(ticket!==generation){await w.terminate();live();}worker=w;await w.setParameters({tessedit_pageseg_mode:'11',preserve_interword_spaces:'1'});const first=(await w.recognize(canvas,{}, {text:true,blocks:true})).data;live();const O=PreparationOCR,header=O.header(first);if(header.multiplePages)throw Error('BL de plusieurs pages : cette première lecture ne suffit pas. Ne commencez pas une préparation partielle.');const box=O.layout(first),initial=O.rows(first,box);phase='Vérification des lignes';const left=Math.floor(box.left),top=Math.floor(box.top);crop=document.createElement('canvas');crop.width=Math.min(canvas.width-left,Math.ceil(box.qtyEnd+50-left));crop.height=Math.floor(box.bottom-top);if(left<0||top<0||crop.width<1||crop.height<1)throw Error('Cadrage du tableau non reconnu.');crop.getContext('2d').drawImage(canvas,left,top,crop.width,crop.height,0,0,crop.width,crop.height);await w.setParameters({tessedit_pageseg_mode:'6'});const second=(await w.recognize(crop,{}, {text:true,blocks:true})).data;live();const rows=O.rows(second,{...box,left:0,top:0,refEnd:box.refEnd-left,qtyStart:box.qtyStart-left,qtyEnd:box.qtyEnd-left,bottom:crop.height});return {header,lines:O.merge(initial,rows)};
}finally{if(canvas)canvas.width=canvas.height=1;if(crop)crop.width=crop.height=1;if(ticket===generation){const old=worker;worker=null;if(old)try{await old.terminate();}catch{}}}}
g.PreparationPhoto={read,cancel};
})(globalThis);
