const test=require('node:test'),a=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),C=require('./preparation-core.js'),P=require('./partner-planning-core.js');
function setup(photoResult){const nodes={},store=new Map();let callback,fail=false;
 const node=()=>({value:'',hidden:false,children:[],dataset:{},checked:false,append(n){this.children.push(n)},replaceChildren(){this.children=[]},removeAttribute(){},reset(){},click(){},className:''});
 const $=id=>nodes[id]??=(id==='reader'?node():node());
 const products=[{id:'p',reference:'TEST',description:'Article de test',location:'A1'}];
 const db={from(table){const q={select(){return this},eq(k,v){this[k]=v;return this},order(){return this},or(){return this},in(){return this},maybeSingle(){return Promise.resolve({data:{role:'operator'}})},range(){return Promise.resolve({data:[]})},limit(){return Promise.resolve({data:products})}};return q;},auth:{onAuthStateChange(cb){callback=cb},getSession:async()=>({data:{session:{user:{id:'tester'}}}})}};
 const c={document:{getElementById:$,createElement:node,addEventListener(){}},window:{addEventListener(){}},parent:{postMessage(){}},location:{origin:'https://test.local'},PreparationPhoto:{cancel(){},read:async()=>photoResult},Preparation:C,PartnerPlanning:P,supabase:{createClient:()=>db},localStorage:{getItem:k=>store.get(k)||null,setItem(k,v){if(fail)throw Error('Quota');store.set(k,v)}},setTimeout:f=>f(),setInterval(){},URL:{revokeObjectURL(){},createObjectURL(){return "blob:test"}},confirm:()=>true,crypto:{randomUUID:()=> 'doc'},structuredClone,Date,Intl,navigator:{},Html5Qrcode:class{}};
 vm.runInNewContext(fs.readFileSync('preparation.js','utf8'),c);return {nodes,$,store,auth:s=>callback('test',s),fail:()=>fail=true};}
const tick=async()=>{for(let i=0;i<8;i++)await new Promise(r=>setImmediate(r));};
async function start(){const s=setup();await tick();s.$('new').onclick();s.$('number').value='TEST-1';s.$('date').value='2026-10-02';s.$('employee').value='Test';s.$('customer').value='Comptoir';s.$('mode').value='pickup';s.$('productQuery').value='TEST';await s.$('find').onclick();s.$('products').children[0].onclick();s.$('reviewed').checked=true;s.$('editor').onsubmit({preventDefault(){}});return s;}
test('pickup BL saves, scan checks a unit, finish persists and locks further scans',async()=>{const s=await start();a.match(s.$('departure').textContent,/Retrait au comptoir/);a.equal(s.$('finish').disabled,true);s.$('code').value='123';s.$('scanForm').onsubmit({preventDefault(){}});await tick();a.equal(s.$('finish').disabled,false);await s.$('finish').onclick();a.equal(s.$('cameraButton').disabled,true);const saved=JSON.parse([...s.store.values()][0]);a.equal(saved[0].lines[0].count,1);a.ok(saved[0].completedAt);});
test('storage failure leaves previous counted quantity intact',async()=>{const s=await start();s.fail();s.$('code').value='123';s.$('scanForm').onsubmit({preventDefault(){}});await tick();a.match(s.$('feedback').textContent,/Quota/);a.equal(JSON.parse([...s.store.values()][0])[0].lines[0].count,0);a.equal(s.$('finish').disabled,true);});
test('logout removes the displayed private preparation',async()=>{const s=await start();s.auth(null);await tick();a.equal(s.$('workspace').hidden,true);a.equal(s.$('lines').children.length,0);});

test('photo builds recognized lines automatically and blocks missing catalogue matches',async()=>{const s=setup({header:{number:'PHOTO',date:'2026-10-02',pickup:true,pageVerified:true},lines:[{reference:'TEST',expected:4,uncertain:false},{reference:'UNKNOWN',expected:1,uncertain:true}]});await tick();s.$('new').onclick();s.$('photo').files=[{type:'image/jpeg',size:1000}];await s.$('photo').onchange();a.equal(s.$('number').value,'PHOTO');a.equal(s.$('draftLines').children.length,1);a.equal(s.$('photoRows').children.length,1);a.equal(s.$('begin').disabled,true);s.$('reviewed').checked=true;s.$('editor').onsubmit({preventDefault(){}});a.equal(s.store.size,0);});
