(()=>{'use strict';
const $=id=>document.getElementById(id),C=Preparation,P=PartnerPlanning,shop='8770297c-cadb-4cc6-8b93-55a0f9bd154e';
const db=supabase.createClient('https://pryocchvwmnuoidtitow.supabase.co','sb_publishable_AQ9cr2Z7Kr6EAravVOgB9Q_Z5Mx2yOZ');
let actor=undefined,epoch=0,allowed=false,documents=[],partners=[],draft=[],current=null,scanner=null,starting=false,scanning=false,processing=false,lastScan=0,photoUrl=null,searchId=0,serialized='[]',conflict=false;
let photoJob=0,photoBusy=false,photoBlocked=false,photoEntries=[];
const check=r=>{if(r.error)throw Error(r.error.message);return r.data;};
function message(s,error=false){$('status').textContent=s;$('status').className=error?'error':'';}
function dirty(v){if(parent!==window)parent.postMessage({type:'alcorb-dirty',dirty:v},location.origin);}
function photoClear(){photoJob++;PreparationPhoto.cancel();photoBusy=false;photoBlocked=false;photoEntries=[];$('photoRows').replaceChildren();$('photoStatus').textContent='';$('begin').disabled=false;if(photoUrl)URL.revokeObjectURL(photoUrl);photoUrl=null;$('preview').removeAttribute('src');$('preview').hidden=true;$('photo').value='';}
function commit(next){if(!allowed||!actor||conflict)throw Error('Enregistrement indisponible. Rechargez cette section.');const k=C.key(shop,actor),stored=localStorage.getItem(k)||'[]';if(stored!==serialized){conflict=true;throw Error('Un autre onglet a modifié ces dossiers. Rechargez avant de continuer.');}C.save(localStorage,k,next);serialized=JSON.stringify(next);documents=next;}
function replace(next){commit(documents.map(d=>d.id===next.id?next:d));current=next;paint();}
function node(tag,text,parent){const n=document.createElement(tag);n.textContent=text;parent?.append(n);return n;}
function board(){$('documents').replaceChildren();for(const d of [...documents].reverse()){const b=node('button','BL '+d.number+' · '+d.customer+' · '+(d.completedAt?'Préparé':'En cours'),$('documents'));b.onclick=()=>open(d);}if(!documents.length)node('p','Aucun BL enregistré sur cet appareil pour votre compte.',$('documents'));}
function departure(){if(!current)return;if(current.mode==='pickup'){$('departure').textContent='Retrait au comptoir · pris magasin';return;}const p=partners.find(p=>p.id===current.partnerId),s=p?P.next(p)[0]:null;$('departure').textContent=s?s.carrier+' · '+s.time+'\n'+P.label(s)+(s.place?'\nÀ déposer : '+s.place:'')+(s.cutoff?'\nPréparer avant '+s.cutoff:''):'Horaire non renseigné pour ce garage — consulter la logistique.';}
function paint(){if(!current)return;$('title').textContent='BL '+current.number+' · '+current.customer;$('meta').textContent=current.date+' · Préparateur : '+current.employee;$('lines').replaceChildren();let done=0,total=0;for(const l of current.lines){done+=l.count;total+=l.expected;const row=node('article','',$('lines'));row.className=l.count===l.expected?'done':'';node('strong',l.reference,row);node('p',l.description,row);node('small','Emplacement : '+(l.location||'non renseigné'),row);node('div',l.count+' / '+l.expected+' pièce(s)',row).className='quantity';}$('progress').textContent=done+' / '+total+' pièces contrôlées'+(current.completedAt?' · Préparé le '+new Date(current.completedAt).toLocaleString('fr-FR'):'');$('finish').disabled=!!current.completedAt||done!==total||conflict;$('cameraButton').disabled=$('undo').disabled=!!current.completedAt||conflict;$('scanForm').hidden=!!current.completedAt;departure();}
function open(d){current=d;$('start').hidden=true;$('editor').hidden=true;$('work').hidden=false;$('feedback').textContent='';paint();}
function garageOptions(){const selected=$('garage').value;$('garage').replaceChildren();const empty=node('option','Choisir un garage',$('garage'));empty.value='';for(const p of partners.filter(p=>p.id===selected||P.matches(p,$('garageSearch').value))){const o=node('option',p.name+(p.details?.code?' · '+p.details.code:''),$('garage'));o.value=p.id;}$('garage').value=selected;}
function paintDraft(){$('draftLines').replaceChildren();for(const l of draft){const r=node('article',l.reference+' · '+l.description+(l.ocrReview?' · Lecture à vérifier':''),$('draftLines'));node('small','Emplacement : '+(l.location||'non renseigné'),r);const label=node('label','Quantité attendue',r),n=document.createElement('input');n.type='number';n.min='1';n.max='10000';n.step='1';n.required=true;n.value=l.expected;n.oninput=()=>{l.expected=Number(n.value);$('reviewed').checked=false;};label.append(n);const b=node('button','Retirer',r);b.type='button';b.onclick=()=>{draft=draft.filter(x=>x!==l);$('reviewed').checked=false;paintDraft();};}}
$('new').onclick=()=>{if(!allowed)return;draft=[];current=null;$('editor').reset();photoClear();$('date').value=new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Paris'}).format(new Date());$('start').hidden=true;$('editor').hidden=false;$('work').hidden=true;$('products').replaceChildren();garageOptions();paintDraft();dirty(true);};
$('editor').oninput=()=>{$('reviewed').checked=false;};
$('reviewed').oninput=e=>e.stopPropagation();
$('cancel').onclick=()=>{photoClear();searchId++;$('editor').hidden=true;$('start').hidden=false;dirty(false);};
function unresolvedPhotos(){return photoBlocked||photoBusy||photoEntries.some(e=>!e.resolved);}
function photoRows(){
 $('photoRows').replaceChildren();$('begin').disabled=unresolvedPhotos();
 for(const entry of photoEntries.filter(e=>!e.resolved)){
  const box=node('article','Ligne à vérifier : '+entry.description,$('photoRows'));box.className='error';
  const refLabel=node('label','Référence lue',box),ref=document.createElement('input');ref.value=entry.reference;ref.maxLength=120;refLabel.append(ref);
  const qtyLabel=node('label','Quantité LIVR',box),qty=document.createElement('input');qty.type='number';qty.min=1;qty.max=10000;qty.step=1;qty.value=entry.expected||'';qtyLabel.append(qty);
  const b=node('button','Vérifier dans le catalogue',box);b.type='button';const note=node('p','Référence non reconnue, ambiguë ou quantité illisible. Aucune ligne ne sera ignorée.',box);
  b.onclick=async()=>{const token=epoch,job=photoJob,n=Number(qty.value),q=ref.value.trim().toUpperCase();if(!q||!Number.isSafeInteger(n)||n<1||n>10000){note.textContent='Corrigez la référence et la quantité entière positive.';return;}b.disabled=true;try{const matches=check(await db.from('scanette_products').select('id,reference,description,location').eq('workspace_id',shop).eq('reference',q).limit(30));if(token!==epoch||job!==photoJob)return;if(matches.length!==1){note.textContent=matches.length?'Plusieurs fiches correspondent. Faites corriger la fiche catalogue avant de continuer.':'Référence absente du catalogue : vérifiez la lecture ou ajoutez sa fiche avant de continuer.';return;}entry.reference=q;entry.expected=n;appendPhoto(entry,matches[0]);photoRows();paintDraft();}catch{if(token===epoch&&job===photoJob)note.textContent='Catalogue indisponible. Réessayez.';}finally{b.disabled=false;}};
 }
}
function appendPhoto(entry,p){const prior=draft.find(l=>l.productId===p.id);if(prior){prior.expected+=entry.expected;prior.ocrReview=true;}else draft.push({productId:p.id,reference:p.reference,description:p.description||entry.description,location:p.location||'',expected:entry.expected,count:0,ocrReview:entry.uncertain});entry.resolved=true;$('reviewed').checked=false;}
$('photo').onchange=async()=>{
 const f=$('photo').files[0];if(!f||!allowed)return;if(!f.type.startsWith('image/')||f.size>15000000){message('Choisissez une photo de moins de 15 Mo.',true);return;}
 if(draft.length&&!confirm('Remplacer les articles saisis par la lecture de cette photo ?'))return;
 await PreparationPhoto.cancel();const job=++photoJob,token=epoch;photoBusy=true;photoBlocked=true;photoEntries=[];draft=[];paintDraft();photoRows();$('reviewed').checked=false;
 if(photoUrl)URL.revokeObjectURL(photoUrl);photoUrl=URL.createObjectURL(f);$('preview').src=photoUrl;$('preview').hidden=false;
 try{const result=await PreparationPhoto.read(f,t=>{if(job===photoJob&&token===epoch)$('photoStatus').textContent=t;});if(job!==photoJob||token!==epoch)return;
  $('number').value=result.header.number;$('date').value=result.header.date;$('mode').value=result.header.pickup?'pickup':'delivery';
  photoEntries=result.lines.map(l=>({...l,resolved:false}));const refs=[...new Set(photoEntries.map(l=>l.reference))],products=[];
  for(let i=0;i<refs.length;i+=50){products.push(...check(await db.from('scanette_products').select('id,reference,description,location').eq('workspace_id',shop).in('reference',refs.slice(i,i+50)).limit(3000)));if(job!==photoJob||token!==epoch)return;}
  for(const entry of photoEntries){const matches=products.filter(p=>p.reference===entry.reference);if(matches.length===1&&entry.expected)appendPhoto(entry,matches[0]);}
  photoBlocked=false;$('photoStatus').textContent=photoEntries.length+' ligne(s) lue(s). Vérifiez toutes les lignes et quantités avec le papier'+(!result.header.pageVerified?' ; vérifiez aussi qu’il s’agit du BL complet, sur une seule page.':'.')+' Les emplacements proviennent du catalogue.';paintDraft();
 }catch(e){if(job===photoJob&&token===epoch){photoBlocked=true;$('photoStatus').textContent='Lecture non validée : '+e.message+' Reprenez une photo nette du BL entier.';}}
 finally{if(job===photoJob&&token===epoch){photoBusy=false;photoRows();}}
};
$('garageSearch').oninput=garageOptions;$('garage').onchange=()=>{const p=partners.find(p=>p.id===$('garage').value);if(p)$('customer').value=p.name;};
$('find').onclick=async()=>{const q=$('productQuery').value.trim(),ticket=epoch,request=++searchId;if(!allowed||!q)return;$('products').replaceChildren();try{const rows=check(await db.from('scanette_products').select('id,reference,description,location').eq('workspace_id',shop).eq('reference',q.toUpperCase()).limit(30));if(ticket!==epoch||request!==searchId)return;if(!rows.length){node('p','Référence introuvable. Ajoutez ou corrigez sa fiche catalogue avant de préparer ce BL.',$('products'));return;}for(const p of rows){const b=node('button',p.reference+' · '+p.description+' · '+(p.location||'Emplacement non renseigné'),$('products'));b.type='button';b.onclick=()=>{if(draft.some(l=>l.productId===p.id)){message('Pièce déjà présente : ajustez sa quantité.',true);return;}draft.push({productId:p.id,reference:p.reference,description:p.description||'',location:p.location||'',expected:1,count:0});$('reviewed').checked=false;paintDraft();$('products').replaceChildren();$('productQuery').value='';};}}catch{if(ticket===epoch)message('Catalogue indisponible. Réessayez.',true);}};
$('editor').onsubmit=e=>{e.preventDefault();try{if(unresolvedPhotos())throw Error('Terminez la vérification de toutes les lignes de la photo.');if(!$('reviewed').checked)throw Error('Vérifiez le relevé avec le BL.');const p=partners.find(p=>p.id===$('garage').value);if($('mode').value==='delivery'&&!p)throw Error('Choisissez le garage pour relier ses départs.');const d={format:1,id:crypto.randomUUID(),number:$('number').value.trim(),date:$('date').value,employee:$('employee').value.trim(),customer:$('mode').value==='delivery'?p.name:$('customer').value.trim(),mode:$('mode').value,partnerId:p?.id||null,lines:structuredClone(draft),events:[],createdAt:new Date().toISOString(),completedAt:null};C.validate(d);if(documents.some(x=>x.number===d.number&&x.date===d.date))throw Error('Ce BL est déjà enregistré pour cette date. Reprenez-le dans la liste.');commit([...documents,d]);dirty(false);photoClear();open(d);message('BL enregistré sur cet appareil. Scannez une unité à la fois.');}catch(e){message(e.message,true);}};
async function detected(code,fromCamera=false){if(!current||!allowed||processing||current.completedAt||conflict)return;if(fromCamera&&(!scanning||Date.now()-lastScan<2000))return;processing=true;lastScan=Date.now();const ticket=epoch,id=current.id;try{const quoted='"'+String(code).trim().replace(/\\/g,'\\\\').replace(/"/g,'\\"')+'"';if(!String(code).trim()||String(code).length>256)throw Error('Code invalide.');const products=check(await db.from('scanette_products').select('id').eq('workspace_id',shop).or('internal_barcode.eq.'+quoted+',manufacturer_barcode.eq.'+quoted).limit(3));if(ticket!==epoch||current?.id!==id)return;const next=C.scan(current,products,code,new Date().toISOString());replace(next);$('feedback').className='';$('feedback').textContent='✓ '+next.lines.find(l=>l.productId===products[0].id).reference+' · une pièce contrôlée';$('code').value='';navigator.vibrate?.(60);}catch(e){if(ticket===epoch){$('feedback').className='error';$('feedback').textContent=e.message;await stop();}}finally{processing=false;}}
$('scanForm').onsubmit=e=>{e.preventDefault();detected($('code').value);};
async function stop(){scanning=false;$('camera').hidden=true;const old=scanner;scanner=null;if(old)try{await old.stop();old.clear();}catch{}}
$('cameraButton').onclick=async()=>{if(starting||scanner||!allowed||!current||current.completedAt)return;starting=true;const ticket=epoch;const s=new Html5Qrcode('reader');scanner=s;scanning=true;$('camera').hidden=false;try{await s.start({facingMode:'environment'},{fps:10,aspectRatio:16/9,qrbox:(w,h)=>({width:Math.floor(w*.85),height:Math.floor(Math.min(110,h*.65))})},code=>detected(code,true),()=>{});if(ticket!==epoch||!scanning){try{await s.stop();s.clear();}catch{}}}catch{await stop();message('Caméra indisponible. Vérifiez son autorisation ou utilisez une douchette.',true);}finally{starting=false;}};
$('stop').onclick=stop;$('back').onclick=async()=>{await stop();current=null;$('work').hidden=true;$('start').hidden=false;board();};
$('undo').onclick=()=>{if(processing)return;try{replace(C.undo(current,new Date().toISOString()));$('feedback').textContent='Dernier scan annulé.';}catch(e){message(e.message,true);}};
$('finish').onclick=async()=>{if(processing)return;try{replace(C.complete(current,new Date().toISOString()));await stop();message('Préparation complète enregistrée sur cet appareil.');}catch(e){message(e.message,true);}};
$('export').onclick=()=>{if(!current)return;const u=URL.createObjectURL(new Blob([JSON.stringify({format:'alcorb-preparation-export-v1',document:current},null,2)],{type:'application/json'})),a=document.createElement('a');a.href=u;a.download='preparation-'+current.id+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);};
async function enter(s){const id=s?.user?.id||null;if(id===actor)return;epoch++;const ticket=epoch;actor=id;allowed=false;current=null;documents=[];partners=[];draft=[];conflict=false;stop();photoClear();dirty(false);$('workspace').hidden=true;$('documents').replaceChildren();$('lines').replaceChildren();$('editor').reset();if(!id){message('Connectez-vous depuis l’application.');return;}try{const m=check(await db.from('scanette_members').select('role').eq('workspace_id',shop).eq('user_id',id).maybeSingle());if(ticket!==epoch)return;if(!m||!['admin','operator'].includes(m.role))throw Error('Un accès opérateur est nécessaire pour préparer les commandes.');let all=[];for(let from=0;;from+=500){const rows=check(await db.from('gestion_partners').select('*').eq('workspace_id',shop).eq('kind','client').order('id').range(from,from+499));if(ticket!==epoch)return;all.push(...rows);if(rows.length<500)break;}partners=P.active(all);serialized=localStorage.getItem(C.key(shop,id))||'[]';const saved=JSON.parse(serialized);if(!Array.isArray(saved))throw Error('Archive locale illisible. Elle a été conservée sans modification.');saved.forEach(C.validate);documents=saved;allowed=true;$('workspace').hidden=false;$('editor').hidden=$('work').hidden=true;$('start').hidden=false;board();message('Prêt. Vos dossiers sont conservés sur cet appareil.');}catch(e){if(ticket===epoch)message(e.message,true);}}
window.addEventListener('storage',e=>{if(actor&&e.key===C.key(shop,actor)&&e.newValue!==serialized){conflict=true;stop();message('Dossiers modifiés dans un autre onglet. Rechargez avant de continuer.',true);paint();}});
document.addEventListener('visibilitychange',()=>{if(document.hidden)stop();});window.addEventListener('pagehide',stop);window.addEventListener('beforeunload',e=>{if(!$('editor').hidden){e.preventDefault();e.returnValue='';}});setInterval(departure,1000);
db.auth.onAuthStateChange((_e,s)=>setTimeout(()=>enter(s),0));db.auth.getSession().then(r=>enter(r.data.session)).catch(()=>message('Connexion indisponible.',true));
})();
