const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),C=require('./receipt-link-core.js'),L=require('./logistics-core.js');
function setup({lost=false,archiveFail=false,editDuringSave=false}={}){
 const nodes={},store=new Map();let calls=0,failed=false;const section={id:'section',name:'APO',items:{R:{qty:2,prix:null}}};let record={id:'receipt',version:1,content:{supplier_name:'APO',orders:'BL1',lines:[]}};
 const node=()=>({value:'',hidden:false,textContent:'',after(){},replaceChildren(){},append(){}}),$=id=>nodes[id]??=node();
 const q={select(){return q},eq(){return q},is(){return q},order(){return q},limit:async()=>({data:[structuredClone(record)]}),single:async()=>({data:structuredClone(record)})};
 const ctx={URLSearchParams,location:{search:'?receipt=receipt'},document:{getElementById:$,createElement:node},Option:function(){},currentUserId:'u',sessionEpoch:1,storageReady:true,sections:[section],crypto:{randomUUID:()=> 'next'},structuredClone,Date,JSON,ReceiptLinkCore:C,LogisticsCore:L,localStorage:{getItem:k=>store.get(k)||null,setItem(k,v){if(archiveFail)throw Error('storage full');store.set(k,v)}},snapshot:()=>({sections:ctx.sections}),ScanetteCore:{write(s,u,v){store.set('active',JSON.stringify(v))}},storageError(){},scanHistory:[],lastAction:{},selected:{},render(){},updateCurSection(){},updateLastScanBar(){},save(){},confirm:()=>true,supaClient:{auth:{onAuthStateChange(){}},from:()=>q,rpc:async(name,args)=>{calls++;record={id:'receipt',version:2,content:args.document};if(editDuringSave)ctx.sections[0].items.R.qty++;if(lost&&!failed){failed=true;return {error:{message:'lost'}};}return {data:record};}}};
 vm.runInNewContext(fs.readFileSync('receipt-link.js','utf8'),ctx);$('receiptTarget').value='receipt';$('receiptPointage').value='section';$('receiptBatchName').value='Bosch';return {ctx,$,store,send:()=>$('receiptSend').onclick(),get calls(){return calls},get record(){return record}};
}
test('Confirmed transfer keeps brand in shared receipt and starts empty active pointage',async()=>{const a=setup();await a.send();assert.equal(a.record.content.pointages[0].name,'Bosch');assert.equal(a.record.content.lines[0].quantity,2);assert.equal(a.ctx.sections[0].id,'next');assert.equal(Object.keys(a.ctx.sections[0].items).length,0);assert.ok(a.store.has('scanette_receipt_archive_v1:u'));assert.equal(JSON.parse(a.store.get('active')).sections[0].id,'next');});
test('Lost response preserves scans; retry confirms same receipt without a second write',async()=>{const a=setup({lost:true});await a.send();assert.equal(a.ctx.sections[0].items.R.qty,2);await a.send();assert.equal(a.calls,1);assert.equal(a.ctx.sections[0].id,'next');assert.equal(a.record.content.lines[0].quantity,2);});
test('Local storage failure never empties work even when server saved',async()=>{const a=setup({archiveFail:true});await a.send();assert.equal(a.ctx.sections[0].items.R.qty,2);assert.match(a.$('receiptMessage').textContent,/réception est enregistrée/);});
test('Concurrent new scan is retained after the old snapshot is transferred',async()=>{const a=setup({editDuringSave:true});await a.send();assert.equal(a.ctx.sections[0].items.R.qty,3);assert.equal(a.record.content.lines[0].quantity,2);assert.match(a.$('receiptMessage').textContent,/changé/);});

test('Adding a pointage from a saved dossier preselects that reception',async()=>{const a=setup();await a.$('receiptChoose').onclick();assert.equal(a.$('receiptTarget').value,'receipt');assert.equal(a.$('receiptPointage').value,'section');assert.equal(a.$('receiptChoice').hidden,false);});
