const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),R=require('./reference-core.js');
const json=name=>JSON.parse(fs.readFileSync(name,'utf8').replace(/^\uFEFF/,''));
const sirene=json('partners-data.json'),osm=json('partners-osm-data.json'),products=json('products-open-data.json'),official=json('suppliers-official-data.json');
assert.ok(sirene.entries.length>10000);assert.equal(new Set(sirene.entries.map(e=>e.siret)).size,sirene.entries.length);
for(const e of sirene.entries){assert.match(e.siret,/^\d{14}$/);assert.ok(e.name&&e.address&&e.city);assert.equal(e.kind,e.activity==='45.20A'?'garage':'supplier');assert.ok(e.source.startsWith('https://recherche-entreprises.api.gouv.fr/'));for(const forbidden of ['dirigeants','finances','date_naissance','beneficiaires_effectifs'])assert.equal(e[forbidden],undefined);}
assert.equal(new Set(products.entries.map(e=>e.gtin)).size,products.entries.length);assert.ok(products.entries.every(p=>R.validGTIN(p.gtin)&&p.source.startsWith('https://world.openproductsfacts.org/product/')));assert.ok(!products.entries.some(p=>p.gtin==='8056269636179'));
const all=R.combine(sirene.entries,osm.entries,official.entries);assert.equal(new Set(all.map(e=>e.id)).size,all.length);assert.ok(R.filter(all,{query:'Bayonne'}).length>30);assert.equal(R.filter(all,{query:'Bordeaux'}).filter(e=>e.city==='BORDEAUX').length,0);assert.ok(R.filter(all,{query:'bilstein',kind:'supplier',area:''}).length);assert.ok(R.filter(all,{query:'sidat',kind:'supplier',area:''}).length>=2);assert.equal(R.web('javascript:alert(1)'), '');assert.equal(R.web('data:text/html,bad'),'');assert.equal(R.escape('<img onerror="x">'),'&lt;img onerror=&quot;x&quot;&gt;');
const merged=R.combine([{siret:'12345678901234',name:'A',city:'Bayonne',kind:'garage',department:'64'}],[{siret:'12345678901234',id:'osm-node-1',name:'A',phone:'123',source:'https://www.openstreetmap.org/node/1'}]);assert.equal(merged.length,1);assert.equal(merged[0].phone,'123');assert.equal(merged[0].sources.length,2);
const choices=[];assert.equal(R.attach(choices,all[0],'client'),true);assert.equal(R.attach(choices,all[0],'client'),false);assert.equal(choices.length,1);R.attach(choices,all[0],'supplier');assert.deepEqual(choices[0].roles,['client','supplier']);
const saved=new Map(),storage={getItem:k=>saved.get(k),setItem:(k,v)=>saved.set(k,v)};
function app(){const body={innerHTML:''},root={querySelector:()=>body,querySelectorAll:()=>[],dataset:{},style:{setProperty(){}},addEventListener(){}};const context={document:{getElementById:()=>root},window:{addEventListener(){}},console,localStorage:storage,ReferenceCore:R};vm.createContext(context);const source=fs.readFileSync('gestion-demo.js','utf8').replace(' restore(window.openai?.widgetState);',' globalThis.api={attachPartner,switchStore,handle,save,render,views,getState:()=>s,getClients:()=>C}; restore(window.openai?.widgetState);');vm.runInContext(source,context);return {...context.api,body};}
let a=app();const entry={id:'test-garage',name:'Test <img src=x onerror=alert(1)>',city:'Bayonne',address:'Test',kind:'garage',sources:[]};a.attachPartner(entry,'client');a.attachPartner(entry,'client');assert.equal(a.getState().partners.length,1);assert.equal(a.getClients().length,4);a.handle('client-sale:3');a.handle('add:0');a.handle('validate');assert.equal(a.getState().docs.at(-1).client,3);a.save();a=app();assert.equal(a.getClients().length,4);assert.equal(a.getState().docs.at(-1).client,3);a.getState().clientView=3;
for(const page of ['clients','sale','documents','portal','home']){a.getState().page=page;a.render();assert.ok(!a.body.innerHTML.includes('<img'),'unescaped public name in '+page);}
assert.match(a.views.portal(),/<option value="3"/);assert.ok(!a.views.portal().includes('<option value="2"'));
a.switchStore('landes');assert.equal(a.getClients().length,3);assert.equal(a.getState().partners.length,0);a.attachPartner({...entry,id:'other-store',name:'Autre garage'},'client');a.switchStore('bellecave');assert.equal(a.getClients()[3].partnerId,'test-garage');a.save();a=app();a.switchStore('landes');assert.equal(a.getClients()[3].partnerId,'other-store');
console.log(JSON.stringify({pass:true,sirene:sirene.entries.length,osm:osm.entries.length,official:official.entries.length,merged:all.length,garages:all.filter(e=>e.kind==='garage').length,suppliers:all.filter(e=>e.kind==='supplier').length,phone:all.filter(e=>e.phone).length,email:all.filter(e=>e.email).length,products:products.entries.length,local:all.filter(e=>['64','40'].includes(e.department)).length},null,2));
console.log('PASS provenance, géographie, GTIN, sources fusionnées, doublons, échappement, portail, isolation et restauration après rechargement');
