(function(root){
 'use strict';
 const STATUS=Object.freeze({requested:'À enlever',collected:'Collecté',received:'Réceptionné',supplier_ready:'Prêt fournisseur',sent:'Envoyé fournisseur',credit_pending:'Avoir attendu',credited:'Avoir reçu',cancelled:'Annulé'});
 const NEXT=Object.freeze({requested:['collected','cancelled'],collected:['received','cancelled'],received:['supplier_ready','cancelled'],supplier_ready:['sent','cancelled'],sent:['credit_pending','cancelled'],credit_pending:['credited','cancelled'],credited:[],cancelled:[]});
 const norm=value=>String(value||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').trim().toUpperCase();
 function quantity(value){const n=Number(value);if(!Number.isSafeInteger(n)||n<1||n>100000)throw Error('Quantité invalide.');return n;}
 function newLine(product={}){return {id:crypto.randomUUID(),product_id:product.id||null,reference:norm(product.reference),description:String(product.description||'').trim(),quantity:1,received_quantity:null,condition:'',reason:''};}
 function validateLine(line){if(!line||typeof line.id!=='string'||!line.id||!norm(line.reference)||norm(line.reference).length>120||String(line.description||'').length>500)throw Error('Ligne retour invalide.');quantity(line.quantity);if(line.received_quantity!==null&&line.received_quantity!==undefined){const n=Number(line.received_quantity);if(!Number.isSafeInteger(n)||n<0||n>line.quantity)throw Error('Quantité réceptionnée invalide.');}if(String(line.condition||'').length>300||String(line.reason||'').length>500)throw Error('Informations de ligne trop longues.');}
 function validateDocument(d){if(!d||!['return','warranty','mixed'].includes(d.type)||!Object.hasOwn(STATUS,d.status)||typeof d.client_name!=='string'||!d.client_name.trim()||d.client_name.length>180||typeof d.supplier_name!=='string'||d.supplier_name.length>180||!Array.isArray(d.lines)||!d.lines.length||d.lines.length>200)throw Error('Dossier retour incomplet.');const ids=new Set();for(const line of d.lines){validateLine(line);if(ids.has(line.id))throw Error('Ligne retour dupliquée.');ids.add(line.id);}return d;}
 function canMove(from,to){return NEXT[from]?.includes(to)===true;}
 function badge(cases){return cases.filter(c=>c.document?.status==='requested').length;}
 function search(cases,query='',status=''){const q=norm(query);return cases.filter(c=>!status||c.document.status===status).filter(c=>!q||norm([c.document.client_name,c.document.supplier_name,c.document.type,...c.document.lines.flatMap(l=>[l.reference,l.description])].join(' ')).includes(q)).sort((a,b)=>new Date(b.updated_at)-new Date(a.updated_at));}
 function csvCell(value){const text=String(value??'');return '"'+(/^[=+\-@]/.test(text)?"'":'')+text.replace(/"/g,'""')+'"';}
 function creditCsv(row){const d=row?.document||row;if(!d)throw Error('Dossier avoir introuvable.');validateDocument(d);const headers=['Dossier','État','Type','Garage','Fournisseur','Référence','Désignation','À reprendre','Réceptionné','État pièce','Motif'];const rows=d.lines.map(line=>[row.id||'',STATUS[d.status]||d.status,d.type,d.client_name,d.supplier_name,line.reference,line.description,line.quantity,line.received_quantity??'',line.condition,line.reason]);return '\uFEFF'+[headers,...rows].map(values=>values.map(csvCell).join(';')).join('\r\n');}
 function creditMail(row){const d=row.document||row;const subject='Avoir à traiter · '+d.client_name+(d.supplier_name?' · '+d.supplier_name:'');const details=d.lines.map(line=>'- '+line.reference+' · '+line.quantity+' à reprendre'+(line.received_quantity!==null&&line.received_quantity!==undefined?' · '+line.received_quantity+' réceptionnée(s)':'')).join('\n');return {subject,body:'Bonjour,\n\nVeuillez trouver ci-joint le relevé de retour / garantie à traiter.\n\nGarage : '+d.client_name+'\nType : '+(d.type==='warranty'?'Garantie':d.type==='mixed'?'Retour et garantie':'Retour client')+'\n\nPièces :\n'+details+'\n\nCordialement.'};}
 const api={STATUS,NEXT,norm,quantity,newLine,validateLine,validateDocument,canMove,badge,search,creditCsv,creditMail};
 if(typeof module!=='undefined')module.exports=api;else root.ReturnsCore=api;
})(typeof globalThis!=='undefined'?globalThis:this);
