(()=>{'use strict';
const C=ReturnsCore,P=PartnerPlanning,$=id=>document.getElementById(id),shop='8770297c-cadb-4cc6-8b93-55a0f9bd154e';
const db=supabase.createClient('https://pryocchvwmnuoidtitow.supabase.co','sb_publishable_AQ9cr2Z7Kr6EAravVOgB9Q_Z5Mx2yOZ');
let actor=null,role='',epoch=0,cases=[],clients=[],suppliers=[],current=null,lines=[],dirty=false,busy=false,scanner=null,lastCode='',lastAt=0,liveChannel=null;
const check=r=>{if(r.error)throw Object.assign(Error(r.error.message),{code:r.error.code});return r.data;};
const writable=()=>['operator','admin'].includes(role);
const kind=d=>d.type==='warranty'?'Garantie':d.type==='deposit'?'Consigne':d.type==='mixed'?'Retour et garantie':'Retour';
const carrier=d=>d.collection_carrier||'À attribuer';
function say(text,error=false){$('status').textContent=text;$('status').className=error?'error':'';}
function mark(value){dirty=value;if(parent!==window)parent.postMessage({type:'alcorb-dirty',dirty:value},location.origin);}
function clear(){epoch++;actor=null;role='';cases=[];clients=[];suppliers=[];current=null;lines=[];mark(false);stopCamera();if(liveChannel){db.removeChannel(liveChannel);liveChannel=null;}$('workspace').hidden=true;$('editor').hidden=true;$('list').replaceChildren();}
function statusLabel(s){return C.STATUS[s]||'État inconnu';}
function clientById(id){return clients.find(p=>p.id===id)||null;}
function supplierById(id){return suppliers.find(p=>p.id===id)||null;}
function address(p){const d=p?.details||{};return [d.address,d.postcode,d.city].filter(Boolean).join(' · ');}
function departure(d){const p=clientById(d.client_id),next=p?.departures?.length?P.next(p)[0]:null;return next?'Prochain passage : '+next.carrier+' à '+next.time:'';}
function options(select,rows,selected,placeholder,format=p=>p.name){select.replaceChildren(new Option(placeholder,''));for(const row of rows)select.append(new Option(format(row),row.id));select.value=selected||'';}
function filterClients(value){const q=C.norm(value);return clients.filter(p=>!q||C.norm([p.name,p.details?.code,p.details?.address,p.details?.city].join(' ')).includes(q));}
function populateCarriers(){for(const id of ['carrier','carrierFilter']){const el=$(id),previous=el.value;el.replaceChildren(new Option(id==='carrier'?'À attribuer':'Tous',''));for(const name of C.CARRIERS)el.append(new Option(name,name));el.value=previous;}}
function populatePartners(){const selectedClient=$('client').value,selectedSupplier=$('supplier').value,selectedLink=$('linkGarage').value;const visible=filterClients($('clientSearch').value);options($('client'),visible,selectedClient,'Choisir dans la liste',p=>p.name+(p.details?.code?' · '+p.details.code:''));options($('linkGarage'),filterClients($('linkGarageSearch').value),selectedLink,'Choisir un garage',p=>p.name+(p.details?.code?' · '+p.details.code:''));options($('supplier'),suppliers,selectedSupplier,'À déterminer à la réception');}
function renderCard(row){const d=row.document,card=document.createElement('details'),summary=document.createElement('summary'),meta=document.createElement('p'),actions=document.createElement('div'),open=document.createElement('button');card.className='case '+d.status;summary.textContent=statusLabel(d.status)+' · '+d.client_name+' · '+d.lines.length+' référence(s)';meta.className='meta';meta.textContent=[kind(d),'Transporteur : '+carrier(d),address(clientById(d.client_id)),departure(d),'Mis à jour '+new Date(row.updated_at).toLocaleString('fr-FR')].filter(Boolean).join(' · ');open.type='button';open.textContent='Ouvrir le dossier';open.onclick=()=>openCase(row);actions.className='case-actions';if(d.status==='requested'){const task=document.createElement('button');task.type='button';task.className='task';task.textContent=d.collection_done?'Fait':'À faire';task.disabled=!writable()||busy;task.onclick=()=>markCollected(row);actions.append(task);}actions.append(open);card.append(summary,meta,actions);return card;}
function paintList(){const list=C.search(cases,$('filter').value,$('statusFilter').value,$('carrierFilter').value);$('list').replaceChildren();const waiting=cases.filter(c=>c.document?.status==='requested').length;$('alert').textContent=waiting?waiting+' à enlever':'';$('alert').className=waiting?'badge':'';if(!list.length){const p=document.createElement('p');p.textContent='Aucun dossier ne correspond à cette recherche.';$('list').append(p);return;}const groups=new Map();for(const row of list){const key=row.document.status==='requested'?'À enlever · '+carrier(row.document):'Traitement · '+statusLabel(row.document.status);if(!groups.has(key))groups.set(key,[]);groups.get(key).push(row);}for(const [name,rows] of groups){const h=document.createElement('h2');h.className='group-title';h.textContent=name;$('list').append(h);for(const row of rows)$('list').append(renderCard(row));}}
function paintLines(){$('lines').replaceChildren();for(const [index,item] of lines.entries()){$('lines').append(lineRow(item,index));}if(!lines.length){const p=document.createElement('p');p.textContent='Ajoutez au moins une pièce.';$('lines').append(p);}}
function lineRow(item,index){const card=document.createElement('article'),ref=document.createElement('strong'),desc=document.createElement('p'),qtyLabel=document.createElement('label'),qty=document.createElement('input'),gotLabel=document.createElement('label'),got=document.createElement('input'),remove=document.createElement('button'),editable=writable()&&(!current||current.document.status==='requested');card.className='line';ref.textContent=item.reference;desc.textContent=[item.brand,item.range,item.description||'Désignation à compléter.',item.location].filter(Boolean).join(' · ');qtyLabel.textContent='À reprendre';qty.type='number';qty.min='1';qty.max='100000';qty.step='1';qty.value=item.quantity;qty.disabled=!editable;qty.oninput=()=>{item.quantity=Number(qty.value);mark(true);};gotLabel.textContent='Réceptionné';got.type='number';got.min='0';got.max=String(item.quantity);got.step='1';got.value=item.received_quantity??'';got.placeholder='—';got.disabled=!writable()||!['collected','received'].includes(current?.document.status);got.oninput=()=>{item.received_quantity=got.value===''?null:Number(got.value);mark(true);};remove.type='button';remove.textContent='Retirer';remove.disabled=!editable;remove.onclick=()=>{lines.splice(index,1);mark(true);paintLines();};card.append(ref,desc,qtyLabel,gotLabel,remove);qtyLabel.append(qty);gotLabel.append(got);return card;}
function documentFromForm(status){const client=clientById($('client').value),supplier=supplierById($('supplier').value);return {type:$('type').value,status,client_id:client?.id||null,client_name:(client?.name||$('clientName').value).trim(),supplier_id:supplier?.id||null,supplier_name:(supplier?.name||'').trim(),collection_carrier:$('carrier').value||'',collection_done:status!=='requested'||!!current?.document?.collection_done,lines:structuredClone(lines)};}
function eventMessage(e){return e.event_kind==='created'?'Dossier créé':e.event_kind==='status_changed'?statusLabel(e.from_status)+' → '+statusLabel(e.to_status):'Dossier mis à jour';}
async function paintHistory(){if(!current)return;try{const events=check(await db.from('returns_case_events').select('*').eq('case_id',current.id).order('created_at',{ascending:true}).limit(100));if(!current)return;$('events').replaceChildren();for(const e of events){const p=document.createElement('p');p.textContent=new Date(e.created_at).toLocaleString('fr-FR')+' · '+eventMessage(e)+(e.note?' · '+e.note:'');$('events').append(p);}$('history').hidden=false;}catch{$('events').textContent='Historique indisponible.';$('history').hidden=false;}}
function setEditor(enabled){$('fields').disabled=!enabled;$('save').hidden=!enabled;}
function nextText(status){return({requested:'Marquer comme collecté',collected:'Valider la réception',received:'Préparer l’envoi fournisseur',supplier_ready:'Marquer envoyé au fournisseur',sent:'Passer à avoir attendu',credit_pending:'Confirmer l’avoir reçu'})[status]||'';}
async function openCase(row){if(dirty&&!confirm('Fermer les modifications non enregistrées ?'))return;await stopCamera();current=structuredClone(row);lines=structuredClone(row.document.lines);$('title').textContent='Dossier · '+row.document.client_name;$('type').value=row.document.type;$('client').value=row.document.client_id||'';$('clientName').value=row.document.client_name;$('supplier').value=row.document.supplier_id||'';$('carrier').value=row.document.collection_carrier||'';$('note').value='';$('saved').textContent='Version '+row.version+' · '+statusLabel(row.document.status);$('processHint').textContent=row.document.status==='collected'?'Contrôlez les quantités réellement reçues, puis validez la réception.':'Chaque transition reste datée et attribuée à la personne connectée.';$('editor').hidden=false;setEditor(writable());paintLines();const target=C.NEXT[row.document.status]?.[0];$('next').hidden=!writable()||!target;$('next').textContent=nextText(row.document.status);await paintHistory();mark(false);$('saved').scrollIntoView({behavior:'smooth',block:'end'});$('saved').focus({preventScroll:true});}
function newCase(){if(!writable())return;if(dirty&&!confirm('Abandonner les modifications non enregistrées ?'))return;current=null;lines=[];$('editor').reset();populatePartners();populateCarriers();$('title').textContent='Nouveau dossier interne';$('saved').textContent='Ajoutez les pièces, puis enregistrez.';$('editor').hidden=false;setEditor(true);$('next').hidden=true;$('history').hidden=true;paintLines();mark(false);$('saved').scrollIntoView({behavior:'smooth',block:'end'});}
async function loadCases(notify=false){const token=epoch;try{const data=check(await db.from('returns_cases').select('*').eq('workspace_id',shop).order('updated_at',{ascending:false}).limit(500));if(token!==epoch)return;cases=data;paintList();if(notify&&!dirty)say('Les retours ont été actualisés automatiquement.');}catch(e){if(token===epoch)say(e.code==='42501'?'Accès retours non confirmé.':'Retours indisponibles : '+e.message,true);}}
async function loadPartners(){const token=epoch,rows=[];for(let from=0;;from+=500){const data=check(await db.from('gestion_partners').select('*').eq('workspace_id',shop).order('id').range(from,from+499));if(token!==epoch)return;rows.push(...data);if(data.length<500)break;}clients=rows.filter(p=>p.kind==='client'&&!p.details?.archived&&!p.details?.merged_into).sort((a,b)=>a.name.localeCompare(b.name,'fr'));suppliers=rows.filter(p=>p.kind==='supplier'&&!p.details?.archived).sort((a,b)=>a.name.localeCompare(b.name,'fr'));populatePartners();populateCarriers();}
async function subscribe(){if(liveChannel)db.removeChannel(liveChannel);liveChannel=db.channel('returns-'+shop).on('postgres_changes',{event:'*',schema:'public',table:'returns_cases',filter:'workspace_id=eq.'+shop},()=>{if(!dirty)loadCases(true);else say('Un dossier retour a changé ailleurs. Enregistrez ou fermez vos modifications avant de recharger.',true);}).subscribe();}
async function enter(session){const id=session?.user?.id||null;if(id===actor)return;clear();actor=id;if(!id){say('Connectez-vous depuis l’application.');return;}const token=epoch;try{const member=check(await db.from('scanette_members').select('role').eq('workspace_id',shop).eq('user_id',id).maybeSingle());if(token!==epoch)return;if(!member||!['reader','operator','admin'].includes(member.role))throw Error('Accès application absent.');role=member.role;await loadPartners();if(token!==epoch)return;$('workspace').hidden=false;$('new').hidden=!writable();await loadCases();await subscribe();if(token===epoch)say(writable()?'Prêt. Les dossiers se synchronisent automatiquement.':'Lecture seule.');}catch(e){if(token===epoch)say(e.message||'Connexion retours indisponible.',true);}}
function addProduct(product){if(lines.some(l=>product.id?l.product_id===product.id:C.norm(l.reference)===C.norm(product.reference))){$('lookup').textContent='Cette fiche est déjà dans le dossier.';return;}lines.push(C.newLine(product));lines.at(-1).brand=product.brand||'';lines.at(-1).range=product.range||'';lines.at(-1).location=product.location||'';$('reference').value='';$('lookup').replaceChildren();paintLines();mark(true);}
async function addReference(raw){if(!writable())return;const term=C.norm(raw);if(!term)return;const notice=$('lookup');notice.textContent='Recherche de la référence…';try{let products=check(await db.from('scanette_products').select('id,reference,description,brand,range,location').eq('workspace_id',shop).eq('reference',term).limit(12));if(!products.length)products=check(await db.from('scanette_products').select('id,reference,description,brand,range,location').eq('workspace_id',shop).eq('internal_barcode',raw.trim()).limit(12));if(!products.length)products=check(await db.from('scanette_products').select('id,reference,description,brand,range,location').eq('workspace_id',shop).eq('manufacturer_barcode',raw.trim()).limit(12));notice.replaceChildren();if(!products.length){addProduct({reference:term,description:''});$('lookup').textContent='Référence absente du catalogue : ajoutée à vérifier.';return;}if(products.length===1){addProduct(products[0]);$('lookup').textContent='Référence catalogue ajoutée.';return;}const p=document.createElement('p');p.textContent='Plusieurs fiches correspondent. Choisissez la marque :';notice.append(p);for(const product of products){const b=document.createElement('button');b.type='button';b.className='choice';b.textContent=[product.brand||'Marque à préciser',product.range,product.description,product.location].filter(Boolean).join(' · ');b.onclick=()=>addProduct(product);notice.append(b);}}catch(e){notice.textContent=e.message||'Recherche indisponible.';}}
async function stopCamera(){const old=scanner;scanner=null;$('scanner').hidden=true;if(old)try{await old.stop();old.clear();}catch{}}
async function startCamera(){if(scanner||!writable())return;const s=new Html5Qrcode('reader');scanner=s;$('scanner').hidden=false;try{await s.start({facingMode:'environment'},{fps:10,qrbox:{width:260,height:120}},async code=>{if(Date.now()-lastAt<1600||code===lastCode)return;lastAt=Date.now();lastCode=code;await addReference(code);},()=>{});}catch{await stopCamera();$('lookup').textContent='Caméra indisponible. Vérifiez l’autorisation ou saisissez la référence.';}}
async function persist(row,document,note){const saved=check(await db.rpc('returns_save_case',{shop_id:shop,case_id:row?.id||crypto.randomUUID(),expected_version:row?.version||0,case_document:document,event_note:note||''}));const result=Array.isArray(saved)?saved[0]:saved;if(!result?.id)throw Error('Le serveur n’a pas confirmé le dossier.');const index=cases.findIndex(c=>c.id===result.id);if(index<0)cases.unshift(result);else cases[index]=result;current=result;paintList();return result;}
async function save(targetStatus=null){if(!writable()||busy)return;const status=targetStatus||current?.document.status||'requested';let document;try{document=documentFromForm(status);C.validateDocument(document);if(current&&status!==current.document.status&&!C.canMove(current.document.status,status))throw Error('Transition non autorisée.');}catch(e){$('saved').textContent=e.message;return;}busy=true;$('save').disabled=true;$('next').disabled=true;try{const row=await persist(current,document,$('note').value.trim());$('saved').textContent='Dossier enregistré et synchronisé · version '+row.version+'.';$('note').value='';mark(false);await openCase(row);}catch(e){$('saved').textContent=e.code==='PT409'?'Dossier modifié ailleurs. Fermez-le puis ouvrez la version actuelle avant de recommencer.':e.message||'Enregistrement non confirmé.';}finally{busy=false;$('save').disabled=false;$('next').disabled=false;}}
async function markCollected(row){if(!writable()||busy)return;busy=true;try{const doc=structuredClone(row.document);doc.status='collected';doc.collection_done=true;const saved=await persist(row,doc,'Enlèvement confirmé.');say('Enlèvement marqué comme fait.');paintList();}catch(e){say(e.message||'Mise à jour indisponible.',true);}finally{busy=false;}}
function installPortalActions(){const create=$('createPortal'),revoke=$('revokePortal'),selected=()=>$('linkGarage').value;const repaint=()=>{const ok=writable()&&!!selected();create.disabled=!ok;revoke.disabled=!ok;};create.onclick=async()=>{if(!selected())return;create.disabled=true;try{const token=check(await db.rpc('returns_portal_issue_link',{shop_id:shop,garage_id:selected()}));const url=new URL('returns-portal.html?t='+encodeURIComponent(token),location.href).href;try{await navigator.clipboard.writeText(url);$('linkStatus').textContent='Lien privé copié. Transmettez-le uniquement au garage concerné.';}catch{window.prompt('Copiez ce lien privé :',url);}}catch(e){$('linkStatus').textContent=e.message||'Création du lien indisponible.';}finally{repaint();}};revoke.onclick=async()=>{if(!selected()||!confirm('Révoquer tous les liens actifs pour ce garage ?'))return;try{check(await db.rpc('returns_portal_revoke_client_links',{shop_id:shop,garage_id:selected()}));$('linkStatus').textContent='Les liens privés de ce garage sont révoqués.';}catch(e){$('linkStatus').textContent=e.message||'Révocation indisponible.';}repaint();};$('linkGarage').onchange=repaint;repaint();}
$('new').onclick=newCase;$('close').onclick=()=>{if(dirty&&!confirm('Fermer les modifications non enregistrées ?'))return;stopCamera();$('editor').hidden=true;current=null;mark(false);};$('filter').oninput=paintList;$('statusFilter').onchange=paintList;$('carrierFilter').onchange=paintList;$('clientSearch').oninput=populatePartners;$('linkGarageSearch').oninput=populatePartners;$('client').onchange=()=>{const p=clientById($('client').value);if(p)$('clientName').value=p.name;mark(true);};$('type').onchange=() => mark(true);$('carrier').onchange=()=>mark(true);$('supplier').onchange=()=>mark(true);$('clientName').oninput=()=>{const linked=clientById($('client').value);if(linked&&linked.name!==$('clientName').value.trim())$('client').value='';mark(true);};$('note').oninput=()=>mark(true);$('addRef').onclick=()=>addReference($('reference').value);$('reference').onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();addReference($('reference').value);}};$('camera').onclick=startCamera;$('stopCamera').onclick=stopCamera;$('editor').onsubmit=e=>{e.preventDefault();save();};$('next').onclick=()=>save(C.NEXT[current.document.status][0]);installPortalActions();
window.addEventListener('pagehide',()=>{stopCamera();if(liveChannel)db.removeChannel(liveChannel);});document.addEventListener('visibilitychange',()=>{if(document.hidden)stopCamera();});setInterval(()=>{if(actor&&!document.hidden&&!dirty&&!busy)loadCases();},30000);db.auth.onAuthStateChange((_event,s)=>setTimeout(()=>enter(s),0));db.auth.getSession().then(r=>enter(r.data.session)).catch(()=>say('Connexion indisponible.',true));
})();