(()=>{'use strict';
const C=ReturnsCore,P=PartnerPlanning,$=id=>document.getElementById(id);
// Shared logistics access without account: shared_* functions serve the configured shop only.
// Other devices' changes arrive through the 30-second refresh (no realtime channel for anon).
const call=SharedAccess.call;
let actor=null,role='',epoch=0,cases=[],clients=[],suppliers=[],current=null,lines=[],dirty=false,busy=false,scanner=null,lastCode='',lastAt=0;
const writable=()=>['operator','admin'].includes(role);
function say(text,error=false){$('status').textContent=text;$('status').className=error?'error':'';}
function mark(value){dirty=value;if(parent!==window)parent.postMessage({type:'alcorb-dirty',dirty:value},location.origin);}
function clear(){epoch++;actor=null;role='';cases=[];clients=[];suppliers=[];current=null;lines=[];mark(false);stopCamera();$('workspace').hidden=true;$('editor').hidden=true;$('list').replaceChildren();}
function statusLabel(s){return C.STATUS[s]||'État inconnu';}
function clientById(id){return clients.find(p=>p.id===id)||null;}
function supplierById(id){return suppliers.find(p=>p.id===id)||null;}
function departure(document){const p=clientById(document.client_id);const next=p?.departures?.length?P.next(p)[0]:null;return next?' · Prochain passage : '+next.carrier+' à '+next.time:'';}
function caseTypeLabel(type){return type==='warranty'?'Garantie':type==='deposit'?'Consigne':type==='mixed'?'Retour et garantie':'Retour';}
function paintList(){const list=C.search(cases,$('filter').value,$('statusFilter').value);$('list').replaceChildren();$('alert').textContent=C.badge(cases)?C.badge(cases)+' dossier(s) à enlever':'';$('alert').className=C.badge(cases)?'badge':'';
 if(!list.length){const p=document.createElement('p');p.className='empty-list';p.textContent='Aucun dossier ne correspond à cette recherche.';$('list').append(p);return;}
 const grid=document.createElement('div');grid.className='case-grid';
 for(const row of list){const d=row.document,card=document.createElement('article'),head=document.createElement('div'),state=document.createElement('span'),garage=document.createElement('h2'),info=document.createElement('p'),meta=document.createElement('p'),open=document.createElement('button');card.className='case '+d.status;head.className='case-head';state.className='case-state';state.textContent=statusLabel(d.status);garage.textContent=d.client_name;const portal=C.portalInfo(d);info.className='case-info';info.textContent=(portal?'Demande garage · ':'')+caseTypeLabel(d.type)+' · '+d.lines.length+' référence'+(d.lines.length>1?'s':'')+(d.supplier_name?' · '+d.supplier_name:' · fournisseur à déterminer');meta.className='meta';meta.textContent=(departure(d).replace(/^ · /,'')||'Passage à confirmer')+' · Mis à jour '+new Date(row.updated_at).toLocaleString('fr-FR');open.type='button';open.className='secondary';open.textContent='Ouvrir le dossier';open.onclick=()=>openCase(row);head.append(state);card.append(head,garage,info);if(portal){const place=document.createElement('p');place.className='case-place';place.textContent='À récupérer : '+(portal.location||'emplacement non précisé')+(portal.verified?'':' · garage à vérifier');card.append(place);}card.append(meta,open);grid.append(card);}$('list').append(grid);
}
function partnersSelect(){const selectedClient=$('client').value,selectedSupplier=$('supplier').value;$('client').replaceChildren(new Option('Choisir dans la liste',''));for(const p of clients)$('client').append(new Option(p.name+(p.details?.code?' · '+p.details.code:''),p.id));$('client').value=selectedClient;$('supplier').replaceChildren(new Option('À déterminer à la réception',''));for(const p of suppliers)$('supplier').append(new Option(p.name,p.id));$('supplier').value=selectedSupplier;}
function row(line,index){const card=document.createElement('article'),ref=document.createElement('strong'),desc=document.createElement('p'),qtyLabel=document.createElement('label'),qty=document.createElement('input'),gotLabel=document.createElement('label'),got=document.createElement('input'),remove=document.createElement('button');card.className='line';ref.textContent=line.reference;desc.textContent=line.description||'Référence ajoutée manuellement — désignation à compléter.';qtyLabel.textContent='À reprendre';qty.type='number';qty.min='1';qty.max='100000';qty.step='1';qty.value=line.quantity;qty.disabled=!writable()||current?.document.status!=='requested';qty.oninput=()=>{line.quantity=Number(qty.value);mark(true);};gotLabel.textContent='Réceptionné';got.type='number';got.min='0';got.max=String(line.quantity);got.step='1';got.value=line.received_quantity??'';got.placeholder='—';got.disabled=!writable()||!['collected','received'].includes(current?.document.status);got.oninput=()=>{line.received_quantity=got.value===''?null:Number(got.value);mark(true);};remove.type='button';remove.textContent='Retirer';remove.disabled=!writable()||current?.document.status!=='requested';remove.onclick=()=>{lines.splice(index,1);mark(true);paintLines();};card.append(ref,desc,qtyLabel,gotLabel,remove);return card;}
function paintLines(){$('lines').replaceChildren();for(const [i,line] of lines.entries())$('lines').append(row(line,i));if(!lines.length){const p=document.createElement('p');p.textContent='Ajoutez au moins une pièce.';$('lines').append(p);}}
function documentFromForm(status){const client=clientById($('client').value),supplier=supplierById($('supplier').value);return C.mergeDocument(current?.document,{type:$('type').value,status,client_id:client?.id||null,client_name:(client?.name||$('clientName').value).trim(),supplier_id:supplier?.id||null,supplier_name:(supplier?.name||'').trim(),lines:structuredClone(lines)});}
function eventMessage(e){return e.event_kind==='created'?'Dossier créé':e.event_kind==='status_changed'?statusLabel(e.from_status)+' → '+statusLabel(e.to_status):'Dossier mis à jour';}
async function paintHistory(){if(!current)return;try{const events=await call('shared_return_events',{case_id:current.id});if(!current)return;$('events').replaceChildren();for(const e of events){const p=document.createElement('p');p.textContent=new Date(e.created_at).toLocaleString('fr-FR')+' · '+eventMessage(e)+(e.note?' · '+e.note:'')+(e.access_source==='shared_access'?' · accès partagé':'');$('events').append(p);}$('history').hidden=false;}catch{$('events').textContent='Historique indisponible.';$('history').hidden=false;}}
function paintPortal(d){const box=$('portalInfo');if(!box)return;const portal=C.portalInfo(d);box.hidden=!portal;box.textContent=portal?'Demande déposée par le garage sur le portail public · À récupérer : '+(portal.location||'emplacement non précisé')+(portal.verified?'':' · Nom saisi par le garage : reliez-le à la bonne fiche garage.'):'';}
function setEditor(enabled){$('fields').disabled=!enabled;$('save').hidden=!enabled;}
async function openCase(row){if(dirty&&!confirm('Fermer les modifications non enregistrées ?'))return;await stopCamera();current=structuredClone(row);lines=structuredClone(row.document.lines);$('title').textContent='Dossier · '+row.document.client_name;$('type').value=row.document.type;$('client').value=row.document.client_id||'';$('clientName').value=row.document.client_name;$('supplier').value=row.document.supplier_id||'';$('note').value='';$('saved').textContent='Version '+row.version+' · '+statusLabel(row.document.status);paintPortal(row.document);$('editor').hidden=false;setEditor(writable());paintLines();const target=C.NEXT[row.document.status]?.[0];$('next').hidden=!writable()||!target;$('next').textContent=target?'Passer à « '+statusLabel(target)+' »':'';await paintHistory();mark(false);$('editor').scrollIntoView({behavior:'smooth',block:'start'});}
function newCase(){if(!writable())return;if(dirty&&!confirm('Abandonner les modifications non enregistrées ?'))return;current=null;lines=[];$('editor').reset();partnersSelect();$('title').textContent='Nouveau dossier retour';paintPortal(null);$('saved').textContent='Ajoutez les pièces, puis enregistrez : le dossier apparaîtra sur les autres appareils à leur prochaine actualisation.';$('editor').hidden=false;setEditor(true);$('next').hidden=true;$('history').hidden=true;paintLines();mark(false);$('editor').scrollIntoView({behavior:'smooth',block:'start'});}
async function loadCases(notify=false){const token=epoch;try{const data=await call('shared_returns',{max_rows:500});if(token!==epoch)return;cases=data;paintList();if(notify&&!dirty)say('Les retours ont été actualisés automatiquement.');}catch(e){if(token===epoch)say(e.code==='42501'?SharedAccess.message(e):'Retours indisponibles : '+e.message,true);}}
async function loadPartners(){const token=epoch,rows=await call('shared_partners',{partner_kind:null});if(token!==epoch)return;clients=rows.filter(p=>p.kind==='client'&&!p.details?.archived&&!p.details?.merged_into).sort((a,b)=>a.name.localeCompare(b.name,'fr'));suppliers=rows.filter(p=>p.kind==='supplier'&&!p.details?.archived).sort((a,b)=>a.name.localeCompare(b.name,'fr'));partnersSelect();}
async function enter(){clear();actor=SharedAccess.ACTOR;const token=epoch;try{role='operator';await loadPartners();if(token!==epoch)return;$('workspace').hidden=false;$('new').hidden=!writable();await loadCases();if(token===epoch)say('Prêt. Accès logistique partagé : les dossiers s’actualisent toutes les 30 secondes.');}catch(e){if(token===epoch)say(e.message||'Retours indisponibles.',true);}}
async function addReference(raw){if(!writable())return;const term=C.norm(raw);if(!term)return;const notice=$('lookup');notice.textContent='Recherche de la référence…';try{const code=raw.trim().slice(0,256),found=[];for(const value of new Set([term,code]))for(const p of await call('shared_product_lookup',{code:value}))if(!found.some(f=>f.id===p.id))found.push(p);let products=found.filter(p=>p.reference===term);if(!products.length)products=found.filter(p=>p.internal_barcode===code);if(!products.length)products=found.filter(p=>p.manufacturer_barcode===code);if(products.length>1)throw Error('Plusieurs fiches correspondent : renseignez la référence à la main.');const product=products[0];if(lines.some(l=>product?l.product_id===product.id:C.norm(l.reference)===term)){notice.textContent='Cette référence est déjà dans le dossier.';return;}lines.push(product?C.newLine(product):C.newLine({reference:term,description:''}));$('reference').value='';notice.textContent=product?'Référence catalogue ajoutée.':'Référence absente du catalogue : ajoutée à vérifier.';paintLines();mark(true);}catch(e){notice.textContent=e.message||'Recherche indisponible.';}}
async function stopCamera(){const old=scanner;scanner=null;$('scanner').hidden=true;if(old)try{await old.stop();old.clear();}catch{}}
async function startCamera(){if(scanner||!writable())return;const s=new Html5Qrcode('reader');scanner=s;$('scanner').hidden=false;try{await s.start({facingMode:'environment'},{fps:10,qrbox:{width:260,height:120}},async code=>{if(Date.now()-lastAt<1600||code===lastCode)return;lastAt=Date.now();lastCode=code;await addReference(code);},()=>{});}catch{await stopCamera();$('lookup').textContent='Caméra indisponible. Vérifiez l’autorisation ou saisissez la référence.';}}
async function save(targetStatus=null){if(!writable()||busy)return;const status=targetStatus||current?.document.status||'requested';let document;try{document=documentFromForm(status);C.validateDocument(document);if(current&&status!==current.document.status&&!C.canMove(current.document.status,status))throw Error('Transition non autorisée.');}catch(e){$('saved').textContent=e.message;return;}busy=true;$('save').disabled=true;$('next').disabled=true;try{const id=current?.id||crypto.randomUUID(),version=current?.version||0;const saved=await call('shared_save_return',{case_id:id,expected_version:version,case_document:document,event_note:$('note').value.trim()});const row=Array.isArray(saved)?saved[0]:saved;if(!row?.id)throw Error('Le serveur n’a pas confirmé le dossier.');current=row;const i=cases.findIndex(c=>c.id===row.id);if(i<0)cases.unshift(row);else cases[i]=row;paintList();$('saved').textContent='Dossier enregistré et synchronisé · version '+row.version+'.';$('note').value='';mark(false);await openCase(row);}catch(e){$('saved').textContent=e.code==='PT409'?'Dossier modifié ailleurs. Fermez-le puis ouvrez la version actuelle avant de recommencer.':e.message||'Enregistrement non confirmé.';}finally{busy=false;$('save').disabled=false;$('next').disabled=false;}}
$('new').onclick=newCase;$('close').onclick=()=>{if(dirty&&!confirm('Fermer les modifications non enregistrées ?'))return;stopCamera();$('editor').hidden=true;current=null;mark(false);};$('filter').oninput=paintList;$('statusFilter').onchange=paintList;$('client').onchange=()=>{const p=clientById($('client').value);if(p)$('clientName').value=p.name;mark(true);};$('type').onchange=() => mark(true);$('supplier').onchange=()=>mark(true);$('clientName').oninput=()=>mark(true);$('note').oninput=()=>mark(true);$('addRef').onclick=()=>addReference($('reference').value);$('reference').onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();addReference($('reference').value);}};$('camera').onclick=startCamera;$('stopCamera').onclick=stopCamera;$('editor').onsubmit=e=>{e.preventDefault();save();};$('next').onclick=()=>save(C.NEXT[current.document.status][0]);
function installCreditActions(){const exportButton=document.createElement('button'),emailButton=document.createElement('button');exportButton.id='exportCredit';exportButton.type='button';exportButton.className='secondary';exportButton.textContent='Exporter l’avoir CSV';emailButton.id='emailCredit';emailButton.type='button';emailButton.className='secondary';emailButton.textContent='Préparer l’e-mail fournisseur';$('next').after(exportButton,emailButton);const available=()=>['credit_pending','credited'].includes(current?.document?.status);const file=()=>{const name=(current.document.client_name||'avoir').replace(/[^a-z0-9]+/gi,'-').replace(/(^-|-$)/g,'').toLowerCase()||'avoir';return new File([C.creditCsv(current)],'avoir-'+name+'-'+current.id+'.csv',{type:'text/csv;charset=utf-8'});};const paint=()=>{const visible=available(),supplier=supplierById(current?.document?.supplier_id),email=String(supplier?.details?.email||'').trim();exportButton.hidden=!visible;emailButton.hidden=!visible;emailButton.disabled=!visible||!email;emailButton.title=emailButton.disabled?'Adresse e-mail fournisseur absente':'Télécharge le CSV puis ouvre l’e-mail fournisseur';};const download=()=>{if(!available())return;const attachment=file(),url=URL.createObjectURL(attachment),a=document.createElement('a');a.href=url;a.download=attachment.name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);$('saved').textContent='Export CSV préparé. Vous pouvez le joindre à l’avoir fournisseur.';};exportButton.onclick=download;emailButton.onclick=()=>{const supplier=supplierById(current?.document?.supplier_id),email=String(supplier?.details?.email||'').trim();if(!email)return;download();const message=C.creditMail(current);window.location.href='mailto:'+encodeURIComponent(email)+'?subject='+encodeURIComponent(message.subject)+'&body='+encodeURIComponent(message.body);};new MutationObserver(paint).observe($('title'),{childList:true,subtree:true,characterData:true});paint();}
installCreditActions();$('clientName').oninput=()=>{const linked=clientById($('client').value);if(linked&&linked.name!==$('clientName').value.trim())$('client').value='';mark(true);};

window.addEventListener('pagehide',()=>{stopCamera();});document.addEventListener('visibilitychange',()=>{if(document.hidden)stopCamera();});
setInterval(()=>{if(actor&&!document.hidden&&!dirty&&!busy)loadCases();},30000);
enter();
})();
