const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const source=fs.readFileSync('returns-portal.js','utf8');
function setup({token='a'.repeat(64)}={}){
 const nodes={},calls=[];let selected='return';
 function node(){return {hidden:false,value:'',textContent:'',className:'',disabled:false,children:[],style:{},append(...kids){this.children.push(...kids);for(const kid of kids)kid.parentNode=this;},replaceChildren(...kids){this.children=[];this.append(...kids);},setAttribute(){},reset(){this.value='';},remove(){if(this.parentNode)this.parentNode.children=this.parentNode.children.filter(x=>x!==this);}}}
 for(const id of ['status','access','portalLink','openPortal','clientName','form','reference','add','camera','stop','scanner','reader','lines','submit','note','done','again'])nodes[id]=node();nodes.form.hidden=true;nodes.done.hidden=true;nodes.access.hidden=true;
 const document={getElementById:id=>nodes[id]??=node(),createElement:()=>node(),querySelector:s=>s==='input[name="type"]:checked'?{value:selected}:null};
 const db={rpc:async(name,args)=>{calls.push({name,args});return name==='returns_portal_profile'?{data:{client_name:'Garage Test'},error:null}:{data:'case-1',error:null};}};
 const location={search:'',origin:'https://scanette.vercel.app',replace(url){this.replaced=url;}};
 const context={URL,URLSearchParams:class{get(key){return key==='t'?token:null;}},location,supabase:{createClient:()=>db},document,crypto:{randomUUID:()=>String(Math.random())},Html5Qrcode:class{},window:{addEventListener(){}},console};
 vm.createContext(context);vm.runInContext(source,context);return {nodes,calls,location,setType:v=>selected=v,tick:()=>new Promise(r=>setImmediate(r))};
}
test('generic garage entrance only accepts a same-site private return link',async()=>{const a=setup({token:''});await a.tick();assert.equal(a.nodes.access.hidden,false);assert.equal(a.nodes.form.hidden,true);a.nodes.portalLink.value='https://scanette.vercel.app/returns-portal.html?t='+'b'.repeat(64);a.nodes.openPortal.onclick();assert.match(a.location.replaced,/t=b{64}$/);});
test('garage portal keeps the form short and repeated input increments one line',async()=>{const a=setup();await a.tick();assert.equal(a.nodes.form.hidden,false);assert.equal(a.nodes.clientName.textContent,'Garage Test');assert.match(a.nodes.lines.children[0].textContent,/Aucune pièce/);a.nodes.reference.value=' abc-123 ';a.nodes.add.onclick();a.nodes.reference.value='ABC-123';a.nodes.add.onclick();assert.equal(a.nodes.lines.children.length,1);assert.equal(a.nodes.lines.children[0].children[2].textContent,'2');a.nodes.lines.children[0].children[1].onclick();assert.equal(a.nodes.lines.children[0].children[2].textContent,'1');a.nodes.lines.children[0].children[1].onclick();assert.match(a.nodes.lines.children[0].textContent,/Aucune pièce/);});
test('garage submission exports only its selected reason, lines and optional note to the private RPC',async()=>{const a=setup();await a.tick();a.setType('warranty');a.nodes.reference.value='GDB1330';a.nodes.add.onclick();a.nodes.note.value='Carton accueil';await a.nodes.form.onsubmit({preventDefault(){}});const call=a.calls.at(-1);assert.equal(call.name,'returns_portal_submit');assert.equal(call.args.case_type,'warranty');assert.deepEqual(JSON.parse(JSON.stringify(call.args.case_lines.map(x=>({reference:x.reference,quantity:x.quantity})))),[{reference:'GDB1330',quantity:1}]);assert.equal(call.args.case_note,'Carton accueil');assert.equal(a.nodes.done.hidden,false);});