(()=>{'use strict';
const $=id=>document.getElementById(id),token=new URLSearchParams(location.search).get('t')||'',db=supabase.createClient('https://pryocchvwmnuoidtitow.supabase.co','sb_publishable_AQ9cr2Z7Kr6EAravVOgB9Q_Z5Mx2yOZ');
let lines=[],scanner=null,last='',lastAt=0,busy=false;
const safe=value=>String(value||'').trim().toUpperCase();
function say(text,error=false){$('status').textContent=text;$('status').className=error?'error':'';}
function selectedType(){return document.querySelector('input[name="type"]:checked')?.value||'return';}
function paint(){const host=$('lines');host.replaceChildren();if(!lines.length){const empty=document.createElement('p');empty.className='empty';empty.textContent='Aucune pièce ajoutée pour l’instant.';host.append(empty);return;}for(const [index,item] of lines.entries()){const card=document.createElement('article'),ref=document.createElement('strong'),quantity=document.createElement('span'),less=document.createElement('button'),more=document.createElement('button'),remove=document.createElement('button');card.className='line';ref.textContent=item.reference;quantity.className='quantity';quantity.textContent=String(item.quantity);less.type=more.type=remove.type='button';less.className=more.className=remove.className='secondary';less.textContent='−';more.textContent='+';remove.textContent='Retirer';less.setAttribute('aria-label','Retirer une unité de '+item.reference);more.setAttribute('aria-label','Ajouter une unité de '+item.reference);less.onclick=()=>{if(item.quantity===1)lines.splice(index,1);else item.quantity--;paint();};more.onclick=()=>{if(item.quantity<100000)item.quantity++;paint();};remove.onclick=()=>{lines.splice(index,1);paint();};card.append(ref,less,quantity,more,remove);host.append(card);}}
function add(raw){const reference=safe(raw);if(!reference)return;const existing=lines.find(item=>item.reference===reference);if(existing){if(existing.quantity<100000)existing.quantity++;say(reference+' : quantité portée à '+existing.quantity+'.');}else{lines.push({id:crypto.randomUUID(),reference,quantity:1});say(reference+' ajoutée.');}$('reference').value='';paint();}
async function stop(){const old=scanner;scanner=null;$('scanner').hidden=true;if(old)try{await old.stop();old.clear();}catch{}}
async function start(){if(scanner)return;scanner=new Html5Qrcode('reader');$('scanner').hidden=false;try{await scanner.start({facingMode:'environment'},{fps:10,qrbox:{width:260,height:120}},async code=>{const now=Date.now();if(code===last&&now-lastAt<1300)return;last=code;lastAt=now;add(code);},()=>{});}catch{await stop();say('Caméra indisponible. Saisissez la référence.',true);}}
async function profile(){if(!/^[a-f0-9]{64}$/i.test(token))throw Error('Ce lien de retour est invalide.');const {data,error}=await db.rpc('returns_portal_profile',{portal_token:token});if(error)throw error;if(!data?.client_name)throw Error('Ce lien de retour a expiré ou a été révoqué.');$('clientName').textContent=data.client_name;$('form').hidden=false;paint();say('Prêt.');}
async function submit(event){event.preventDefault();if(busy)return;if(!lines.length){say('Ajoutez au moins une référence.',true);return;}for(const item of lines)if(!item.reference||!Number.isSafeInteger(item.quantity)||item.quantity<1||item.quantity>100000){say('Vérifiez les références et quantités.',true);return;}busy=true;$('submit').disabled=true;try{const {error}=await db.rpc('returns_portal_submit',{portal_token:token,case_type:selectedType(),case_lines:lines,case_note:$('note').value.trim()});if(error)throw error;$('form').hidden=true;$('done').hidden=false;say('Demande transmise.');lines=[];await stop();}catch{say('La demande n’a pas été transmise. Vérifiez le lien puis réessayez.',true);}finally{busy=false;$('submit').disabled=false;}}
$('add').onclick=()=>add($('reference').value);$('reference').onkeydown=event=>{if(event.key==='Enter'){event.preventDefault();add($('reference').value);}};$('camera').onclick=start;$('stop').onclick=stop;$('form').onsubmit=submit;$('again').onclick=()=>{$('done').hidden=true;$('form').hidden=false;$('form').reset();lines=[];paint();say('Prêt.');};window.addEventListener('pagehide',stop);profile().catch(error=>say(error.message||'Lien indisponible.',true));
})();
