const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
function setup({fail=false,rows=[{id:'1',name:'APO'},{id:'2',name:'Minerva'}]}={}){const nodes={},sections=[],calls=[];let failOnce=fail,saves=0,serial=2;
function node(){return {value:'',hidden:false,children:[],parentElement:{after(){}},focus(){this.focused=true},addEventListener(e,fn){this['on'+e]=fn},replaceChildren(...x){this.children=x},append(x){this.children.push(x)}}}const $=id=>nodes[id]??=node();
// Shared access facade: the supplier list and the creation go through shared_* functions, never with a shop.
const SharedAccess={call:async(name,args={})=>{assert.equal(/workspace|shop/.test(JSON.stringify(args)),false);if(name==='shared_partners'){assert.equal(args.partner_kind,'supplier');return rows.map(r=>({...r,kind:'supplier'}));}assert.equal(name,'shared_save_partner');calls.push(args);const result={id:args.partner_id,name:args.partner_name};rows.push(result);if(failOnce){failOnce=false;throw Error('response lost');}return [result];}};
const context={document:{getElementById:$,createElement:node},Option:function(t,v){this.text=t;this.value=v},crypto:{randomUUID:()=>String(++serial)},currentUserId:'user',storageReady:true,sections,SharedAccess,save(){saves++},render(){},updateCurSection(){},setTimeout};vm.runInNewContext(fs.readFileSync('scan-suppliers.js','utf8'),context);return {$,sections,calls,rows,context,get saves(){return saves},submit:()=>$('scanSupplierForm').onsubmit({preventDefault(){}})};}
const tick=()=>new Promise(r=>setImmediate(r));
test('Shared list and selection create a local pointage; selecting twice does not duplicate it',async()=>{const a=setup();await tick();assert.equal(a.$('scanSupplier').children.length,3);a.$('scanSupplier').value='1';a.$('scanSupplier').onchange();assert.equal(a.sections[0].name,'APO');a.sections[0].items.X={qty:4};a.$('scanSupplier').onchange();assert.equal(a.sections.length,1);a.$('scanSupplier').value='2';a.$('scanSupplier').onchange();assert.equal(a.sections.length,2);assert.equal(a.sections[0].items.X.qty,4);assert.equal(a.calls.length,0);});
test('Add button opens inline field; new name is registered in shared supplier table',async()=>{const a=setup();await tick();a.$('newSectionBtn').onclick();assert.equal(a.$('scanSupplierForm').hidden,false);assert.equal(a.$('scanSupplierName').focused,true);a.$('scanSupplierName').value='Yacco';await a.submit();assert.equal(a.calls[0].partner_kind,'supplier');assert.equal(a.rows.at(-1).name,'Yacco');assert.equal(a.sections.at(-1).name,'Yacco');assert.equal(a.$('scanSupplierForm').hidden,true);});
test('Typing an existing supplier reuses its record, including a name just added in Reception',async()=>{const a=setup();await tick();a.rows.push({id:'reception',name:'Sodise'});a.$('scanSupplierName').value=' sodise ';await a.submit();assert.equal(a.calls.length,0);assert.equal(a.sections[0].name,'Sodise');});
test('Lost response preserves input and retry recovers supplier without duplicate',async()=>{const a=setup({fail:true});await tick();a.$('scanSupplierName').value='Yacco';await a.submit();assert.equal(a.sections.length,0);assert.equal(a.$('scanSupplierName').value,'Yacco');await a.submit();assert.equal(a.calls.length,1);assert.equal(a.sections[0].name,'Yacco');});
test('Without durable local storage, no supplier is created nor selected',async()=>{const a=setup();await tick();a.context.storageReady=false;a.$('scanSupplierName').value='Blocked';await a.submit();assert.equal(a.calls.length,0);a.$('scanSupplier').value='1';a.$('scanSupplier').onchange();assert.equal(a.sections.length,0);assert.match(a.$('scanSupplierMessage').textContent,/sauvegarde/);});
