'use strict';
const C=Scenario,$=id=>document.getElementById(id),key='alcorb-three-pallets-v2',money=n=>(n/100).toLocaleString('fr-FR',{style:'currency',currency:'EUR'}),esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),date=s=>new Date(s).toLocaleString('fr-FR');
let state=C.initial(new Date().toISOString()),page='home',loadError=false;
try{const saved=localStorage.getItem(key);if(saved)state=C.validate(JSON.parse(saved));}catch{loadError=true;}
function act(type,extra={}){try{if(loadError)throw Error('Sauvegarde illisible. Recommencez explicitement la simulation pour repartir de zéro.');let next=C.transition(state,{type,...extra},new Date().toISOString());if(type==='orderSend'&&!next.shipped){next=C.transition(next,{type:'ship'},new Date().toISOString());next=C.transition(next,{type:'purchase'},new Date().toISOString());}localStorage.setItem(key,JSON.stringify(next));state=next;if(type==='orderSend')page='receive';$('notice').textContent=type==='orderSend'?'Commande envoyée en simulation. APO a préparé la livraison et sa facture de test.':'Enregistré dans la démonstration.';render();}catch(e){$('notice').textContent=e.message;}}
const button=(text,type,disabled=false,extra='')=>`<button data-action="${type}" ${extra} ${disabled?'disabled':''}>${text}</button>`;
const ordered=()=>C.products.reduce((n,p)=>n+C.expected(state,p),0);
const sum=field=>C.products.reduce((n,p)=>n+(field==='stock'?C.stock(state,p.id):field==='expected'?C.expected(state,p):state.counts[p.id]),0);
function restockView(s){const qty=s.order?.quantities||s.draft;return '<section><small>ACHATS · RÉAPPROVISIONNEMENT</small><h2>Préparer une commande</h2><p>Choisis les pièces et les quantités à commander.</p>'+button('Calculer le réappro','replenish',!!s.order)+(qty?'<label>Fournisseur<select aria-label="Fournisseur du réappro"><option>APO · PURFLUX, BOSCH, GATES</option></select></label><p>Un seul fournisseur dans cet essai. Mets une quantité à zéro pour exclure une pièce.</p><div class="lines">'+C.products.map(p=>'<div class="line"><strong>'+p.brand+' · '+p.name+'</strong><p>'+p.ref+' · '+money(p.buy)+' HT / unité</p><label>À commander<input data-orderqty="'+p.id+'" type="number" min="0" max="1000" step="1" value="'+qty[p.id]+'" '+(s.order?'disabled':'')+'></label></div>').join('')+'</div><p><strong>Total : '+money(C.products.reduce((n,p)=>n+qty[p.id]*p.buy,0))+' HT</strong></p>'+button(s.order?s.order.id+' · validée':'Valider la commande APO','order',!!s.order)+'<details><summary>Voir le calcul des besoins</summary><p>Hypothèse pédagogique : couverture 5 jours, ventes fictives sur les 10 derniers jours, stock initial zéro et aucune commande déjà attendue. Ce calendrier simplifié ne représente pas les jours de livraison APO du magasin.</p>'+C.products.map(p=>'<p>'+p.ref+' : '+p.expected*2+' ventes / 10 jours × 5 jours = '+p.expected+' proposées.</p>').join('')+'</details>':'')+(s.order?'<h3>'+s.order.id+'</h3><p>Validée le '+esc(date(s.order.at))+' · '+s.order.status+'</p><label>Adresse mail du fournisseur<input id="order-email" type="email" value="'+esc(s.order.email||'commandes@apo.example')+'" '+(s.order.status==='Envoi simulé'?'disabled':'')+'></label><p>Adresse de test par défaut. Aucun message envoyé, même si tu renseignes une autre adresse.</p>'+button('Simuler l’envoi au fournisseur','orderSend',s.order.status==='Envoi simulé')+(s.order.status==='Envoi simulé'?'<p>Commande envoyée en simulation. La livraison est disponible dans Réceptions.</p>':''):'')+'</section>';}
function go(label,target){return '<button data-go="'+target+'">'+label+'</button>';}
function homeView(s){const next=!s.order?['Préparer la commande APO','restock']:s.order.status!=='Envoi simulé'?['Envoyer la commande APO','restock']:!s.receipt?['Réceptionner la livraison APO','receive']:!s.sale?['Créer le BL du garage','sales']:!s.invoice?['Facturer le BL du garage','sales']:!s.claim&&C.shortages(s).length?['Préparer la réclamation APO','claim']:s.claim&&s.claim.status!=='Envoi simulé'?['Envoyer la réclamation','claim']:s.claim&&!s.credit?['Consulter la réponse fournisseur','claim']:['Consulter les factures','office'];return '<section><h2>À faire</h2><p class="muted">Une commande fournisseur et une vente client pour essayer le parcours.</p>'+go(next[0],next[1])+'<div class="work-list"><div><strong>Achats</strong><span>APO · '+(s.order?s.order.id+' · '+s.order.status:'commande à préparer')+'</span>'+go('Ouvrir','restock')+'</div><div><strong>Réceptions</strong><span>'+(s.receipt?s.receipt.id+' · enregistrée':s.shipped?'Livraison APO attendue':'Aucune livraison attendue')+'</span>'+go('Ouvrir','receive')+'</div><div><strong>Vente comptoir</strong><span>Garage Démo Bayonne · '+(s.invoice?s.invoice.id:s.sale?s.sale.id:'vente à préparer')+'</span>'+go('Ouvrir','sales')+'</div><div><strong>Réclamations</strong><span>'+(s.credit?'Avoir APO reçu':s.claim?s.claim.status:s.receipt?C.shortages(s).reduce((n,p)=>n+p.missing,0)+' pièces manquantes':'Aucun écart constaté')+'</span>'+go('Ouvrir','claim')+'</div></div><details><summary>Comprendre cet essai</summary><p>APO fournit trois palettes PURFLUX, BOSCH et GATES. Son expédition et sa facture sont simulées automatiquement après l’envoi de ta commande. Tu travailles uniquement côté magasin. Les scans sont simulés, la progression reste sur cet appareil et les écritures sont illustratives.</p></details></section>';}
function stockView(s){return '<section><h2>Stock du magasin</h2><p>Quantités du scénario, indépendantes du catalogue réel.</p><div class="table-wrap"><table><thead><tr><th>Référence</th><th>Désignation</th><th>Entrées</th><th>Sorties</th><th>Disponible</th></tr></thead><tbody>'+C.products.map(p=>'<tr><td>'+p.brand+'<br>'+p.ref+'</td><td>'+p.name+'</td><td>'+(s.receipt?s.receipt.counts[p.id]:0)+'</td><td>'+(s.sale?p.sale:0)+'</td><td><strong>'+C.stock(s,p.id)+'</strong></td></tr>').join('')+'</tbody></table></div></section>';}
function render(){$('mobile-page').value=page;const s=state,missing=C.shortages(s),booked=s.journal.some(j=>j.id==='ACHAT');$('summary').innerHTML=[[s.order?ordered():0,'Pièces commandées'],[s.receipt?sum('received'):0,'Entrées validées'],[s.sale?12:0,'Pièces vendues'],[sum('stock'),'Stock du scénario']].map(([v,k])=>`<div><strong>${v}</strong><span>${k}</span></div>`).join('');document.querySelectorAll('[data-page]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.page===page)));
if(page==='home')$('view').innerHTML=homeView(s);
if(page==='stock')$('view').innerHTML=stockView(s);
if(page==='restock')$('view').innerHTML=restockView(s);
if(page==='supplier')$('view').innerHTML=`<section><small>ESPACE FOURNISSEUR · APO · SIMULATION</small><h2>Commande CMD-DEMO-001</h2><p>Créée le ${esc(date(s.createdAt))} · destination Bellecave (test).</p><div class="lines">${[1,2,3].map(i=>`<div class="line"><h3>Palette ${i} · ${C.products.find(p=>p.pallet===i).brand}</h3>${C.products.filter(p=>p.pallet===i).map(p=>`<p>${C.expected(s,p)} × ${p.name}<br><small>${p.ref}</small></p>`).join('')}</div>`).join('')}</div><p>Total commande : ${money(C.totals(s,'expected'))} HT. Références DEMO sans code-barres réel.</p><div class="actions">${button(s.shipped?'Trois palettes expédiées':'Simuler l’expédition des trois palettes','ship',s.shipped||s.order?.status!=='Envoi simulé')}${button(s.purchase?'Facture fournisseur reçue':'Simuler la facture reçue d’APO','purchase',!s.shipped||!!s.purchase)}</div><p>La facture du fournisseur porte ici sur les pièces commandées. Les manquants entraîneront une demande d’avoir.</p></section>`;
if(page==='receive')$('view').innerHTML=`<section><small>BELLECAVE · RÉCEPTION</small><h2>Pointer les trois palettes</h2><p>Commande CMD-DEMO-001 · BL-APO-DEMO-001. Les boutons ci-dessous simulent les scans ; tu peux corriger les quantités avant validation.</p><div class="actions">${[1,2,3].map(i=>button('Simuler les scans · palette '+i,'scan',!s.shipped||!!s.receipt,`data-pallet="${i}"`)).join('')}</div><div class="lines" style="margin-top:18px">${C.products.map(p=>`<div class="line"><h3>${p.brand} · ${p.name}</h3><small>${p.ref} · ${C.expected(s,p)} attendues</small><label>Quantité reçue<input data-count="${p.id}" type="number" min="0" max="${C.expected(s,p)}" step="1" value="${s.counts[p.id]}" ${!s.shipped||s.receipt?'disabled':''}></label><p>${C.expected(s,p)-s.counts[p.id]} non pointée(s)</p></div>`).join('')}</div><p class="tag">${sum('received')} reçues sur ${ordered()} · ${ordered()-sum('received')} non pointées. Après validation, les non pointées seront déclarées manquantes.</p>${button(s.receipt?'Réception enregistrée':'Valider les quantités et les manquants','receive',!s.shipped||!!s.receipt||!sum('received'))}${s.receipt?`<p>${esc(s.receipt.id)} · ${esc(date(s.receipt.at))}<br>${esc(s.receipt.actor)}</p>`:''}</section>`;
if(page==='sales')$('view').innerHTML=`<section><small>BELLECAVE · COMPTOIR</small><h2>Garage Démo Bayonne</h2><p>Client CLI-DEMO-001 · panier fixe de 12 pièces pour cet essai.</p><div class="lines">${C.products.map(p=>`<div class="line"><h3>${p.sale} × ${p.name}</h3><small>${p.brand} · ${p.ref}</small><p>${money(p.sell)} HT / unité<br>Stock disponible : ${C.stock(s,p.id)}</p></div>`).join('')}</div><div class="actions">${button(s.sale?'BL-DEMO-001 créé':'Valider le BL et sortir les pièces','sale',!s.receipt||!!s.sale)}${button(s.invoice?'FA-DEMO-001 créée':'Créer la facture du garage','invoice',!s.sale||!!s.invoice)}</div><p>Le BL diminue le stock. Sa facture crée les écritures de vente sans retirer les pièces une deuxième fois.</p>${s.invoice?`<p>Facture ${s.invoice.id} liée au ${s.invoice.bl} · ${money(s.invoice.ht)} HT + ${money(s.invoice.tax)} TVA = <strong>${money(s.invoice.ttc)} TTC</strong>.</p>`:''}</section>`;
if(page==='claim')$('view').innerHTML=`<section><small>BELLECAVE → APO · LITIGE</small><h2>Réclamer les articles manquants</h2><p>${s.receipt?missing.reduce((n,p)=>n+p.missing,0)+' pièce(s) manquante(s).':'Valide la réception pour constater les écarts.'}</p>${button('Préparer le courriel de réclamation','claim',!s.receipt||!missing.length||!!s.claim)}${s.claim?`<p>À : <strong>${esc(s.claim.to)}</strong> · adresse fictive réservée au test<br>Objet : ${esc(s.claim.subject)}</p><label>Courriel préparé<textarea readonly>${esc(s.claim.body)}</textarea></label><p>État : ${esc(s.claim.status)}</p><div class="actions">${button('Simuler l’envoi du courriel','send',s.claim.status==='Envoi simulé')}${button(s.credit?'Avoir fournisseur reçu':'Recevoir l’avoir APO · simulation','credit',!s.purchase||s.claim.status!=='Envoi simulé'||!!s.credit)}</div><p>L’avoir réduit la dette fournisseur. Il ne rajoute aucune pièce en stock.</p>`:''}${s.credit?`<p>Avoir ${s.credit.id} : ${money(s.credit.ht)} HT / ${money(s.credit.ttc)} TTC.</p>`:''}</section>`;
if(page==='office')$('view').innerHTML=`<section><small>BUREAUX · DOCUMENTS ET ÉCRITURES</small><h2>Factures et avoirs</h2><p>Commande CMD-DEMO-001 → ${s.receipt?s.receipt.id:'réception en attente'} → ${s.sale?s.sale.id:'vente en attente'} → ${s.invoice?s.invoice.id:'facture client en attente'}.</p><p>Facture APO : ${s.purchase?money(s.purchase.ttc)+' TTC · '+s.purchase.id:'non reçue'}<br>Avoir APO : ${s.credit?money(s.credit.ttc)+' TTC':'non reçu'}<br>Dette fournisseur après avoir : ${s.purchase?money(s.purchase.ttc-(s.credit?.ttc||0)):'—'}</p><p>${s.purchase&&s.receipt&&missing.length&&!s.credit?'Écart fournisseur ouvert : seules les pièces manquantes restent en litige. La facture peut être enregistrée.':''}</p>${button(booked?'Achat comptabilisé dans le journal simulé':'Enregistrer la facture fournisseur','book',booked||!s.purchase)}</section><section><h2>Stock par référence</h2><div class="lines">${C.products.map(p=>`<div class="line"><strong>${p.brand} · ${p.ref}</strong><p>${s.receipt?s.receipt.counts[p.id]:0} entrées − ${s.sale?p.sale:0} sorties = <strong>${C.stock(s,p.id)}</strong></p></div>`).join('')}</div></section><section><h2>Journal comptable illustratif</h2>${s.journal.map(j=>`<h3>${esc(j.title)}</h3><div class="table-wrap"><table><thead><tr><th>Poste</th><th>Débit</th><th>Crédit</th></tr></thead><tbody>${j.rows.map(r=>`<tr><td>${esc(r.account)}</td><td>${money(r.debit)}</td><td>${money(r.credit)}</td></tr>`).join('')}</tbody></table></div><p>Équilibre : ${money(j.rows.reduce((n,r)=>n+r.debit-r.credit,0))}</p>`).join('')||'<p>Aucune écriture. La réception seule ne crée pas de facture.</p>'}</section>`;
$('history').innerHTML=s.events.slice().reverse().map(e=>`<p><small>${esc(date(e.at))}</small><br>${esc(e.note)}</p>`).join('')||'<p>Commence par calculer les besoins dans Réappro.</p>';}
$('mobile-page').onchange=e=>{page=e.target.value;$('notice').textContent='';render();};
$('sections').onclick=e=>{const b=e.target.closest('[data-page]');if(b){page=b.dataset.page;$('notice').textContent='';render();}};
$('view').onclick=e=>{const target=e.target.closest('[data-go]');if(target){page=target.dataset.go;$('notice').textContent='';render();return;}const b=e.target.closest('[data-action]');if(!b||b.disabled)return;if(b.dataset.action==='receive'&&!confirm('Enregistrer '+sum('received')+' pièces et déclarer '+(ordered()-sum('received'))+' manquantes dans la simulation ?'))return;act(b.dataset.action,b.dataset.pallet?{pallet:Number(b.dataset.pallet)}:b.dataset.action==='orderSend'?{email:$('order-email').value}:{});};
$('view').onchange=e=>{if(e.target.dataset.orderqty){act('orderqty',{id:e.target.dataset.orderqty,quantity:e.target.value.trim()===''?NaN:Number(e.target.value)});render();}else if(e.target.dataset.count){act('count',{id:e.target.dataset.count,quantity:e.target.value.trim()===''?NaN:Number(e.target.value)});render();}};
$('reset').onclick=()=>{if(!confirm('Effacer uniquement la progression de ce scénario fictif sur cet appareil ?'))return;try{const next=C.initial(new Date().toISOString());localStorage.setItem(key,JSON.stringify(next));state=next;loadError=false;page='home';$('notice').textContent='Nouvelle simulation.';render();}catch{$('notice').textContent='Impossible de sauvegarder sur cet appareil.';}};
render();if(loadError)$('notice').textContent='Sauvegarde illisible. Utilise « Recommencer la simulation » pour repartir explicitement de zéro.';

if(new URLSearchParams(location.search).get('embedded')==='1')document.querySelectorAll('header a').forEach(el=>el.style.display='none');
