(function(root){'use strict';
const products=[
 {id:'PF1',brand:'PURFLUX',ref:'DEMO-PUR-001',name:'Filtre à huile',expected:20,received:18,buy:600,sell:1100,sale:3,pallet:1},
 {id:'PF2',brand:'PURFLUX',ref:'DEMO-PUR-002',name:'Filtre à air',expected:12,received:12,buy:1000,sell:1800,sale:2,pallet:1},
 {id:'BO1',brand:'BOSCH',ref:'DEMO-BOS-001',name:'Jeu de plaquettes',expected:10,received:9,buy:2500,sell:4200,sale:1,pallet:2},
 {id:'BO2',brand:'BOSCH',ref:'DEMO-BOS-002',name:'Bougie',expected:24,received:24,buy:400,sell:750,sale:4,pallet:2},
 {id:'GA1',brand:'GATES',ref:'DEMO-GAT-001',name:'Courroie accessoires',expected:8,received:7,buy:1400,sell:2400,sale:1,pallet:3},
 {id:'GA2',brand:'GATES',ref:'DEMO-GAT-002',name:'Kit de distribution',expected:6,received:6,buy:6500,sell:10000,sale:1,pallet:3}
];
const amounts=ht=>({ht,tax:Math.round(ht*.2),ttc:ht+Math.round(ht*.2)});
const expected=(s,p)=>s.order?s.order.quantities[p.id]:p.expected;
const totals=(s,field)=>products.reduce((n,p)=>n+(field==='expected'?expected(s,p):s.counts[p.id])*p.buy,0);
function initial(now){return {version:1,createdAt:now,draft:null,order:null,shipped:false,counts:Object.fromEntries(products.map(p=>[p.id,0])),receipt:null,sale:null,invoice:null,purchase:null,credit:null,claim:null,events:[],journal:[]};}
function stock(s,id){return (s.receipt?s.receipt.counts[id]:0)-(s.sale?s.sale.quantities[id]:0);}
function shortages(s){return products.map(p=>({...p,expected:expected(s,p),missing:expected(s,p)-(s.receipt?s.receipt.counts[p.id]:s.counts[p.id])})).filter(p=>p.missing>0);}
function entry(s,id,title,rows){if(s.journal.some(x=>x.id===id))return;s.journal.push({id,title,rows});}
function bookCredit(s){const c=s.credit;if(c&&s.journal.some(j=>j.id==='ACHAT'))entry(s,'AVOIR','Avoir fournisseur de démonstration',[{account:'Dette fournisseur',debit:c.ttc,credit:0},{account:'Achats',debit:0,credit:c.ht},{account:'TVA déductible simulée',debit:0,credit:c.tax}]);}
function transition(old,action,now){const s=JSON.parse(JSON.stringify(old));let note='';
 const need=(yes,msg)=>{if(!yes)throw Error(msg);};
 if(action.type==='replenish'){need(!s.order&&!s.shipped,'Commande déjà engagée.');s.draft=Object.fromEntries(products.map(p=>[p.id,Math.max(0,Math.ceil((p.expected*2/10)*5))]));note='Besoins calculés pour APO : ventes fictives sur 10 jours, couverture 5 jours, stock et attendus initiaux nuls.';}
 else if(action.type==='orderqty'){need(s.draft&&!s.order,'Calculer les besoins avant de choisir les pièces.');need(products.some(p=>p.id===action.id)&&Number.isInteger(action.quantity)&&action.quantity>=0&&action.quantity<=1000,'Quantité à commander invalide.');s.draft[action.id]=action.quantity;return s;}
 else if(action.type==='order'){if(s.order)return s;need(s.draft&&Object.values(s.draft).some(n=>n>0),'Sélectionner au moins une pièce.');s.order={id:'CMD-DEMO-001',at:now,quantities:{...s.draft},status:'Validée',supplier:'APO',email:''};note='CMD-DEMO-001 créée et validée pour APO. Courriel à préparer.';}
 else if(action.type==='orderSend'){need(s.order,'Valider la commande.');if(s.order.status==='Envoi simulé')return s;const email=String(action.email||'').trim();need(/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email),'Renseigner une adresse mail valide.');s.order.email=email;s.order.status='Envoi simulé';s.order.sentAt=now;note='Commande '+s.order.id+' : envoi simulé. Aucun courriel réel transmis.';}
 else if(action.type==='ship'){if(s.shipped)return s;need(s.order?.status==='Envoi simulé','Valider et simuler l’envoi du réappro avant l’expédition.');s.shipped=true;note='APO : palettes expédiées, BL-APO-DEMO-001.';}
 else if(action.type==='scan'){need(s.shipped,'Expédier les palettes avant de pointer.');need(!s.receipt,'Réception déjà validée.');need([1,2,3].includes(action.pallet),'Palette inconnue.');for(const p of products.filter(p=>p.pallet===action.pallet))s.counts[p.id]=Math.max(0,expected(s,p)-(p.expected-p.received));note='Palette '+action.pallet+' : scan simulé des quantités du scénario.';}
 else if(action.type==='count'){need(s.shipped&&!s.receipt,'Pointage fermé ou livraison non expédiée.');const p=products.find(p=>p.id===action.id);need(p&&Number.isInteger(action.quantity)&&action.quantity>=0&&action.quantity<=expected(s,p),'Quantité invalide ou supérieure à la commande.');s.counts[p.id]=action.quantity;return s;}
 else if(action.type==='receive'){if(s.receipt)return s;need(s.shipped,'Aucune livraison expédiée.');need(Object.values(s.counts).some(x=>x>0),'Pointer au moins une pièce.');s.receipt={id:'REC-DEMO-001',at:now,actor:'Alexis · pointeur de démonstration',counts:{...s.counts}};note='Bellecave : réception validée. Les quantités reçues entrent en stock ; les manquants restent à traiter.';}
 else if(action.type==='sale'){if(s.sale)return s;need(s.receipt,'Valider la réception avant la vente.');need(products.every(p=>stock(s,p.id)>=p.sale),'Stock insuffisant pour le panier du garage.');s.sale={id:'BL-DEMO-001',at:now,client:'Garage Démo Bayonne',clientCode:'CLI-DEMO-001',quantities:Object.fromEntries(products.map(p=>[p.id,p.sale]))};note='BL-DEMO-001 : 12 pièces sorties pour Garage Démo Bayonne. Facturation en attente.';}
 else if(action.type==='invoice'){if(s.invoice)return s;need(s.sale,'Créer le BL avant de facturer.');const sum=amounts(products.reduce((n,p)=>n+p.sale*p.sell,0));s.invoice={id:'FA-DEMO-001',at:now,bl:s.sale.id,...sum};entry(s,s.invoice.id,'Facture client de démonstration',[{account:'Créance client',debit:sum.ttc,credit:0},{account:'Ventes',debit:0,credit:sum.ht},{account:'TVA collectée simulée',debit:0,credit:sum.tax}]);note='Facture client créée, écritures simulées équilibrées. Aucun nouveau mouvement de stock.';}
 else if(action.type==='purchase'){if(s.purchase)return s;need(s.shipped,'Attendre l’expédition.');s.purchase={id:'FA-APO-DEMO-001',at:now,...amounts(totals(s,'expected'))};note='Facture fournisseur reçue pour toutes les pièces commandées. Rapprochement requis.';}
 else if(action.type==='claim'){if(s.claim)return s;need(s.receipt,'Valider la réception pour constater les manquants.');const missing=shortages(s);need(missing.length,'Aucun manquant à réclamer.');s.claim={id:'REC-LIT-DEMO-001',at:now,status:'Brouillon',to:'reclamations@apo.example',subject:'SIMULATION — manquants CMD-DEMO-001 / BL-APO-DEMO-001',body:'SIMULATION — AUCUN ENVOI RÉEL\n\nFournisseur : APO (scénario fictif)\nMagasin : Bellecave (espace de test)\nCommande : CMD-DEMO-001 du '+(s.order?.at||s.createdAt)+'\nBon fournisseur : BL-APO-DEMO-001\nRéception : '+s.receipt.id+' du '+s.receipt.at+'\nPointeur : '+s.receipt.actor+'\n\n'+missing.map(p=>p.brand+' / '+p.ref+' : commandé '+p.expected+', reçu '+s.receipt.counts[p.id]+', manquant '+p.missing).join('\n')+'\n\nMerci de confirmer un remplacement ou un avoir pour ces écarts.'};note='Réclamation préparée automatiquement à partir de la réception.';}
 else if(action.type==='send'){need(s.claim,'Préparer la réclamation.');if(s.claim.status==='Envoi simulé')return s;s.claim.status='Envoi simulé';s.claim.sentAt=now;note='Courriel placé dans la boîte d’envoi de test. Aucun message envoyé à APO.';}
 else if(action.type==='credit'){if(s.credit)return s;need(s.purchase&&s.claim?.status==='Envoi simulé','Recevoir la facture fournisseur et simuler la réclamation avant sa réponse.');s.credit={id:'AV-APO-DEMO-001',at:now,...amounts(totals(s,'expected')-totals(s,'received'))};bookCredit(s);note='APO : avoir simulé pour les manquants, écriture distincte si la facture est enregistrée. Aucune entrée physique supplémentaire.';}
 else if(action.type==='book'){if(s.journal.some(x=>x.id==='ACHAT'))return s;need(s.purchase,'Facture fournisseur nécessaire.');const p=s.purchase;entry(s,'ACHAT','Facture fournisseur de démonstration',[{account:'Achats',debit:p.ht,credit:0},{account:'TVA déductible simulée',debit:p.tax,credit:0},{account:'Dette fournisseur',debit:0,credit:p.ttc}]);bookCredit(s);note='Facture fournisseur enregistrée. Les éventuels manquants restent suivis séparément, sans blocage comptable.';}
 else throw Error('Action inconnue.');
 s.events.push({at:now,note});return s;
}
function validate(s){if(!s||s.version!==1||!s.counts||!Array.isArray(s.events)||!Array.isArray(s.journal))throw Error('Sauvegarde de démonstration invalide.');for(const p of products){const n=s.counts[p.id];if(!Number.isInteger(n)||n<0||n>expected(s,p))throw Error('Quantité sauvegardée invalide.');}return s;}
const api={products,initial,transition,stock,shortages,totals,amounts,validate,expected};if(typeof module!=='undefined')module.exports=api;else root.Scenario=api;
})(typeof globalThis!=='undefined'?globalThis:this);
