(()=>{'use strict';

const db=supabase.createClient('https://pryocchvwmnuoidtitow.supabase.co','sb_publishable_AQ9cr2Z7Kr6EAravVOgB9Q_Z5Mx2yOZ'),shop='8770297c-cadb-4cc6-8b93-55a0f9bd154e',$=id=>document.getElementById(id);
let actor=null,admin=false,epoch=0,rows=[],selected=null,busy=false,dirty=false;
const norm=v=>String(v).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
function mark(value){dirty=value;if(window.parent!==window)window.parent.postMessage({type:'alcorb-dirty',dirty},location.origin);}
function clear(){epoch++;actor=null;admin=false;rows=[];selected=null;mark(false);$('team').hidden=true;$('edit').hidden=true;$('edit').reset();$('people').replaceChildren();$('saved').textContent='';}

function paint(){const q=norm($('search').value),list=rows.filter(r=>norm(r.display_name).includes(q));$('people').replaceChildren();$('count').textContent=list.length+' / '+rows.length+' fiche(s) · '+rows.filter(r=>r.user_id).length+' accès existant(s) au total';for(const row of list){const b=document.createElement('button');b.className='person';const homonyms=rows.filter(r=>r.display_name===row.display_name).sort((a,b)=>a.id.localeCompare(b.id));b.textContent=row.display_name+(homonyms.length>1?' ('+(homonyms.findIndex(r=>r.id===row.id)+1)+')':'');const small=document.createElement('small');small.textContent=(row.user_id?'Accès existant':'À activer');b.append(small);b.onclick=()=>open(row);$('people').append(b);}}
function open(row){if(busy)return;if(dirty&&!confirm('Remplacer les modifications non enregistrées ?'))return;selected={...row};$('edit').hidden=false;$('title').textContent=row.display_name||'Nouvelle personne';$('name').value=row.display_name||'';$('email').value=row.contact_email||'';$('notes').value=row.notes||'';$('fields').disabled=!admin;$('access').textContent=row.user_id?'Lié à un compte existant. Ses permissions de connexion sont gérées séparément.':'Fiche préparée · aucun accès de connexion actif. L’activation du compte reste à organiser.';$('saved').textContent='';mark(false);}
async function load(){const token=++epoch;try{const r=await db.from('gestion_team').select('*').eq('workspace_id',shop).order('display_name');if(token!==epoch)return;if(r.error)throw r.error;rows=r.data||[];$('team').hidden=false;$('new').hidden=!admin;paint();$('status').textContent=admin?'Équipe privée du magasin. Les fiches sont enregistrées en base.':'Votre fiche personnelle. L’administrateur de l’application gère les fiches.';}catch{if(token===epoch)$('status').textContent='Équipe indisponible. Réessayez sans ressaisir les personnes.';}}
async function enter(s){const next=s?.user?.id||null;if(next===actor)return;clear();actor=next;if(!actor){$('status').textContent='Connectez-vous depuis l’espace magasin.';return;}const token=epoch;const r=await db.from('scanette_members').select('role').eq('workspace_id',shop).eq('user_id',actor).maybeSingle();if(token!==epoch)return;if(r.error||!r.data){$('status').textContent='Accès non confirmé.';return;}admin=r.data.role==='admin';load();}
$('search').oninput=paint;$('edit').addEventListener('input',()=>mark(true));$('new').onclick=()=>{if(admin)open({id:crypto.randomUUID(),version:0,functions:[]});};
$('edit').onsubmit=async e=>{e.preventDefault();if(!admin||!selected||busy)return;const token=epoch,request={shop_id:shop,member_id:selected.id,expected_version:selected.version,member_name:$('name').value.trim(),member_functions:[],member_email:$('email').value.trim(),member_notes:$('notes').value.trim()};busy=true;$('fields').disabled=true;try{const r=await db.rpc('gestion_save_team_member',request);if(token!==epoch)return;if(r.error){$('saved').textContent=r.error.code==='40001'?'Fiche modifiée ailleurs. Rechargez avant de réappliquer vos changements.':'Enregistrement non confirmé. Rechargez pour vérifier avant de réessayer.';return;}const row=Array.isArray(r.data)?r.data[0]:r.data;if(!row?.id)throw Error();selected=row;const i=rows.findIndex(x=>x.id===row.id);if(i<0)rows.push(row);else rows[i]=row;mark(false);paint();$('saved').textContent='Fiche enregistrée · version '+row.version+' · '+new Date(row.updated_at).toLocaleString('fr-FR');}catch{if(token===epoch)$('saved').textContent='Enregistrement non confirmé. Vérifiez le résultat en rechargeant.';}finally{busy=false;if(token===epoch)$('fields').disabled=!admin;}};
$('reload').onclick=async()=>{if(busy||dirty&&!confirm('Recharger et remplacer vos modifications non enregistrées ?'))return;$('edit').hidden=true;mark(false);await load();};
db.auth.onAuthStateChange((_event,s)=>setTimeout(()=>enter(s),0));db.auth.getSession().then(r=>enter(r.data.session));
})();
