(function(scope){
 'use strict';
 const modules={home:'Mon espace',sale:'Comptoir',documents:'BL, factures & avoirs',clients:'Clients',stock:'Catalogue & stock',receive:'Réceptions',dispatch:'Départs',stats:'Mon activité',suppliers:'Fournisseurs',restock:'Réapprovisionnement',purchases:'Achats & tarifs',payments:'Règlements & relances',accounting:'Comptabilité',workshop:'Atelier',portal:'Portail clients',directory:'Annuaire de partenaires',scenario:'Essai APO complet',realtools:'Scanette et stock réels'};
 const roles={sales:{label:'Vendeur',description:'Vendre, retrouver un client et suivre ses documents.',menus:['sale','clients','documents','stock','portal','stats']},accounting:{label:'Comptabilité',description:'Retrouver les factures, les règlements et les écritures.',menus:['accounting','documents','payments','purchases','clients','suppliers']},logistics:{label:'Logistique',description:'Réceptionner, consulter le stock et organiser les départs.',menus:['receive','dispatch','stock','realtools','suppliers','restock']},purchasing:{label:'Achats',description:'Préparer le réapprovisionnement et suivre les fournisseurs.',menus:['restock','purchases','suppliers','stock','directory']},management:{label:'Direction',description:'Suivre l’activité et accéder aux services du magasin.',menus:['stats','documents','accounting','payments','stock','restock','clients','suppliers']}};
 function clean(raw){const state={role:Object.hasOwn(roles,raw?.role)?raw.role:'sales',menus:{}};for(const id of Object.keys(roles)){const list=raw?.menus?.[id];state.menus[id]=Array.isArray(list)?[...new Set(list.filter(x=>x!=='home'&&Object.hasOwn(modules,x)))]:[...roles[id].menus];}return state;}
 function toggle(state,id){if(!Object.hasOwn(modules,id)||id==='home')return;const list=state.menus[state.role],index=list.indexOf(id);if(index<0)list.push(id);else list.splice(index,1);}
 function create(host){
  const root=host.root,nav=root.querySelector('nav'),main=root.querySelector('.ag-main'),mobile=root.querySelector('#ag-section-choice');
  const bar=document.createElement('section');bar.className='ws-bar';bar.setAttribute('aria-label','Mon espace de travail');main.insertBefore(bar,main.querySelector('.mobile-section'));
  let store='',state=clean(),open=false,warning='',page='home';const key=id=>'alcorb-workspace-v1-'+id;
  function load(id){store=id;open=false;warning='';try{state=clean(JSON.parse(localStorage.getItem(key(id))||'null'));}catch{state=clean();warning='Préférences indisponibles : les menus par défaut sont affichés.';}}
  function save(){try{localStorage.setItem(key(store),JSON.stringify(state));warning='';}catch{warning='Les préférences ne peuvent pas être sauvegardées sur cet appareil.';}}
  function sync(id,current){if(id!==store)load(id);page=current;const selected=state.menus[state.role];
   nav.innerHTML='<p class="menu-group-title">'+roles[state.role].label+'</p>'+['home',...selected].map(id=>'<button data-page="'+id+'" '+(page===id?'aria-current="page"':'')+'>'+modules[id]+'</button>').join('');
   const visible=['home',...selected];if(!visible.includes(page)&&modules[page])visible.push(page);
   mobile.innerHTML=visible.map(id=>'<option value="'+id+'">'+modules[id]+(id===page&&!selected.includes(id)&&id!=='home'?' · accès ponctuel':'')+'</option>').join('');mobile.value=page;
   bar.innerHTML='<div class="ws-toolbar"><label class="ag-label">Mon métier<select id="ws-role" class="ag-field">'+Object.entries(roles).map(([id,r])=>'<option value="'+id+'" '+(id===state.role?'selected':'')+'>'+r.label+'</option>').join('')+'</select></label><button class="ag-action ag-secondary" data-ws="customize" aria-expanded="'+open+'" aria-controls="ws-customize">'+(open?'Fermer la personnalisation':'＋ / − Mes menus')+'</button></div>'+(warning?'<p role="alert">'+warning+'</p>':'')+(open?'<div id="ws-customize" class="ws-customize"><div class="ag-row"><h2>Mes menus · '+roles[state.role].label+'</h2><button class="ag-action ag-secondary" data-ws="reset">Revenir aux menus proposés</button></div><p>Ajoutez vos raccourcis avec +, retirez-les avec −. Les opérations et documents sont conservés.</p><div class="ws-picker">'+Object.entries(modules).filter(([id])=>id!=='home').map(([id,label])=>'<div><span>'+label+'</span><button data-ws="toggle" data-module="'+id+'" aria-label="'+(selected.includes(id)?'Retirer ':'Ajouter ')+label+'" aria-pressed="'+selected.includes(id)+'">'+(selected.includes(id)?'−':'+')+'</button></div>').join('')+'</div><small>Préférences de démonstration sur cet appareil, par magasin et métier. Ce choix ne modifie pas les autorisations.</small></div>':'');
  }
  bar.addEventListener('input',e=>e.stopPropagation());
  bar.addEventListener('change',e=>{e.stopPropagation();if(e.target.id==='ws-role'&&Object.hasOwn(roles,e.target.value)){state.role=e.target.value;open=false;save();host.navigate('home');}});
  bar.addEventListener('click',e=>{e.stopPropagation();const b=e.target.closest('button[data-ws]');if(!b)return;const action=b.dataset.ws,id=b.dataset.module;if(action==='customize')open=!open;else if(action==='toggle')toggle(state,id);else if(action==='reset')state.menus[state.role]=[...roles[state.role].menus];save();host.repaint();const focus=action==='toggle'?bar.querySelector('[data-module="'+id+'"]'):bar.querySelector('[data-ws="'+action+'"]');focus?.focus();});
  function home(){const role=roles[state.role];return '<section class="ws-welcome"><small>MON ESPACE · '+role.label.toUpperCase()+'</small><h1>Que souhaitez-vous faire ?</h1><p>'+role.description+'</p></section><div class="ws-shortcuts">'+state.menus[state.role].map((id,i)=>'<button data-page="'+id+'"><span class="ws-number">'+String(i+1).padStart(2,'0')+'</span><span>'+modules[id]+'</span><span aria-hidden="true">↗</span></button>').join('')+'</div>'+(state.menus[state.role].length?'':'<p class="ag-panel ag-pad">Votre espace est vide. Utilisez « ＋ / − Mes menus » pour ajouter un raccourci.</p>');}
  return {sync,home};
 }
 const api={modules,roles,clean,toggle,create};if(typeof module!=='undefined')module.exports=api;else scope.Workspaces=api;
})(globalThis);
