(function(scope){
 'use strict';
 const modules={home:'Mon espace',sale:'Comptoir',documents:'BL, factures & avoirs',clients:'Clients',stock:'Catalogue & stock',receive:'Réceptions',dispatch:'Départs',stats:'Mon activité',storestats:'Statistiques magasin',suppliers:'Fournisseurs',restock:'Réapprovisionnement',purchases:'Achats & tarifs',payments:'Règlements & relances',accounting:'Comptabilité',workshop:'Atelier',portal:'Portail clients',directory:'Annuaire de partenaires',scenario:'Essai APO complet',realtools:'Scanette et stock réels'};
 const roles={commercial:{label:'Commercial',description:'Retrouver les garages suivis. Le suivi des visites sera ajouté dans une prochaine phase.',menus:['clients','documents','storestats']},sales:{label:'Vendeur',description:'Vendre, retrouver un client et suivre ses documents.',menus:['sale','clients','documents','stock','portal','stats']},accounting:{label:'Comptabilité',description:'Retrouver les factures, les règlements et les écritures.',menus:['accounting','documents','payments','purchases','clients','suppliers']},logistics:{label:'Logistique',description:'Réceptionner, consulter le stock et organiser les départs.',menus:['receive','dispatch','stock','realtools','suppliers','restock']},purchasing:{label:'Achats',description:'Préparer le réapprovisionnement et suivre les fournisseurs.',menus:['restock','purchases','suppliers','stock','directory']},management:{label:'Direction',description:'Suivre l’activité et accéder aux services du magasin.',menus:['storestats','stats','documents','accounting','payments','stock','restock','clients','suppliers']}};
 function clean(raw){const state={role:Object.hasOwn(roles,raw?.role)?raw.role:'sales',menus:{}};for(const id of Object.keys(roles)){const list=raw?.menus?.[id];state.menus[id]=Array.isArray(list)?[...new Set(list.filter(x=>x!=='home'&&Object.hasOwn(modules,x)))]:[...roles[id].menus];}return state;}
 function toggle(state,id){if(!Object.hasOwn(modules,id)||id==='home')return;const list=state.menus[state.role],index=list.indexOf(id);if(index<0)list.push(id);else list.splice(index,1);}

 const E=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 function safeLink(value){try{const u=new URL(value);return u.protocol==='https:'&&!u.username&&!u.password?u.href:'';}catch{return '';}}
 function people(raw,legacy){
  const seen=new Set();const list=(Array.isArray(raw?.people)?raw.people:[]).filter(p=>p&&/^person-[a-z0-9-]+$/.test(p.id)&&!seen.has(p.id)&&seen.add(p.id)).map(p=>({id:p.id,name:String(p.name||'Profil').slice(0,80),code:/^[A-Z0-9-]{1,60}$/.test(p.code)?p.code:'DEMO-'+p.id.slice(-8).toUpperCase(),preferences:clean(p.preferences),links:(Array.isArray(p.links)?p.links:[]).filter(l=>l&&safeLink(l.url)).map(l=>({name:String(l.name||'Catalogue').slice(0,60),url:safeLink(l.url)}))}));
  if(!list.length)list.push({id:'person-alexis',name:'Alexis · démo',code:'M017',preferences:clean(legacy),links:[]});
  return {version:2,active:list.some(p=>p.id===raw?.active)?raw.active:list[0].id,people:list};
 }
 function create(host){
  const root=host.root,nav=root.querySelector('nav'),main=root.querySelector('.ag-main'),mobile=root.querySelector('#ag-section-choice');
  const bar=document.createElement('section');bar.className='ws-bar';bar.setAttribute('aria-label','Mon espace de travail');main.insertBefore(bar,main.querySelector('.mobile-section'));
  let store='',state=clean(),book=people(),open=false,teamOpen=false,warning='',page='home';const key=id=>'alcorb-workspace-v2-'+id;
  const person=()=>book.people.find(p=>p.id===book.active);
  function load(id){store=id;open=false;teamOpen=false;warning='';try{book=people(JSON.parse(localStorage.getItem(key(id))||'null'),JSON.parse(localStorage.getItem('alcorb-workspace-v1-'+id)||'null'));}catch{book=people();warning='Préférences indisponibles : profil de démonstration affiché.';}state=person().preferences;}
  function save(){try{localStorage.setItem(key(store),JSON.stringify(book));warning='';}catch{warning='Les préférences ne peuvent pas être sauvegardées sur cet appareil.';}}
  function team(){return '<div class="ws-customize"><h2>Profils individuels · démonstration</h2><p>Chaque personne conserve ses menus et liens. Ces profils locaux ne sont pas des comptes authentifiés.</p><form id="ws-person-form" class="ag-form"><label class="ag-label">Nom de la personne<input class="ag-field" name="personName" maxlength="80" required></label><label class="ag-label">Métier initial<select class="ag-field" name="personRole">'+Object.entries(roles).map(([id,r])=>'<option value="'+id+'" '+(id==='sales'?'selected':'')+'>'+r.label+'</option>').join('')+'</select></label><button class="ag-action" type="submit">Créer ce profil de démonstration</button></form></div>';}
  function linkEditor(){return '<section class="ws-links"><h2>Mes catalogues et sites fournisseurs</h2><p>Ouverture dans un nouvel onglet. Vos abonnements et connexions restent gérés par chaque site.</p>'+person().links.map((l,i)=>'<div class="ag-row"><a href="'+E(l.url)+'" target="_blank" rel="noopener noreferrer">'+E(l.name)+' ↗</a><button class="ag-action ag-secondary" data-ws="unlink" data-index="'+i+'" aria-label="Retirer le lien '+E(l.name)+'">−</button></div>').join('')+'<form id="ws-link-form" class="ag-form"><label class="ag-label">Nom du raccourci<input name="linkName" class="ag-field" maxlength="60" placeholder="TecDoc, fournisseur…" required></label><label class="ag-label">Adresse HTTPS du site<input name="linkUrl" class="ag-field" type="url" placeholder="https://…" required></label><button class="ag-action" type="submit">+ Ajouter ce site</button></form><a href="https://www.tecalliance.net/fr/produits/cartes/tecdoc-catalogue" target="_blank" rel="noopener noreferrer">TecDoc · présentation officielle ↗</a></section>';}
  function sync(id,current){if(id!==store)load(id);page=current;const selected=state.menus[state.role];
   nav.innerHTML='<p class="menu-group-title">'+roles[state.role].label+'</p>'+['home',...selected].map(id=>'<button data-page="'+id+'" '+(page===id?'aria-current="page"':'')+'>'+modules[id]+'</button>').join('');
   const visible=['home',...selected];if(!visible.includes(page)&&modules[page])visible.push(page);
   mobile.innerHTML=visible.map(id=>'<option value="'+id+'">'+modules[id]+(id===page&&!selected.includes(id)&&id!=='home'?' · accès ponctuel':'')+'</option>').join('');mobile.value=page;
   const identity=root.querySelector('.ag-top-right');if(identity)identity.innerHTML='<span class="ag-demo">DÉMONSTRATION</span><div>'+E(person().name)+'<small>'+E(person().code)+' · profil local</small></div>';
   bar.innerHTML='<div class="ws-toolbar"><label class="ag-label">Mon profil<select id="ws-person" class="ag-field">'+book.people.map(p=>'<option value="'+p.id+'" '+(p.id===book.active?'selected':'')+'>'+E(p.name)+'</option>').join('')+'</select></label><label class="ag-label">Mon métier<select id="ws-role" class="ag-field">'+Object.entries(roles).map(([id,r])=>'<option value="'+id+'" '+(id===state.role?'selected':'')+'>'+r.label+'</option>').join('')+'</select></label><button class="ag-action ag-secondary" data-ws="customize" aria-expanded="'+open+'" aria-controls="ws-customize">'+(open?'Fermer la personnalisation':'＋ / − Mes menus')+'</button><button class="ag-action ag-secondary" data-ws="team" aria-expanded="'+teamOpen+'">Profils de l’équipe</button></div>'+(teamOpen?team():'')+(warning?'<p role="alert">'+warning+'</p>':'')+(open?'<div id="ws-customize" class="ws-customize"><div class="ag-row"><h2>Mes menus · '+roles[state.role].label+'</h2><button class="ag-action ag-secondary" data-ws="reset">Revenir aux menus proposés</button></div><p>Ajoutez vos raccourcis avec +, retirez-les avec −. Les opérations et documents sont conservés.</p><div class="ws-picker">'+Object.entries(modules).filter(([id])=>id!=='home').map(([id,label])=>'<div><span>'+label+'</span><button data-ws="toggle" data-module="'+id+'" aria-label="'+(selected.includes(id)?'Retirer ':'Ajouter ')+label+'" aria-pressed="'+selected.includes(id)+'">'+(selected.includes(id)?'−':'+')+'</button></div>').join('')+'</div><small>Préférences de ce profil sur cet appareil, dans ce magasin. Ce choix ne modifie pas les autorisations.</small>'+linkEditor()+'</div>':'');
  }
  bar.addEventListener('input',e=>e.stopPropagation());
  bar.addEventListener('change',e=>{e.stopPropagation();if(e.target.id==='ws-person'&&book.people.some(p=>p.id===e.target.value)){book.active=e.target.value;state=person().preferences;open=false;teamOpen=false;save();host.navigate('home');return;}if(e.target.id==='ws-role'&&Object.hasOwn(roles,e.target.value)){state.role=e.target.value;open=false;save();host.navigate('home');}});
  bar.addEventListener('click',e=>{e.stopPropagation();const b=e.target.closest('button[data-ws]');if(!b)return;const action=b.dataset.ws,id=b.dataset.module;if(action==='team')teamOpen=!teamOpen;else if(action==='unlink'){const index=Number(b.dataset.index);if(Number.isInteger(index)&&index>=0)person().links.splice(index,1);}else if(action==='customize')open=!open;else if(action==='toggle')toggle(state,id);else if(action==='reset')state.menus[state.role]=[...roles[state.role].menus];save();host.repaint();const focus=action==='toggle'?bar.querySelector('[data-module="'+id+'"]'):bar.querySelector('[data-ws="'+action+'"]');focus?.focus();});
  bar.addEventListener('submit',e=>{e.preventDefault();e.stopPropagation();const form=e.target;
   if(form.id==='ws-person-form'){const name=form.elements.personName.value.trim(),role=form.elements.personRole.value;if(!name||!Object.hasOwn(roles,role))return;const id='person-'+crypto.randomUUID();const preferences=clean({role});book.people.push({id,name:name.slice(0,80),code:'DEMO-'+id.slice(-8),preferences,links:[]});book.active=id;state=preferences;teamOpen=false;open=false;save();host.navigate('home');}
   if(form.id==='ws-link-form'){const url=safeLink(form.elements.linkUrl.value.trim()),name=form.elements.linkName.value.trim();if(!url||!name){warning='Indiquez un nom et une adresse HTTPS sans identifiants dans le lien.';host.repaint();return;}if(!person().links.some(l=>l.url===url))person().links.push({name:name.slice(0,60),url});save();host.repaint();}
  });
  function home(){const role=roles[state.role];return '<section class="ws-welcome"><small>MON ESPACE · '+role.label.toUpperCase()+'</small><h1>'+E(person().name)+'</h1><p>'+role.description+'</p></section><div class="ws-shortcuts">'+state.menus[state.role].map((id,i)=>'<button data-page="'+id+'"><span class="ws-number">'+String(i+1).padStart(2,'0')+'</span><span>'+modules[id]+'</span><span aria-hidden="true">↗</span></button>').join('')+'</div>'+(person().links.length?'<section class="ag-panel ag-pad ws-links"><h2>Mes catalogues</h2>'+person().links.map(l=>'<a class="ag-action ag-secondary" href="'+E(l.url)+'" target="_blank" rel="noopener noreferrer">'+E(l.name)+' ↗</a>').join('')+'</section>':'')+(state.menus[state.role].length?'':'<p class="ag-panel ag-pad">Votre espace est vide. Utilisez « ＋ / − Mes menus » pour ajouter un raccourci.</p>');}
  return {sync,home,person:()=>({...person(),role:state.role}),people:()=>book.people.map(p=>({id:p.id,name:p.name,code:p.code,role:p.preferences.role}))};
 }
 const api={modules,roles,clean,toggle,safeLink,people,create};if(typeof module!=='undefined')module.exports=api;else scope.Workspaces=api;
})(globalThis);
