(()=>{'use strict';const C=InventoryCore,S=InventoryStorage,$=id=>document.getElementById(id);
const endpoint='https://pryocchvwmnuoidtitow.supabase.co/rest/v1/rpc/inventory_read_invite',key='sb_publishable_AQ9cr2Z7Kr6EAravVOgB9Q_Z5Mx2yOZ';
let catalogue=[],listTitle='',draft=null,revision=0,page=0,scanner=null,starting=false,cameraGeneration=0,queue=Promise.resolve(),failed=false,unsaved=false,version=0,savedVersion=0,unknownCode='',cooldown=C.gate(),audio;
function message(text,isError=false){$('message').textContent=text;$('message').className='status'+(isError?' error':'');}
function download(name,text,type){const url=URL.createObjectURL(new Blob([text],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function dirty(value){if(window.parent!==window)window.parent.postMessage({type:'alcorb-dirty',dirty:value},location.origin);}
function save(){if(!draft)return Promise.resolve();unsaved=true;dirty(true);const snapshot=structuredClone(draft),stamp=version;$('saveStatus').textContent='Sauvegarde sur ce téléphone…';
 queue=queue.then(async()=>{if(failed)return;try{const result=await S.save(snapshot,revision);revision=result.revision;savedVersion=stamp;unsaved=version!==stamp;dirty(unsaved);$('saveStatus').textContent='✓ Enregistré sur ce téléphone à '+new Date(result.updatedAt).toLocaleTimeString('fr-FR');$('saveStatus').className='success';}catch(e){failed=true;unsaved=true;$('saveStatus').textContent=e.message;$('saveStatus').className='error';await stopCamera();message(e.message,true);}});return queue;
}
function changed(){version++;save();summary();}
function summary(){if(!draft)return;const n=draft.lines.filter(r=>r.quantity!==null).length;$('count').textContent=n+' / '+draft.lines.length+' références comptées · '+draft.lines.reduce((sum,r)=>sum+(r.quantity||0),0)+' pièces';$('progress').max=draft.lines.length||1;$('progress').value=n;$('undo').disabled=!draft.undo?.length;$('scanUndo').disabled=!draft.undo?.length;}
function validInputs(){const bad=$('lines').querySelector('input:invalid');if(bad){bad.reportValidity();message('Corrigez la quantité signalée avant de continuer.',true);return false;}return true;}
function render(){if(!draft)return;const q=C.norm($('search').value),rows=draft.lines.filter(r=>C.norm(r.reference+' '+r.description+' '+r.location).includes(q));page=Math.max(0,Math.min(page,Math.ceil(rows.length/60)-1));$('lines').replaceChildren();
 for(const r of rows.slice(page*60,(page+1)*60)){const a=document.createElement('article');a.className='count-line'+(r.quantity!==null?' counted':'')+(r.id===draft.lastId?' last':'');const info=document.createElement('div'),ref=document.createElement('strong'),desc=document.createElement('p'),loc=document.createElement('small');ref.textContent=r.reference;desc.textContent=r.description;loc.textContent=(r.location||'Emplacement non renseigné')+(r.added?' · Ajout pendant inventaire':'');info.append(ref,desc,loc);const label=document.createElement('label');label.textContent='Quantité comptée';const input=document.createElement('input');input.type='number';input.inputMode='numeric';input.min='0';input.max='1000000';input.step='1';input.value=r.quantity??'';input.setAttribute('aria-label','Quantité comptée pour '+r.reference);input.addEventListener('input',()=>{try{if(input.validity.badInput)throw Error('Nombre entier attendu');const value=C.quantity(input.value);input.setCustomValidity('');C.change(draft,r.id,value);a.classList.toggle('counted',value!==null);changed();}catch(e){input.setCustomValidity(e.message);input.reportValidity();dirty(true);}});label.append(input);a.append(info,label);$('lines').append(a);}
 $('page').textContent='Page '+(page+1)+' / '+Math.max(1,Math.ceil(rows.length/60));$('previous').disabled=page===0;$('next').disabled=(page+1)*60>=rows.length;summary();
}
function show(d){draft=d;revision=d.revision||0;version=0;savedVersion=0;unsaved=false;failed=false;page=0;$('search').value='';$('resume').hidden=true;$('start').hidden=true;$('work').hidden=false;$('title').textContent='Inventaire de '+[d.employee,d.employee2].filter(Boolean).join(' / ');$('scope').textContent=[d.listTitle,d.brand||'Toutes marques',d.range||'Toutes gammes',d.zone].filter(Boolean).join(' · ');$('saveStatus').textContent='Relevé conservé sur ce téléphone';render();message('');}
async function showDrafts(){try{const rows=await S.all();$('drafts').replaceChildren();$('resume').hidden=!rows.some(d=>d.employee!=='TEST TECHNIQUE — articles fictifs');for(const d of rows.filter(d=>d.employee!=='TEST TECHNIQUE — articles fictifs')){const b=document.createElement('button');b.textContent=[d.employee,d.employee2].filter(Boolean).join(' / ')+' · '+(d.brand||'Toutes marques')+' · '+(d.range||'Toutes gammes')+' · '+d.lines.filter(r=>r.quantity!==null).length+'/'+d.lines.length+' comptées · '+new Date(d.updatedAt).toLocaleString('fr-FR');b.onclick=()=>show(d);$('drafts').append(b);}}catch(e){message('Stockage local indisponible : '+e.message,true);$('begin').disabled=true;}}
function options(id,values,label){const old=$(id).value;$(id).replaceChildren(new Option(label,''));for(const value of [...new Set(values.filter(Boolean))].sort((a,b)=>a.localeCompare(b,'fr',{numeric:true})))$(id).append(new Option(value,value));$(id).value=[...$(id).options].some(o=>o.value===old)?old:'';}
function filterOptions(){options('range',C.select(catalogue,$('brand').value,'').map(r=>r.range),'Toutes les gammes');options('zone',C.select(catalogue,$('brand').value,$('range').value).map(r=>r.location),'Toutes les allées');const n=C.select(catalogue,$('brand').value,$('range').value,$('zone').value).length;$('selectionCount').textContent=n+' références dans la liste choisie';$('begin').disabled=!n;$('beginScan').disabled=!n;for(const id of ['brand','range','zone'])$(id).disabled=!catalogue.length;}
function loadList(rows,title){catalogue=C.catalogue(rows);listTitle=title;options('brand',catalogue.map(r=>r.brand),'Toutes les marques');filterOptions();$('listName').textContent=title+' · '+catalogue.length+' références';}
$('brand').onchange=filterOptions;$('range').onchange=filterOptions;$('zone').onchange=filterOptions;
$('begin').onclick=async()=>{if(!$('employee').value.trim()){message('Renseignez votre nom pour identifier le relevé.',true);$('employee').focus();return;}try{await S.all();const rows=C.select(catalogue,$('brand').value,$('range').value,$('zone').value);if(!rows.length)return;show({id:crypto.randomUUID(),employee:$('employee').value.trim(),employee2:$('employee2').value.trim(),listTitle,brand:$('brand').value,range:$('range').value,zone:$('zone').value,createdAt:new Date().toISOString(),lines:rows.map(r=>({...r,quantity:null})),undo:[]});changed();await queue;navigator.storage?.persist?.().catch(()=>{});}catch(e){message('Impossible de préparer une sauvegarde locale : '+e.message,true);}};
$('beginScan').onclick=async()=>{await $('begin').onclick();if(draft&&!failed)$('scan').click();};
$('file').onchange=async()=>{const f=$('file').files[0];if(!f)return;try{if(f.size>12000000)throw Error('Fichier limité à 12 Mo');const text=await f.text();if(f.name.endsWith('.json')){const data=JSON.parse(text);if(data.format==='alcorb-inventory-backup-v1'){const d=data.draft;if(typeof d.employee!=='string'||!d.employee.trim()||!Array.isArray(d.lines))throw Error('Sauvegarde invalide');const clean=C.catalogue(d.lines);show({...d,id:crypto.randomUUID(),revision:0,undo:[],lines:clean.map((r,i)=>({...r,quantity:C.quantity(d.lines[i].quantity),added:!!d.lines[i].added}))});changed();return;}loadList(data.rows||data,'Liste importée : '+f.name);}else loadList(C.parseCSV(text),'Liste importée : '+f.name);message('Liste prête. Choisissez votre périmètre.');}catch(e){message(e.message,true);}finally{$('file').value='';}};
function accepted(r){C.change(draft,r.id,(r.quantity??0)+1);changed();$('lastScan').textContent=r.reference+' · '+r.quantity+' pièce'+(r.quantity>1?'s':'');if(navigator.vibrate)navigator.vibrate(70);try{if(audio){const o=audio.createOscillator(),g=audio.createGain();o.frequency.value=880;g.gain.value=.06;o.connect(g);g.connect(audio.destination);o.start();o.stop(audio.currentTime+.08);}}catch{}render();}
async function detected(code){if(!draft||$('camera').hidden||failed||$('unknown').open||!cooldown.accept(Date.now()))return;const matches=C.lookup(draft.lines,code);if(matches.length===1){try{accepted(matches[0]);}catch(e){message(e.message,true);await stopCamera();}}else{await stopCamera();openUnknown(code,matches.length?matches:C.lookup(catalogue,code));}}
function openUnknown(code='',matches=[]){unknownCode=code;$('unknownText').textContent=matches.length?'Plusieurs références correspondent, ou la pièce est hors de votre liste. Choisissez-la ou ajoutez une nouvelle ligne.':code?'Code absent de la liste : '+code:'La pièce sera ajoutée à ce relevé uniquement.';$('choices').replaceChildren();for(const r of matches){const b=document.createElement('button');b.type='button';b.textContent=r.reference+' · '+r.description;b.onclick=()=>{try{let line=draft.lines.find(l=>l.id===r.id);if(!line){line={...r,quantity:null,added:true};draft.lines.push(line);C.change(draft,line.id,1,true);changed();render();}else accepted(line);$('unknown').close();}catch(e){message(e.message,true);}};$('choices').append(b);}$('unknownRef').value=code;$('unknownDescription').value='';$('unknownLocation').value=draft.zone||'';$('unknown').showModal();}
$('unknownForm').onsubmit=e=>{e.preventDefault();try{if(draft.lines.length>=20000)throw Error('Le dossier contient déjà 20 000 lignes');const reference=$('unknownRef').value.trim();if(!reference)return;const existing=draft.lines.filter(r=>r.reference===reference);if(existing.length){$('unknownText').textContent='Cette référence existe déjà. Choisissez la ligne proposée pour éviter un doublon.';$('choices').replaceChildren();for(const r of existing){const b=document.createElement('button');b.type='button';b.textContent=r.reference+' · '+r.description;b.onclick=()=>{accepted(r);$('unknown').close();};$('choices').append(b);}return;}const r={id:crypto.randomUUID(),reference,description:$('unknownDescription').value.trim(),location:$('unknownLocation').value.trim(),brand:draft.brand||'À préciser',range:draft.range||'À préciser',internal_barcode:'',manufacturer_barcode:unknownCode,quantity:null,added:true};draft.lines.push(r);C.change(draft,r.id,1,true);changed();render();$('unknown').close();}catch(e){$('unknownText').textContent=e.message;}};
$('cancelUnknown').onclick=()=>$('unknown').close();$('manual').onclick=()=>{if(validInputs())openUnknown();};
async function stopCamera(){cameraGeneration++;const old=scanner;scanner=null;$('camera').hidden=true;if(old){try{await old.stop();old.clear();}catch{}}}
$('scan').onclick=async()=>{if(starting||failed||!validInputs())return;starting=true;const generation=++cameraGeneration;$('camera').hidden=false;try{audio=audio||new (window.AudioContext||window.webkitAudioContext)();audio.resume().catch(()=>{});}catch{}const reader=new Html5Qrcode('reader');scanner=reader;try{await reader.start({facingMode:'environment'},{fps:10},detected,()=>{});if(generation!==cameraGeneration){try{await reader.stop();reader.clear();}catch{}}}catch{await stopCamera();message('Caméra indisponible. Autorisez-la dans le navigateur, ou comptez dans les cases.',true);}finally{starting=false;}};
$('pause').onclick=stopCamera;setInterval(()=>{if(!$('camera').hidden){const left=cooldown.left(Date.now());$('ready').textContent=left?'Prochaine prise dans '+(left/1000).toFixed(1)+' s':'Prêt à scanner';}},100);
function undo(){if(draft&&C.undo(draft)){changed();render();$('lastScan').textContent='Dernière action annulée.';}}$('undo').onclick=undo;$('scanUndo').onclick=undo;
$('search').oninput=()=>{if(validInputs()){page=0;render();}};$('previous').onclick=()=>{if(validInputs()){page--;render();}};$('next').onclick=()=>{if(validInputs()){page++;render();}};
$('export').onclick=()=>validInputs()&&download('inventaire-'+draft.id+'.csv',C.csv(draft),'text/csv;charset=utf-8');$('backup').onclick=()=>validInputs()&&download('inventaire-'+draft.id+'.json',JSON.stringify({format:'alcorb-inventory-backup-v1',draft}),'application/json');
$('print').onclick=()=>{if(!validInputs())return;const w=window.open('','_blank');if(!w){message('Autorisez l’aperçu d’impression.',true);return;}w.opener=null;const title=w.document.createElement('h1');title.textContent='Inventaire · '+[draft.employee,draft.employee2].filter(Boolean).join(' / ');w.document.body.append(title);const info=w.document.createElement('p');info.textContent=$('scope').textContent;w.document.body.append(info);const table=w.document.createElement('table');table.style.cssText='width:100%;border-collapse:collapse';for(const cells of [['Référence','Désignation','Emplacement','Quantité'],...draft.lines.map(r=>[r.reference,r.description,r.location,r.quantity??'Non compté'])]){const tr=w.document.createElement('tr');for(const value of cells){const td=w.document.createElement('td');td.textContent=value;td.style.cssText='padding:8px;border:1px solid #aaa';tr.append(td);}table.append(tr);}w.document.body.append(table);w.print();};
$('home').onclick=async()=>{if(!validInputs())return;await stopCamera();await queue;if(unsaved){message('Sauvegarde non confirmée. Exportez votre travail avant de quitter.',true);return;}draft=null;$('work').hidden=true;$('start').hidden=false;await showDrafts();};
setInterval(()=>{if(draft&&!failed&&version!==savedVersion)save();},10000);
window.addEventListener('beforeunload',e=>{if(unsaved||$('lines').querySelector('input:invalid')){e.preventDefault();e.returnValue='';}});document.addEventListener('visibilitychange',()=>{if(document.hidden){stopCamera();if(draft&&!failed&&version!==savedVersion)save();}});window.addEventListener('pagehide',stopCamera);
async function invitation(){const match=location.hash.match(/^#i=([0-9a-f-]{36})\.([0-9a-f]{64})$/i);if(!match)return;message('Chargement de la liste de l’inventaire…');try{const r=await fetch(endpoint,{method:'POST',headers:{apikey:key,'Content-Type':'application/json'},body:JSON.stringify({invite_id:match[1],secret:match[2]})});if(!r.ok)throw Error();const payload=await r.json();if(!payload)throw Error();loadList(payload.rows,payload.title);message('Liste chargée. Votre comptage reste sur ce téléphone.');}catch{message('Lien expiré, indisponible ou connexion absente. Vous pouvez reprendre un inventaire déjà enregistré sur ce téléphone.',true);}}

async function shopList(){
 message('Chargement de la liste du magasin…');
 try{
  let db=window.parent!==window?window.parent.AlcorbAuth:null;
  if(!db){
   await new Promise((resolve,reject)=>{const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2.116.0/dist/umd/supabase.js';s.onload=resolve;s.onerror=reject;document.head.append(s);});
   db=supabase.createClient('https://pryocchvwmnuoidtitow.supabase.co',key);
  }
  const session=await db.auth.getSession();
  if(!session.data.session){message('Pour charger les pièces du magasin, ouvrez Inventaire depuis votre espace connecté, ou utilisez le lien envoyé par l’organisateur.');return;}
  const r=await db.rpc('inventory_current_list',{shop:'8770297c-cadb-4cc6-8b93-55a0f9bd154e'});
  if(r.error)throw Error('La liste du magasin est indisponible. Réessayez avec une connexion, ou utilisez votre lien d’inventaire.');
  if(!r.data){message('Aucune liste préparée pour ce magasin. L’organisateur peut en préparer une avec le lien ci-dessous.');return;}
  if(draft||catalogue.length)return;
  loadList(r.data.rows,r.data.title);message('Liste du magasin chargée. Choisissez votre marque, gamme ou allée.');
 }catch(e){message(e.message||'Liste indisponible. Vérifiez votre connexion.',true);}
}

showDrafts();if(location.hash.startsWith('#i='))invitation();else shopList();if('serviceWorker' in navigator)navigator.serviceWorker.register('sw.js').then(async reg=>{await navigator.serviceWorker.ready;$('offline').textContent='Application disponible hors connexion après ce premier chargement. Exportez avant d’effacer les données du navigateur.';}).catch(()=>{$('offline').textContent='Le mode hors connexion n’a pas pu être préparé. Gardez la page ouverte pendant le comptage.';});
})();
