(()=>{'use strict';const C=InventoryCore,$=id=>document.getElementById(id),shop='8770297c-cadb-4cc6-8b93-55a0f9bd154e',db=supabase.createClient('https://pryocchvwmnuoidtitow.supabase.co','sb_publishable_AQ9cr2Z7Kr6EAravVOgB9Q_Z5Mx2yOZ');let epoch=0,actor=null,rows=[],products=[],busy=false,invitation=null;
const check=r=>{if(r.error)throw Error(r.error.message);return r.data;};function status(s,error=false){$('status').textContent=s;$('status').className='status'+(error?' error':'');}function download(name,text,type){const url=URL.createObjectURL(new Blob([text],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function clear(){busy=false;$('find').disabled=false;$('publish').disabled=false;epoch++;actor=null;rows=[];products=[];invitation=null;$('private').hidden=true;$('link').value='';$('linkBox').hidden=true;for(const id of ['groups','products','invites'])$(id).replaceChildren();}
async function enter(s){if(s?.user?.id&&s.user.id===actor)return;clear();if(!s){status('Connectez-vous dans l’application pour préparer les listes. Les employés utiliseront ensuite le lien sans compte.');return;}actor=s.user.id;const ticket=epoch;try{const m=check(await db.from('scanette_members').select('role').eq('workspace_id',shop).eq('user_id',actor).maybeSingle());if(ticket!==epoch)return;if(m?.role!=='admin')throw Error('La préparation des liens est réservée à l’administrateur de l’application.');$('private').hidden=false;const aisles=check(await db.from('scanette_aisles').select('code').eq('workspace_id',shop).order('code'));if(ticket!==epoch)return;$('aisle').replaceChildren(new Option('Toutes les allées',''));for(const r of aisles.sort((a,b)=>a.code.localeCompare(b.code,'fr',{numeric:true})))$('aisle').append(new Option(r.code,r.code));status('Sélectionnez les pièces, puis attribuez une marque et une gamme à chaque sélection.');await invites();}catch(e){if(ticket===epoch)status(e.message,true);}}
$('find').onclick=async()=>{if(busy)return;busy=true;const ticket=epoch;products=[];$('products').replaceChildren();$('find').disabled=true;$('selectAll').checked=false;try{const term=$('query').value.replace(/[^\p{L}\p{N}\s./-]/gu,' ').trim(),aisle=$('aisle').value;let loaded=[];for(let from=0;;from+=500){let q=db.from('scanette_products').select('id,reference,description,location,internal_barcode,manufacturer_barcode').eq('workspace_id',shop);if(aisle)q=q.ilike('location',aisle);if(term)q=q.or('reference.ilike.%'+term+'%,description.ilike.%'+term+'%');const part=check(await q.order('id').range(from,from+499));if(ticket!==epoch)return;loaded.push(...part);$('found').textContent=loaded.length+' pièces chargées…';if(loaded.length>20000)throw Error('Plus de 20 000 résultats : précisez une allée ou une désignation.');if(part.length<500)break;}
 products=loaded.sort((a,b)=>a.reference.localeCompare(b.reference,'fr',{numeric:true}));for(const p of products){const row=document.createElement('div');row.className='pick-row';const input=document.createElement('input');input.type='checkbox';input.dataset.id=p.id;input.setAttribute('aria-label','Sélectionner '+p.reference);const label=document.createElement('label');label.textContent=p.reference+' · '+p.description+' · '+(p.location||'Sans emplacement');label.prepend(input);row.append(label);$('products').append(row);}$('found').textContent=products.length+' résultats complets. Cochez les pièces de la marque et de la gamme choisies.';
 }catch(e){if(ticket===epoch)status(e.message,true);}finally{if(ticket===epoch){busy=false;$('find').disabled=false;}}};
$('selectAll').onchange=()=>{for(const input of $('products').querySelectorAll('input'))input.checked=$('selectAll').checked;};
function paint(){if(window.parent!==window)window.parent.postMessage({type:'alcorb-dirty',dirty:!!rows.length},location.origin);const groups=new Map();for(const r of rows){const k=JSON.stringify([r.brand,r.range]);groups.set(k,(groups.get(k)||0)+1);}$('groups').replaceChildren();for(const [k,n] of groups){const [brand,range]=JSON.parse(k),div=document.createElement('p'),b=document.createElement('button');div.textContent=brand+' · '+range+' · '+n+' références ';b.textContent='Retirer cette liste';b.onclick=()=>{rows=rows.filter(r=>r.brand!==brand||r.range!==range);paint();};div.append(b);$('groups').append(div);}$('total').textContent=rows.length+' références réparties dans '+groups.size+' listes';}
$('add').onclick=()=>{try{const brand=$('brand').value.trim(),range=$('range').value.trim();if(!brand||!range)throw Error('Renseignez la marque et la gamme de cette sélection.');const selected=new Set([...$('products').querySelectorAll('input:checked')].map(i=>i.dataset.id));if(!selected.size)throw Error('Sélectionnez au moins une pièce.');let duplicates=0;const next=[...rows];for(const r of products.filter(r=>selected.has(r.id))){if(next.some(p=>p.id===r.id)){duplicates++;continue;}next.push({...r,brand,range});}rows=C.catalogue(next);paint();status('Liste mise à jour.'+(duplicates?' '+duplicates+' pièces déjà présentes ont été conservées sans doublon.':''));}catch(e){status(e.message,true);}};
$('file').onchange=async()=>{try{const f=$('file').files[0];if(!f)return;if(f.size>12000000)throw Error('Fichier limité à 12 Mo');const text=await f.text(),data=f.name.endsWith('.json')?JSON.parse(text):null;const imported=data?C.catalogue(data.rows||data):C.parseCSV(text);if(rows.length&&!confirm('Remplacer les listes préparées par celles du fichier ?'))return;rows=imported;paint();status('Listes importées.');}catch(e){status(e.message,true);}finally{$('file').value='';}};
$('template').onclick=()=>download('modele-inventaire.csv','\ufeffRéférence;Désignation;Marque;Gamme;Emplacement;Code interne;Code fabricant\r\n','text/csv;charset=utf-8');
$('package').onclick=()=>{try{download('liste-inventaire.json',JSON.stringify({rows:C.catalogue(rows)}),'application/json');}catch(e){status(e.message,true);}};
$('publish').onclick=async()=>{if(busy)return;const ticket=epoch;try{const clean=C.catalogue(rows),title=$('title').value.trim();if(!title)throw Error('Donnez un nom à l’inventaire.');if(!confirm('Créer un lien sans compte pour ces '+clean.length+' références ? Toute personne possédant le lien pourra consulter cette liste pendant la durée choisie.'))return;
 const fingerprint=JSON.stringify([title,clean,Number($('days').value)]);if(!invitation||invitation.fingerprint!==fingerprint)invitation={id:crypto.randomUUID(),secret:Array.from(crypto.getRandomValues(new Uint8Array(32)),b=>b.toString(16).padStart(2,'0')).join(''),fingerprint};busy=true;$('publish').disabled=true;check(await db.rpc('inventory_create_invite',{shop,invite_id:invitation.id,secret:invitation.secret,document:{title,rows:clean},valid_days:Number($('days').value)}));if(ticket!==epoch)return;const url=new URL('index.html',location.href);url.hash='i='+invitation.id+'.'+invitation.secret;$('link').value=url.href;$('open').href=url.href;$('linkBox').hidden=false;status('Lien prêt. Les téléphones ne partagent aucune quantité.');await invites();}catch(e){if(ticket===epoch)status('Lien non confirmé : '+e.message+'. Vous pouvez exporter la liste JSON en attendant.',true);}finally{if(ticket===epoch){busy=false;$('publish').disabled=false;}}};
$('copy').onclick=async()=>{try{await navigator.clipboard.writeText($('link').value);status('Lien copié.');}catch{$('link').select();status('Sélectionnez et copiez le lien.');}};
$('share').onclick=async()=>{if(navigator.share){try{await navigator.share({title:'Inventaire Alcorb',url:$('link').value});}catch{}}else $('copy').click();};
async function invites(){const ticket=epoch;try{const result=check(await db.rpc('inventory_list_invites',{shop}));if(ticket!==epoch)return;$('invites').replaceChildren();for(const r of result.filter(r=>!r.revoked)){const p=document.createElement('p'),b=document.createElement('button');p.textContent=r.title+' · '+r.article_count+' références · '+(r.revoked?'Lien fermé':'Fin : '+new Date(r.expires_at).toLocaleString('fr-FR'))+' ';b.textContent='Fermer ce lien';b.disabled=r.revoked;b.onclick=async()=>{if(!confirm('Fermer le lien aux nouveaux chargements ? Les comptages déjà enregistrés restent sur les téléphones.'))return;try{check(await db.rpc('inventory_revoke_invite',{invite_id:r.id}));if(ticket!==epoch)return;await invites();}catch(e){status(e.message,true);}};p.append(b);$('invites').append(p);}}catch{$('invites').textContent='Service de liens indisponible ou pas encore activé. L’import et l’export des listes restent disponibles.';}}
$('refresh').onclick=invites;window.addEventListener('beforeunload',e=>{if(rows.length){e.preventDefault();e.returnValue='';}});db.auth.onAuthStateChange((_e,s)=>setTimeout(()=>enter(s),0));db.auth.getSession().then(r=>enter(r.data.session));
})();
