(()=>{'use strict';
// Shared logistics access without account: the list is published as the shop's current list through
// shared_* functions (shop fixed on the server). Guest links stay reserved to members and are not produced here.
const C=InventoryCore,$=id=>document.getElementById(id),call=SharedAccess.call;let epoch=0,actor=null,rows=[],products=[],busy=false,pending=null;function status(s,error=false){$('status').textContent=s;$('status').className='status'+(error?' error':'');}function download(name,text,type){const url=URL.createObjectURL(new Blob([text],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function clear(){busy=false;$('find').disabled=false;$('publish').disabled=false;epoch++;actor=null;rows=[];products=[];pending=null;$('private').hidden=true;for(const id of ['groups','products','invites'])$(id).replaceChildren();}
async function enter(){clear();actor=SharedAccess.ACTOR;const ticket=epoch;try{$('private').hidden=false;const aisles=await call('shared_aisles');if(ticket!==epoch)return;$('aisle').replaceChildren(new Option('Toutes les allées',''));for(const code of LocationSearch.choices(aisles))$('aisle').append(new Option(/^A\d+$/.test(code)?'Allée '+code+' · toutes les sections':code,code));status('Sélectionnez les pièces, puis attribuez une marque et une gamme à chaque sélection.');await invites();}catch(e){if(ticket===epoch)status(e.message,true);}}
$('find').onclick=async()=>{if(busy)return;busy=true;const ticket=epoch;products=[];$('products').replaceChildren();$('find').disabled=true;$('selectAll').checked=false;try{const term=$('query').value.replace(/[^\p{L}\p{N}\s./-]/gu,' ').trim(),aisle=$('aisle').value;const code=aisle?LocationSearch.code(aisle):null,words=term.toLocaleLowerCase('fr');let loaded=[];for(let from=0;;from+=500){const part=await call('shared_products_search',{search_term:aisle&&!code?aisle:aisle?'':term.slice(0,160),aisle:code||'',page_offset:from,page_size:500});if(ticket!==epoch)return;
 // An aisle search returns the whole aisle: the optional words then narrow it here.
 loaded.push(...part.filter(p=>!aisle||!words||(p.reference+' '+p.description).toLocaleLowerCase('fr').includes(words)).map(({id,reference,description,location,internal_barcode,manufacturer_barcode})=>({id,reference,description,location,internal_barcode,manufacturer_barcode})));$('found').textContent=loaded.length+' pièces chargées…';if(loaded.length>20000)throw Error('Plus de 20 000 résultats : précisez une allée ou une désignation.');if(part.length<500)break;}
 products=loaded.sort((a,b)=>a.reference.localeCompare(b.reference,'fr',{numeric:true}));for(const p of products){const row=document.createElement('div');row.className='pick-row';const input=document.createElement('input');input.type='checkbox';input.dataset.id=p.id;input.setAttribute('aria-label','Sélectionner '+p.reference);const label=document.createElement('label');label.textContent=p.reference+' · '+p.description+' · '+(p.location||'Sans emplacement');label.prepend(input);row.append(label);$('products').append(row);}$('found').textContent=products.length+' résultats complets. Cochez les pièces de la marque et de la gamme choisies.';
 }catch(e){if(ticket===epoch)status(e.message,true);}finally{if(ticket===epoch){busy=false;$('find').disabled=false;}}};
$('selectAll').onchange=()=>{for(const input of $('products').querySelectorAll('input'))input.checked=$('selectAll').checked;};
function paint(){if(window.parent!==window)window.parent.postMessage({type:'alcorb-dirty',dirty:!!rows.length},location.origin);const groups=new Map();for(const r of rows){const k=JSON.stringify([r.brand,r.range]);groups.set(k,(groups.get(k)||0)+1);}$('groups').replaceChildren();for(const [k,n] of groups){const [brand,range]=JSON.parse(k),div=document.createElement('p'),b=document.createElement('button');div.textContent=brand+' · '+range+' · '+n+' références ';b.textContent='Retirer cette liste';b.onclick=()=>{rows=rows.filter(r=>r.brand!==brand||r.range!==range);paint();};div.append(b);$('groups').append(div);}$('total').textContent=rows.length+' références réparties dans '+groups.size+' listes';}
$('add').onclick=()=>{try{const brand=$('brand').value.trim(),range=$('range').value.trim();if(!brand||!range)throw Error('Renseignez la marque et la gamme de cette sélection.');const selected=new Set([...$('products').querySelectorAll('input:checked')].map(i=>i.dataset.id));if(!selected.size)throw Error('Sélectionnez au moins une pièce.');let duplicates=0;const next=[...rows];for(const r of products.filter(r=>selected.has(r.id))){if(next.some(p=>p.id===r.id)){duplicates++;continue;}next.push({...r,brand,range});}rows=C.catalogue(next);paint();status('Liste mise à jour.'+(duplicates?' '+duplicates+' pièces déjà présentes ont été conservées sans doublon.':''));}catch(e){status(e.message,true);}};
$('file').onchange=async()=>{try{const f=$('file').files[0];if(!f)return;if(f.size>12000000)throw Error('Fichier limité à 12 Mo');const text=await f.text(),data=f.name.endsWith('.json')?JSON.parse(text):null;const imported=data?C.catalogue(data.rows||data):C.parseCSV(text);if(rows.length&&!confirm('Remplacer les listes préparées par celles du fichier ?'))return;rows=imported;paint();status('Listes importées.');}catch(e){status(e.message,true);}finally{$('file').value='';}};
$('template').onclick=()=>download('modele-inventaire.csv','\ufeffRéférence;Désignation;Marque;Gamme;Emplacement;Code interne;Code fabricant\r\n','text/csv;charset=utf-8');
$('package').onclick=()=>{try{download('liste-inventaire.json',JSON.stringify({rows:C.catalogue(rows)}),'application/json');}catch(e){status(e.message,true);}};
$('publish').onclick=async()=>{if(busy)return;const ticket=epoch;try{const clean=C.catalogue(rows),title=$('title').value.trim();if(!title)throw Error('Donnez un nom à l’inventaire.');if(!confirm('Publier ces '+clean.length+' références comme liste d’inventaire du magasin ? Elle remplacera la liste actuelle dans Inventaire, pour tous les appareils de l’accès logistique.'))return;
 const days=Number($('days').value),fingerprint=JSON.stringify([title,clean,days]);if(!pending||pending.fingerprint!==fingerprint)pending={id:crypto.randomUUID(),fingerprint};busy=true;$('publish').disabled=true;await call('shared_inventory_publish',{invite_id:pending.id,document:{title,rows:clean},valid_days:days});if(ticket!==epoch)return;status('Liste publiée. Elle est chargée dans Inventaire ; les quantités restent sur chaque téléphone.');await invites();}catch(e){if(ticket===epoch)status('Publication non confirmée : '+e.message+' Vous pouvez exporter la liste JSON en attendant.',true);}finally{if(ticket===epoch){busy=false;$('publish').disabled=false;}}};
async function invites(){const ticket=epoch;try{const result=await call('shared_inventory_lists');if(ticket!==epoch)return;$('invites').replaceChildren();for(const r of result.filter(r=>!r.revoked)){const p=document.createElement('p'),b=document.createElement('button');p.textContent=r.title+' · '+r.article_count+' références · Fin : '+new Date(r.expires_at).toLocaleString('fr-FR')+(r.shared?' · publiée par l’accès partagé':' · publiée par un compte')+' ';b.textContent='Retirer cette liste';b.onclick=async()=>{if(!confirm('Retirer cette liste d’Inventaire ? Les comptages déjà enregistrés restent sur les téléphones.'))return;try{await call('shared_inventory_revoke',{invite_id:r.id});if(ticket!==epoch)return;await invites();}catch(e){status(e.message,true);}};p.append(b);$('invites').append(p);}}catch{$('invites').textContent='Listes publiées indisponibles. L’import et l’export des listes restent disponibles.';}}
$('refresh').onclick=invites;window.addEventListener('beforeunload',e=>{if(rows.length){e.preventDefault();e.returnValue='';}});enter();
})();
