/* Loaded only after the PIN server has been installed and verified. */
(()=>{'use strict';
const endpoint='https://pryocchvwmnuoidtitow.supabase.co/functions/v1/logistics-pin',publicKey='sb_publishable_AQ9cr2Z7Kr6EAravVOgB9Q_Z5Mx2yOZ';
const db=window.AlcorbAuth,$=id=>document.getElementById(id),deviceKey='alcorb.logistics.device.v1';
if(!db)return;
let generation=0,busy=false,session=null;
const recovery=document.createElement('details');recovery.id='pinRecovery';const summary=document.createElement('summary');summary.textContent='Première connexion / accès de secours';recovery.append(summary);$('loginForm').before(recovery);recovery.append($('loginForm'));
const panel=document.createElement('section');panel.innerHTML='<h2>Choisissez votre nom</h2><form id="pinLogin" hidden><label for="pinPerson">Votre nom</label><select id="pinPerson" required><option value="">Chargement…</option></select><label for="pinCode">Code PIN personnel</label><input id="pinCode" name="alcorb-personal-pin" type="password" inputmode="numeric" pattern="[0-9]{6}" minlength="6" maxlength="6" autocomplete="new-password" required><button id="pinConnect">Entrer</button></form><p id="pinStatus" role="status"></p>';recovery.before(panel);
const setup=document.createElement('details');setup.id='pinSetup';setup.innerHTML='<summary>Mon code PIN et cet appareil</summary><p>Pour activer ou modifier le PIN, reconnectez-vous d’abord avec votre mot de passe. Cette vérification reste valable cinq minutes.</p><button id="pinPair" type="button">Associer ce navigateur à l’application (administrateur)</button><form id="pinEnrol"><label for="pinNew">Mon PIN · six chiffres</label><input id="pinNew" type="password" inputmode="numeric" pattern="[0-9]{6}" maxlength="6" autocomplete="new-password" required><label for="pinConfirm">Confirmer le PIN</label><input id="pinConfirm" type="password" inputmode="numeric" pattern="[0-9]{6}" maxlength="6" autocomplete="new-password" required><button id="pinSave">Enregistrer mon PIN</button></form><button id="pinRevoke" type="button">Révoquer l’accès PIN de ce navigateur (administrateur)</button><p id="pinSetupStatus" role="status"></p>';document.querySelector('#sections details').append(setup);
async function api(body,authenticated=false,expectedUser=null){const headers={'Content-Type':'application/json',apikey:publicKey};if(authenticated){const r=await db.auth.getSession();if(!r.data.session||r.data.session.user.id!==expectedUser)throw Error('Le compte a changé. Reconnectez-vous.');headers.Authorization='Bearer '+r.data.session.access_token;}const response=await fetch(endpoint,{method:'POST',headers,body:JSON.stringify(body)});const data=await response.json();if(!response.ok)throw Error(data.error||'Connexion PIN indisponible.');return data;}
function getDevice(){try{return localStorage.getItem(deviceKey)||'';}catch{return '';}}
async function roster(){const ticket=++generation;$('pinPerson').replaceChildren();$('pinConnect').disabled=true;$('pinLogin').hidden=true;$('pinCode').value='';$('pinCode').disabled=true;const device=getDevice();if(!device){recovery.open=true;$('pinStatus').textContent='Votre accès PIN n’est pas encore activé sur ce navigateur. Connectez-vous ci-dessous, puis ouvrez Paramétrage → Mon code PIN et cet appareil.';return;}try{const result=await api({action:'roster',device});if(ticket!==generation)return;const placeholder=document.createElement('option');placeholder.value='';placeholder.textContent='Choisir mon nom';$('pinPerson').append(placeholder);for(const person of result.people){const option=document.createElement('option');option.value=person.id;option.textContent=person.name;$('pinPerson').append(option);}$('pinConnect').disabled=!result.people.length;$('pinCode').disabled=!result.people.length;$('pinLogin').hidden=!result.people.length;recovery.open=!result.people.length;$('pinStatus').textContent=result.people.length?'':'Aucun PIN actif sur cet appareil, ou association expirée. Utilisez la connexion de secours.';}catch(e){if(ticket===generation){recovery.open=true;$('pinStatus').textContent=e.message;}}}
$('loginForm').addEventListener('submit',()=>{generation++;$('pinCode').value='';});
$('pinLogin').onsubmit=async event=>{event.preventDefault();if(busy)return;busy=true;const ticket=++generation;$('pinConnect').disabled=true;$('pinPerson').disabled=true;const pin=$('pinCode').value;$('pinCode').value='';try{const data=await api({action:'login',device:getDevice(),person:$('pinPerson').value,pin});if(ticket!==generation)return;const r=await db.auth.setSession(data);if(r.error)throw r.error;}catch(e){if(ticket===generation){recovery.open=true;$('pinStatus').textContent=e.message;}}finally{busy=false;$('pinPerson').disabled=false;if(ticket===generation)$('pinConnect').disabled=false;}};
async function configure(action){if(busy)return;const owner=session?.user?.id,ticket=generation;busy=true;$('pinPair').disabled=true;$('pinSave').disabled=true;$('pinRevoke').disabled=true;try{if(action==='pair'){localStorage.setItem(deviceKey+'.probe','1');localStorage.removeItem(deviceKey+'.probe');const r=await api({action},true,owner);localStorage.setItem(deviceKey,r.device);if(ticket!==generation)return;$('pinSetupStatus').textContent='Navigateur associé pour 90 jours. Chaque personne peut maintenant activer son PIN.';}else if(action==='enrol'){if($('pinNew').value!==$('pinConfirm').value)throw Error('Les deux codes ne sont pas identiques.');await api({action,pin:$('pinNew').value},true,owner);if(ticket!==generation)return;$('pinSetupStatus').textContent='Votre PIN est enregistré. Déconnectez-vous pour utiliser le choix du nom.';}else{await api({action:'revoke',device:getDevice()},true,owner);localStorage.removeItem(deviceKey);if(ticket!==generation)return;$('pinSetupStatus').textContent='Accès PIN révoqué sur ce navigateur. Les sessions déjà ouvertes ne sont pas déconnectées par cette action.';}}catch(e){if(ticket===generation)$('pinSetupStatus').textContent=e.message;}finally{$('pinNew').value='';$('pinConfirm').value='';busy=false;$('pinPair').disabled=false;$('pinSave').disabled=false;$('pinRevoke').disabled=false;}}
$('pinPair').onclick=()=>configure('pair');$('pinEnrol').onsubmit=e=>{e.preventDefault();configure('enrol');};$('pinRevoke').onclick=()=>configure('revoke');
db.auth.onAuthStateChange((_event,s)=>{session=s;generation++;$('pinCode').value='';$('pinNew').value='';$('pinConfirm').value='';if(!s)setTimeout(roster,0);});roster();
})();
